### ISSUE TITLE
wifi notification when already on wifi

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#1]
William received a notification about needing to be on the wifi for playback- he was already on the network- this was build 24

**Comment by donshefer** [comment]
I have tried to replicated this issue but I've not had any luck.

Unfortunately, the app is relying on the Apple's networking framework to report the network changes, and sometimes it gets it wrong. 

If you can give me steps to reproduce this, I can try adding some logic to compensate for the specific situation you are running into.

Sometimes networks changes can happen very quickly. Like walking around your house and connecting and disconnecting from the wifi as you move room to room. Driving around in you car can get pretty spotty as well.

One solution can be to add a timer in there to only trigger if wifi is lost for a curtain amount of time. I've done tweaks like this before but in my experience they are very difficult to get right for everyone. You are just a likely to cause someone issues as you are to fix them for others. 

Unless you have a repeatable case, I would hesitate to add logic like this.

**Comment by RPNate1** [comment]
It hasn't come back up and was likely caused by what you're describing. I'll close this one and if it comes back up, we'll tackle it. I didn't get any real steps to replicate it when it occurred.
