### ISSUE TITLE
Unexpected: long-pressing triggers "peek-and-pop" interaction.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#10]
Long-pressing on tappable items in the History view results in the unexpected appearance of a **"peek-and-pop"** preview tile with '[testing.radioparadise.com](http://testing.radioparadise.com/)" in its title.  

See attached screen recording.

https://user-images.githubusercontent.com/32527656/214940661-1b5fbc68-4d38-4778-8acb-83635a18d32f.mp4

**Comment by RPNate1** [comment]
this should never happen. BUG.

**Comment by donshefer** [comment]
Fixed targeting build 27

**Comment by bradtchapman** [comment]
Seems to be fixed now.  I'm trying to do intentionally dumb / weird user things to induce buggy behavior.

**Comment by RPNate1** [comment]
Works!
