### ISSUE TITLE
💯🎉 (b39) kebab menu *sometimes* stays open after invoking AirPlay menu, resulting in two taps to close it.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#100]
HOORAY 100 ISSUES OPENED!!

### Description of issue
When tapping the AirPlay menu from the kebab, sometimes it stays open unexpectedly after closing the airplay controls.  

It seems to happen less often if you're super quick on the trigger.  Anything longer than 1/2 - 1 second and it will always stay open, requiring two taps to close.  

See attached recording.  

https://user-images.githubusercontent.com/32527656/223822680-8b440782-0bc9-4120-aa2d-d1b4238a91ff.MOV

**Comment by donshefer** [comment]
@bradtchapman @RPNate1 I'm not sure I can do much about this one. Code looks fine.
