### ISSUE TITLE
🐞(b40): Tapping list view from simple mode does nothing.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#101]
### Description of issue

while in simple mode, if I try to access the list view from the kebab, nothing happens.

### Workaround

switch to Info view, then access the list view from the kebab.

see attached screen recording.

https://user-images.githubusercontent.com/32527656/224201478-737f14aa-6105-4eb7-b57f-b7ea19b6ebc6.MOV

**Comment by donshefer** [comment]
Fixed targeting build 41

**Comment by bradtchapman** [comment]
Working in build 41.
