### ISSUE TITLE
📶(b41): App fails real and simulated connection reliability tests

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#103]
### Description of issue
When there is an unreliable connection, the RP app will fail to load music tracks, stop or pause playback for extended periods, fail to load album art, or fail to load all or part of the webpage.

### When / Where does this occur
Unreliable connections can happen when the device is:
- roaming between cellular towers
- has intermittent weak Wi-Fi signal
- temporarily in an area of poor cellular service
- switching from Wi-Fi to cellular

Unreliable connections are a fact of life when using a mobile device, even on Wi-Fi.  Apps **must** be built around these conditions or users will have a poor experience at some point.

### Simulating Unreliable Connections
Both the **Xcode Link Conditioner** and **Charles Proxy** offer "throttling" functions that can simulate connections of varying bandwidths, latency, and reliability.  The latter indicates how often a connection will be made to fail.  The onus is on the app developer to use a method that will keep retrying connections until they succeed.

Even a reliability setting as high as **95-99%** will exhibit problems within a few minutes of testing.  

Please demonstrate this to William and find a way to make it a priority during bug testing with your expanded pool of testers.

**Comment by bradtchapman** [comment]
I think this is a good start in terms of monitoring the app network state and informing the user if there is a problem. 

**The modal dialogue (pop-up) is probably not the best approach**, since it requires the user to tap extra things and gets in the way of their experience of the app.  Also, in testing, the modal dialogue appeared twice: once when the connection went down, and again when it came backup.  The latter was likely just the manifestation of a race condition where the check was performed a bit too quickly before the connection was ready.  

Design-wise, Apple started with modal dialogues in the early iOS versions a decade ago, and has gradually moved away from them in favor of notifications through other means, or making their apps (and the OS) more resilient to transient network issues.  A modal dialogue should be a last resort if the user MUST acknowledge something important.  This is not one of those things.

**Instead, the connection state could be indicated more subtly through a graphical element on screen.**  

I've taken the liberty of mocking up an animation using the RP headphones, which takes up no additional screen real estate, and utilizes an **existing** brand element in a novel way that also serves a **functional** purpose.  

See below.  

* The empty headphones indicate no music is playing.
* The animated yellow indicates "Connecting..." state.
* The static yellow indicates "connection successful, playing music."
* The animated red X indicates "connection error."

![rp-headphones-signal-animation](https://user-images.githubusercontent.com/32527656/226211621-9d36a90d-8431-4f9d-8a98-5de9d7f13a32.gif)



I will email the photoshop document (PSD) that I made for this, which includes layers, layer comps, color overlays, and an animation timeline for reference, should you want to use it as a reference.

**Comment by bradtchapman** [comment]
One more thing... I saw more issues with album art not loading when the network was unstable.  I think I opened another ticket to have a placeholder in the album art square while album art hasn't loaded.  I can see that the physical space on screen is occupied by something now, but the area is still black.  It just needs a permanent layer of basic artwork below the album art inside the box, and the real art appears on top of that once loaded.  Having a generic placeholder communicates more to the user than a black empty void.

**Comment by RPNate1** [comment]
I like this. We already use animated headphones to indicate the currently playing song in List Mode, but I think we could also use this. 
I don't mind the space being held by an invisible object. I'd rather that than the image changing from something generic to the art.

**Comment by bradtchapman** [comment]
The network reachability test is too sensitive and seems to be triggering after one attempt. You've got to use the APIs and frameworks to do the hard work for you, and let them report their status back while continually checking on your behalf.  

Please start with these videos as a foundational guidelines for building an app designed to be resilient in the face of poor network conditions and network transient events:

Optimizing Your App for Today’s Internet: https://developer.apple.com/videos/play/wwdc2018/714/

Advances in Networking, Part 1: https://developer.apple.com/videos/play/wwdc2019/712

Reduce Network Delays for Your App: https://developer.apple.com/videos/play/wwdc2021/10239

Reduce network delays for a more responsive app: https://developer.apple.com/videos/play/wwdc2022/10078/

**Comment by donshefer** [comment]
@RPNate1 Feel free to get me the animation frames for the buffering and network interrupt indicators and I will put them in.

**Comment by bradtchapman** [comment]
So... @RPNate1 ... you're confident that **_all_** the connection reliability tests have been completed, validated, and the app no longer has buffering or loading issues?  😄

**Comment by bradtchapman** [comment]
Unlike Zendesk or IT ticketing systems, Github does allow me to automatically reopen an issue if it's still outstanding.  Only contributors can do that.  I am not.
