### ISSUE TITLE
👇(b43): Intermittent: in the info view, the "selection pop-up" disappears instantly after selecting text, instead of remaining on screen.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#104]
### Description of issue:

When selecting text on the screen in the Info View (web view), a small menu is supposed to appear with options like "Copy," "Look Up," "Translate," "Speak," and "Share."  See picture below for example.  This menu sometimes disappears immediately, instead of remaining on screen and waiting for a user to tap one of the buttons.

I suspect most users will use this feature to copy lyrics for research, or to select a funny comment from another user, or to select a large chunk of their own comment for editing and formatting purposes.  It's not 100% reproducible, but it happened often enough that I felt it warranted a bug report.  Admittedly, this is not a core experience in the app and not a showstopper (unless you feel differently).

### Hardware / software affected:
Reproduced on iPhone SE (1st gen, small screen) and the iPhone 12 Pro.  Therefore it is assumed to happen on all devices.  Both of these phones were running RP 0.9 build 43.

### Demo video
I recorded my interactions with the iPhone 12 from the SE so you can see it happening on a regular sized screen.  See below.

I think the problem might occur more often depending on where the selection is initiated within the web page, but I'm not 100% sure.  Toward the end of the demo recording, you can see that I select some text once and it works, but the next few selections did not.

![IMG_1469](https://user-images.githubusercontent.com/32527656/226217662-8b45c397-70ec-400b-8a02-0de4228a25cf.jpg)

https://user-images.githubusercontent.com/32527656/226218584-455c5ca9-24ec-452d-9479-04f71f295e4b.mp4

**Comment by donshefer** [comment]
I am not able to replicate this on my iPhone 13 running 16.3. It selects text as expected.
@RPNate1 Are you also seeing this? If so, on what device type/version.  My suspicion is that it maybe iOS version related.
@bradtchapman What is the exact iOS version on each device you are using to test?
BTW, I did finally find an iPhone SE gen1 simulator running iOS 15.5. So I should be able to see your UI issues now. I will get them knocked out. It's a very small screen. =)

**Comment by RPNate1** [comment]
I cannot replicate this either. Text selection works as expected. 
@donshefer

**Comment by RPNate1** [comment]
Closing with b45. Cannot replicate. @bradtchapman let me know if this still happens and I'll reopen.
