### ISSUE TITLE
🔎(b43): kebab menu on iPad has really odd spacing, takes up full screen width

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#105]
### Description of issue: 

Sometime in the last couple of builds, the kebab menu was changed to be full width on all devices.  On the iPad, the icons are unevenly spaced and it looks like a mistake.  I don't think this needs all that space for just six icons.  The previous design was fine.

If I had to guess, the icons are in two groups:

[1 2 3] flush left, fixed spacing

[4 - 5 - 6] group fills remaining space; members are spread out evenly with padding set to maximum.

Or the padding between icons 4-5-6 was set to maximum instead of fixed or minimum.

See screenshot below.

![445FD3BE-31F8-4E53-9600-6B32DC049FF4](https://user-images.githubusercontent.com/32527656/226464265-c8687d2e-ff2b-4747-a102-ae8bca26494e.png)

**Comment by bradtchapman** [comment]
Also... sort of related to this menu... that last icon **strongly** suggests "Download."  Since the offline caching function isn't in this release (yet? ever?) it would be best not to mislead users.  Use an "X" instead.

**Comment by RPNate1** [comment]
The download button is the button for the download manager. We are working on getting that implemented.

We will be breaking the mode buttons out of the kebab menu in the iPad version to utilize the real estate better. I keep trying to get to mockups for this and get sidelined. Best to just ignore the iPad layout for now @bradtchapman. it is nowhere near optimized. Coming sooooon...
