### ISSUE TITLE
⏳(b43): If music is stopped, selecting a station shows the "loading gear" forever ... until user presses play.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#106]
### Description of issue

Apart from being comically huge—first build UI weirdness is always excused—the loading gear appears after a station is chosen, but **remains** on screen until the user starts playing music.  Autoplay setting does not matter. 

### Steps to reproduce:

1. Launch app and start playing music.
2. Stop music.
3. Switch stations.
4. Loading gear appears.
5. Artwork / metadata might refresh depending on your current view.
6. Observe that audio does not start, and the loading indicator stays on screen forever.

This was observed on three devices:

- 1st gen iPhone SE (small screen), iOS 15.7.3
- iPhone 12 Pro (medium screen), iOS 15.7.1
- iPad mini 6th gen (large screen), iOS 16.1.1

One way to resolve this is by ensuring that "selecting a station" expresses user intent to start playing music.  Maybe that logic needs to be checked?

Whatever form the loading animation eventually takes, see if you can delay it until the "play" button is pressed or some play-related action begins.

**Comment by RPNate1** [comment]
Selecting a channel should always autoplay.

**Comment by donshefer** [comment]
fixed targeting build 45

**Comment by RPNate1** [comment]
fixed in b45
