### ISSUE TITLE
⏯(b43-b45): MAJOR: Now Playing controls greyed out while playing.  This state survives after killing & relaunching the app.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#107]
### Description of issue

Starting in build 43, the Now Playing controls will become greyed out / untappable after long sessions, or after resuming from a long break.  

Issue appeared in build 43 and persists in build 45.

Controlling RP is still possible remotely (AirPods, Bluetooth, Siri, etc).

Playing audio from another app restores the Now Playing controls, but for that app only.  Switching back to RPv2 finds them disabled again.  

Killing and relaunching RPv2 does not fix this issue. 

### Device Type

iPhone 12 Pro, iOS 15.7.1

### Workaround

Reboot device or reinstall RP.  

The loss of function combined with the severe workaround is why I classified this as a major bug.  

See screenshot for example.

![4550DCB4-68B9-4497-A3EB-9F776BEA2DED](https://user-images.githubusercontent.com/32527656/227252766-a79f6540-b30c-4461-9342-d3e4de6ce9ce.png)

**Comment by bradtchapman** [comment]
UPDATE: downgrading to build 41 restores playback controls immediately. 

The problem returns when upgrading to build 43 or higher.

**Comment by bradtchapman** [comment]
If the app is paused, the "play" button is visible and works here, until the app sends an update to the Now Playing API.

**Comment by bradtchapman** [comment]
Sorry, I am really trying to figure this out.  It's not consistent.

**Comment by RPNate1** [comment]
We can't replicate. Closing until it can be replicated. Perhaps a fresh install of the app will get rid of the issue...
