### ISSUE TITLE
👇(b45-b46): Multiple issues with settings screen: cropped on small SE, fills up whole display, can't scroll, can't swipe to dismiss, difficult to escape.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#108]
### Description of issue

The Settings window has gotten so large that it is difficult to close or dismiss on most phones now.  See attached screenshots.

- On the iPhone SE (1st gen) the window is still truncated and you cannot access the 'log out' item anymore
- On an iPhone 12 Pro, the settings window fills up almost the whole width of the screen.
- The 'escape zone' is an impossibly small sliver at the top and sides, just a few pixels wide.
- The 'Send Feedback' button is missing from the view on the iPhone SE (small screen)
- There is no obvious way to dismiss the window with another gesture such as a swipe or tap.

The design convention on iOS and Android is to design a window that can be **swiped** to dismiss it.  Apple and Google have trained users to do this for years.

**Comment by bradtchapman** [comment]
Scroll Views:
https://developer.apple.com/design/human-interface-guidelines/components/presentation/scroll-views/

Touchscreen Gestures:
https://developer.apple.com/design/human-interface-guidelines/inputs/touchscreen-gestures

Designing Fluid Interfaces:
https://developer.apple.com/videos/play/wwdc2018/803/

**Comment by bradtchapman** [comment]
![rp-b46-settings-iphone-se-1st](https://user-images.githubusercontent.com/32527656/227305002-d1612077-4c1f-4b66-abb1-3030f73c81d6.PNG)

![rp-b46-settings-iphone-12-pro](https://user-images.githubusercontent.com/32527656/227304977-87b4b66e-2e4b-486d-b8f8-f7b67eb988b6.PNG)

**Comment by bradtchapman** [comment]
I see in build 47 that a new modal "card" dialogue has been introduced.  Thanks @donshefer !

Pro-tip: when using this, it is no longer necessary to dim the background since Apple does it for you.  You can remove that step in the sequence for drawing the Settings pane.

**Comment by donshefer** [comment]
minor tweaks to settings menu display
targeting build 49

**Comment by RPNate1** [comment]
Can you restore the tapping outside of the settings panel to dismiss the dialogue? The swipe isn't enough. All three of us at the office this morning were trapped until I reminded everyone to swipe. The feedback was to enable both, is possible.

**Comment by bradtchapman** [comment]
@RPNate1 @donshefer 

The settings card has its own large background of gray.  This is a design error.  Just remove that background and let the card slide to the top of the screen naturally. 

Additionally, ditch the step that darkens RP's main window when the card is open.  

See screenshots.

![FB52A70E-C668-4A9D-9FDF-980999EF87BF](https://user-images.githubusercontent.com/32527656/228012445-149d5499-99a8-4418-a51b-8b4f684bf954.jpeg)
![06D28330-27EB-46F4-9117-69D431060859](https://user-images.githubusercontent.com/32527656/228012452-d5477899-2cf8-4bc2-9f1f-f96ae427512e.jpeg)

**Comment by bradtchapman** [comment]
In this video, you can see a delay while waiting for the card to close before the dark gray disappears.  

The card animation does its own darkening of things behind it.

https://user-images.githubusercontent.com/32527656/228012588-6e64e8e4-3512-4ef3-8193-8ef941f9d90d.MOV

**Comment by RPNate1** [comment]
@bradtchapman were the issues sorted, short of the done button?

**Comment by bradtchapman** [comment]
@RPNate1 : 

- build 50 still has a giant gray background at the top and bottom of the settings card.  Was that going to be addressed soon?
- I haven't checked the small phone today, and am currently at work.  Will check later.

**Comment by bradtchapman** [comment]
@donshefer : the settings card looks great in its animation coming in and out of view.  

Content-wise, it is now very cramped, even on the regular sized phones.   See screen shot and recording below.  It's too easy to tap the wrong button.  The Apple Human Interface Guideline recommends much wider spacing.  

For b51 or b52, is it possible to make transparent the sheet containing the card?  And can you define a "scrollable" area within the settings card, and expand things a bit?  It's too easy to tap the wrong button.

See attached recording / screen shot.

iPhone 12 Pro:

![IMG_1787](https://user-images.githubusercontent.com/32527656/229334558-7fcd6eb4-1093-4976-b446-392b44e9f725.PNG)


iPhone SE 1st Gen (small screen):


https://user-images.githubusercontent.com/32527656/229334572-8afefa06-65ab-4d9e-aada-1ba5ae3ff88c.mp4

**Comment by bradtchapman** [comment]
@donshefer : the buttons for "low" and "flac" are a different size on the small screen.  The text looks larger and the buttons have grown to accommodate.

**Comment by RPNate1** [comment]
How is this looking on the newer builds, @bradtchapman ?

**Comment by bradtchapman** [comment]
The settings pane is now just a static window with an "x" at the top, which I know you wanted for helping users figure out how to dismiss it.  

The audio quality buttons look a bit uneven now: the "low" and "flac" buttons have text that renders slightly larger than the middle 3.  The problem appears on both small screen (SE 1st gen) and a regular sized screen (iPhone 12 Pro).

**Comment by bradtchapman** [comment]
Other than that, you have technically made everything fit on one pane for the SE.   There's no room left, and it honestly feels insanely crowded on the regular sized displays.

**Comment by bradtchapman** [comment]
@RPNate1 : I'm looking at build 54 on both devices.

**Comment by RPNate1** [comment]
There are definitely a lot of settings filling up the panel. All necessary.

**Comment by bradtchapman** [comment]
@RPNate1 Or you could overrule the boss and follow Apple's iOS human interface guidelines and let it grow / scroll beyond one page.
