### ISSUE TITLE
💿(b47): bad metadata on an Etta James track

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#109]
### Description of Issue:

An Etta James track that played recently
shows an album release year of "2000" in the song info, but "1974" in the simple mode, and neither of these has the right album art anyway.

"Leave Your Hat On" was track 16:

https://www.discogs.com/release/3465869-Etta-James-The-Best-Of-Etta-James

This needs a review by multiple parties, possibly including your new sound guru, Joshua, if he is reviewing the catalogue metadata. 

The sole reason I am filing this here is because the app pulled a date of 1974.  Etta James did release an album that year, but not this one.  

![3030E5B0-41A2-490F-8A0D-390560D3CBAB](https://user-images.githubusercontent.com/32527656/227566323-6db5c9be-a25f-46fb-acc3-275232b4c115.jpeg)

![3CD92B28-9AD1-43C6-BD3F-90B49D14BF2F](https://user-images.githubusercontent.com/32527656/227566336-071dfdff-7649-45c8-9af8-f474d2fabe46.jpeg)

**Comment by jarro** [comment]
This is a known issue,  we are in the process of overhauling the music library.
