### ISSUE TITLE
Bug: Unusual split view on resuming the app (History view?)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#11]
See attached screen recording for the observed behavior.

After resuming playback, the media / web viewer was doing something really strange, like showing both the history and the song info.  

After further testing, I was able to reproduce the issue at least once by accessing the "History" view, putting the app to sleep by playing something else, then resuming it a while later.

https://user-images.githubusercontent.com/32527656/214942252-496c4f54-7c0a-4d38-9523-cb7c68da700f.mov

**Comment by RPNate1** [comment]
Oh yeah, what is that?

**Comment by donshefer** [comment]
When you see the web player controls and the Radio Paradise header in the web view, it means the web view has lost it's "embedded mode" state.

I tried reproducing it but I couldn't based on the description.

The web views have been updated so it is possible one of those fixed to issue.
We need to be on the lookout for what links in the web views cause this to happen and then let Jarred know so he can address them.

**Comment by bradtchapman** [comment]
I have seen it happen after RP has been idle for a long time, sometimes not until the next day.  It has to be long enough that RPv2 is put to sleep by the OS and had its working memory reservation released back to the system.

Start playing in RPv2 for a few songs.
Play something else in a different app.
Ignore RPv2 for a long time and start launching other apps on your device to force the app to sleep
Relaunch RPv2.  
You should see two things:

- The last played song name should still be in the info bar
- The RP home page loads in the non-embedded view, and the station + playback controls will be shown here
- The play/pause button is showing the "pause" state (as if music was still playing)
- If you tap Pause, music will resume.

If you press Pause, the last song playing will resume, but eventually will stop and no more music will load.

Can you send something special in the UserAgent string, so that the website always knows the player app is requesting content?

-Brad


—Sent from my iPhone

**Comment by RPNate1** [comment]
I can't recreate this. @bradtchapman still seeing this ever?

**Comment by bradtchapman** [comment]
Constantly. 

—Sent from my iPhone

**Comment by donshefer** [comment]
On further testing, I have not been able to replicate any of these issues. @bradtchapman, please be sure you are on the latest build and retest. There have been several fixes that should address these issues.

**Comment by bradtchapman** [comment]
This is one of the earlier bugs I filed.  It's possible that this was addressed as early as build 26, or with changes made by Jarred on the website.  

—Sent from my iPhone
