### ISSUE TITLE
💿(b47): Inconsistent metadata on one track

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#110]
Album name "Thrak" is capitalized as THRAK on the song info view, but Title Case "Thrak" in the simple player.  The web view is correct.   The app is not.

See screen shots.  

![1C25293C-A007-49BD-8CD4-2544687A682F](https://user-images.githubusercontent.com/32527656/227569969-bd3b6687-da0b-43fc-a5de-245263369e9e.png)
![0F097390-93D8-46C5-A54F-24732615B653](https://user-images.githubusercontent.com/32527656/227569979-65be0264-fdbc-4fc0-b6c8-099bd5c43f38.png)

**Comment by RPNate1** [comment]
Weird. What's going on here @donshefer ?

**Comment by bradtchapman** [comment]
@RPNate1 @jarro @donshefer : check the /api/gapless code to see if it's Transforming Everything Into Title Case.  

I gave you lots to investigate in Issue #109 , demonstrating that the APIs are sending different information.

**Comment by RPNate1** [comment]
This is on Jarred and Jon's end
