### ISSUE TITLE
🐞(b47): Tapping "send feedback" does not create an email as before

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#111]
### Description of issue: 

In the new Settings card, the "Send Feedback" button dismisses the card but doesn't appear to do anything else.  Previous builds created a new email with attached logs.

### Observed on:

- iPhone 12 Pro, iOS 15.7.1
- iPad Mini 6, iOS 16.1.1
- (feedback link is not shown on iPhone SE 1st gen)

### Workaround

Downgrade to b46 or lower to send feedback.

**Comment by donshefer** [comment]
fixed in build 49

**Comment by RPNate1** [comment]
works on b49
