### ISSUE TITLE
navigation ipad mini

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#112]
most of the buttons in the popup  more  menu   activate  airplay.

**Comment by bradtchapman** [comment]
This is not an example of a good issue ticket.  Please include the following details:

### Description of Issue

### Steps to Reproduce

### Devices Affected

### Workaround if any

**Comment by jarro** [comment]
![image](https://user-images.githubusercontent.com/301056/228975374-645b56a6-f818-48da-bb5f-6870c26f8b21.png)

The yellow area  activates the airplay icon.
Issue survived reboot.   

Device is latest ipad mini.   Fully updated  
v50 according to testflight

Might need a mini to reproduce it,  but hard to miss.

**Comment by donshefer** [comment]
@jarro We haven't really started iPad testing yet because Nate is planning to give me a redesign of it.

**Comment by bradtchapman** [comment]
FYI - this does *not* seem to happen on the iPhones, but the AirPlay icon seems to have been given a wider berth than the rest of the icons.  

The kebab is getting pretty cramped with 7 icons now.  Consider two rows.

**Comment by RPNate1** [comment]
This is across the board on ipads and the desktop app as well. I'm spending this week tweaking the layouts and getting them to Don so we can get the icons situated and working.
