### ISSUE TITLE
b54/Website: blue support banner is pushing song title info out of frame 

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#115]
In the info view, on a standard iPhone screen, the blue banner is tall enough to push the song info down so it becomes partly cropped.  

Concerned that a usability tradeoff was made to accommodate a rather large banner.

![IMG_2113](https://user-images.githubusercontent.com/32527656/232120739-baa0b9b1-a77e-478f-bcaa-8a66a22c95dc.jpeg)

**Comment by RPNate1** [comment]
The banner is temporary. We'll be losing a bit of the padding on the play bar as well.

**Comment by RPNate1** [comment]
Banner is gone, but I will make sure that in the future we test it on a version of the app before we launch it wide.
