### ISSUE TITLE
b54: songs previously voted are not showing my vote when playing again

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#117]
I know for damn sure I voted this one a 10 the last time it came up.  But the heart is gray right now.  I loaded my profile's play history just to double check. 

I expect the hearts to show my last vote whenever they play.

![IMG_2166](https://user-images.githubusercontent.com/32527656/232671930-b0aff334-b958-4705-ab8b-964f6f29125a.png)

**Comment by RPNate1** [comment]
@donshefer let's get that fixed!

**Comment by bradtchapman** [comment]
Hey @RPNate1 @donshefer : this appears to be working again.  I first noticed it this morning.  Did it get fixed in the API?  Or was the Pink Floyd song a kind of weird glitch?

**Comment by donshefer** [comment]
@bradtchapman I tested and was not able to replication this issue.

**Comment by bradtchapman** [comment]
That's sort of why I was wondering if this was an API glitch.—Sent from my iPhoneOn Apr 20, 2023, at 1:35 AM, Don Shefer ***@***.***> wrote:﻿
@bradtchapman I tested and was not able to replication this issue.

**Comment by RPNate1** [comment]
Sounds like an API glitch. Jarred is poking around in there as we are preparing other things, so this may pop up. Probably not an app bug.
