### ISSUE TITLE
[BUG] b55: From list view, tapping (i) in kebab always switches between simple and list view, never to info.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#119]
## Brief description of the issue:

After tapping (i) Info button from list view, app switches to simple mode.  Tapping (i) again unexpectedly switches back to the List view, instead of going to Song Info.

### Steps to reproduce:

1. Start playing.
2. Tab Kebab, then the hamburger (list view). 
3. Tap Kebab, then Info button.  App switches to simple player.
4. Tap Kebab, then Info.  App switches back to list view, instead of Song info.

See screen recording linked below for demo.

### Where did you see it? (App build version, device type and iOS version): b55, iPhone 12 Pro, iOS 16.4

*(Please provide screenshots or error message text when possible.)*

See recording below.

https://share.icloud.com/photos/002Y_HwzPJG0nAZwGE7ZZGi4Q

**Comment by donshefer** [comment]
Fixed in build 56

**Comment by RPNate1** [comment]
Fixed!
