### ISSUE TITLE
[BUG] b55: Another song previously rated that fails to show my last vote

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#120]
## Brief description of the issue:
this might look like a duplicate bug, and it is. I found another song that I previously rated a 10, but the vote heart next to the song title is gray.  I checked the play history on my account, and it shows a 10 for this song.

I am starting to wonder if this only affects songs that were voted 10, or if there was an API change that resulted in some votes not being counted or displayed properly on the client side. 

See screenshot.   

### Where did you see it? (App build version, device type and iOS version): b55, iOS 16.4, iPhone 12 Pro

*(Please provide screenshots or error message text when possible.)*

![IMG_2293](https://user-images.githubusercontent.com/32527656/234749575-f3b80109-73a2-461d-b0a6-0c3cdd98208b.png)

**Comment by RPNate1** [comment]
Let's take a look at this @donshefer I want to make sure this isn't going to happen to others. I haven't seen it myself yet...

**Comment by bradtchapman** [comment]
Couple of thoughts...

- Maybe it only happens to older user accounts.
- Maybe it only happens to songs that received votes before/after an API change
- Maybe it only happens to songs with a certain ID range (older titles in the library).  Jeff Buckley and Pink Floyd would have been in RP's library for a while.

On that note, can you add a field in the app or website that shows the date it was added to RP?

**Comment by RPNate1** [comment]
@jarro Ideas on why this might happen?

**Comment by jarro** [comment]
It looks like state management stuff.  
If the song is rated in the webview.  It will broadcast that.   And you need to apply it to any in app songs.   And vice versa.
Or if it's rated offline.   It's a pita.

**Comment by bradtchapman** [comment]
At what point does the app check for ratings?  When each block of songs is loaded?  Or at play time?

**Comment by bradtchapman** [comment]
Here's something I did: 

1. Start playing RP on the phone.
2. Go to the RP website on a computer and start playing the same stream.
3. Skip a couple of songs ahead.
4. Vote on it.
5. Wait until the phone catches up.
6. The vote I just cast it not shown.
7. Stop the stream on the phone.
8. Start the stream on the phone.
9. My previously cast vote for that song is now shown in the app.
10.

**Comment by donshefer** [comment]
I believe the app is only loading the rating with the initial song load. If the song is rated from within the app, the rating is updated. But it is not polling for any changes that might occur outside of the app. For example, if the user adds a rating on another platform. I didn't think that was needed. @RPNate1 Is this something we need to support?

**Comment by bradtchapman** [comment]
My opinion: if it is William's intent to make RP a holistic and seamless experience between all platforms, then the vote routine probably needs to check every time the song is loaded on any device.  Make it an asynchronous request.  The song starts immediately, while the most recent user vote and/or song metadata is polled via API.  And obviously if someone casts a vote from one platform, it overrides the last vote.  No need to check for vote convention: the last vote always wins.

**Comment by bradtchapman** [comment]
It would definitely be overkill for the app or the website to poll continuously, watching for changes from one platform.  The last vote always wins.  No user is going to be checking to see if their phone updates the vote in real time.  Load on next play is good enough, I think.

**Comment by RPNate1** [comment]
Don and Jarred discussed and it should be dealt with. I haven't been able to replicate this but will keep an eye out going forward.
