### ISSUE TITLE
[BUG] b57: Offline Caching: the station buttons need a full size tap zone.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#121]
## Brief description of the issue:
Tap zone is only over the word, not the entire button.

### Steps to reproduce:
Tap a station in the offline caching section.  

### Expected result:
Tap entire button / line.

### Actual result: 
Had to tap the actual text... this was unexpected and made me think the button was broken.

### Where did you see it? (App build version, device type and iOS version):

*(Please provide screenshots or error message text when possible.)*

![IMG_3125](https://user-images.githubusercontent.com/32527656/236059956-18bac95c-7db1-48ec-88a4-a2ac684c9d1d.jpeg)

**Comment by donshefer** [comment]
fixed in build 58

**Comment by RPNate1** [comment]
@donshefer still have to click text in b58 on my 11 pro

**Comment by RPNate1** [comment]
The whole line (as shown with the red rectangles in Brad's image above) would be preferable to the current text/small button. @donshefer

**Comment by donshefer** [comment]
@RPNate1 It should be working that way now. Is it still not in build 60?

**Comment by RPNate1** [comment]
Sorry, I hadn't updated to 60, I guess...

**Comment by RPNate1** [comment]
No, It didn't work that way. @donshefer

**Comment by bradtchapman** [comment]
The tap zones are functioning properly; however, the buttons need a different color for the "pressed" and "active" states: while my finger is holding it down, and while it is the active selection.  The yellow text is not distinctive enough at a glance.  Are these controls not standard UIKit buttons?  Apple has standardized behavior for how buttons animate and change color when you interact with them.  -Brad—Sent from my iPhoneOn May 17, 2023, at 12:35 PM, Don Shefer ***@***.***> wrote:﻿
@RPNate1 It should be working that way now. Is it still not in build 60?

**Comment by RPNate1** [comment]
They do work. Let's add the color change as Brad suggests.

**Comment by RPNate1** [comment]
I requested th e color changes as suggested but the initial bug is fixed in b60. closing!
