### ISSUE TITLE
[BUG] b58 - comments in simple mode are rendered too small

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#122]
## Brief description of the issue:

Build 58 adds the comments button, but the comments are too small by default.  I discovered by trial that this screen has pinch-to-zoom, but most users won't discover this intuitively, or find it very useful.   The screen should be enjoyable with one hand / one finger scrolling. 

Check that the comments are rendered with a media window width that corresponds to the device's actual width.  The ideal size is whatever the new Lyrics view uses. 

### Steps to reproduce:
Load the comments from simple mode

### Expected result:
I expected the comments to be a comfortable size

### Actual result:
The comments are too small.

### Where did you see it? (App build version, device type and iOS version):
Build 58, iPhone 12 Pro, iOS 16.4.1

*(Please provide screenshots or error message text when possible.)*

![IMG_4216](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/b85f99f9-c11b-487e-83b6-ebc928bed4b0)

**Comment by donshefer** [comment]
fixed in build 59

**Comment by RPNate1** [comment]
Fixed as Don said.
