### ISSUE TITLE
[BUG] b58 Caching more than 30 songs yields less than requested amount

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#123]
## Brief description of the issue: 
In the new song caching / offline listening tool, if you request more than 30 songs in any mode, it will download less than the requested amount.  

### Steps to reproduce:
1. Access the caching feature.
2. Add a download.
3. Select any station and bitrate.
4. Select 35 or 40 songs.
5. Press Download.

### Expected result: 
The exact number of songs (35 or 40)

### Actual result: 
I received 31, 32, or 35 during testing. 

### Where did you see it? (App build version, device type and iOS version): 
b58, iOS 16.4.1, iPhone 12 Pro.

*(Please provide screenshots or error message text when possible.)*

**Comment by RPNate1** [comment]
This is something we're aware of and needs to be dialed in. @jarro and @donshefer

**Comment by RPNate1** [comment]
Currently does the 40 song allotment. Will expand this but it is working in b60.

**Comment by bradtchapman** [comment]
This is still not working as intended and was just reported in #150 .  I've closed that one as a duplicate and reopened this one.

**Comment by RPNate1** [comment]
DL manager is getting revamped with functions as expected

**Comment by donshefer** [comment]
should be functioning as expected in build 66

**Comment by JohnADilley** [comment]
Cache request in b66 is now expressed in hours not songs.
The behavior is better, although it may not get all the way the the time requested.
Just now I requested four hours of global mix high bitrate and got 3h23m.  
I was unable to add to the cache block by requesting 4h more (or any time amount).

**Comment by RPNate1** [comment]
I was able to add to my download block and got the requested size. Hmmm.
I'm on b67 but I don't think there was a change to DL manager with that
update.

**Comment by donshefer** [comment]
@RPNate1  When requesting a number of minutes, I am translating that into number of songs using  an average song length of 3.5 minutes. The total time returned depending on the actual length of the songs downloaded. That is why it is sometimes more or less. I have tried to average it as best I can but there are outlier songs that are longer or shorter.

**Comment by bradtchapman** [comment]
@donshefer : when the songs are downloaded, is there no method to query each one and ask its length, then add them up?

**Comment by RPNate1** [comment]
Jarred has always used an average, as well.

**Comment by RPNate1** [comment]
@jarro what's the average you've used in the past?

**Comment by jarro** [comment]
We've been using 4 minutes.   It's worked well enough.  With some songs being 40 minutes it would never be bang on.
There is also  a   lengthMinutes  parameter  that  just  divides by 4.   But in theory could be improved down the line if it seems egregious.
https://api.radioparadise.com/api/gapless?lengthMinutes=200

**Comment by RPNate1** [comment]
@donshefer let's up your average to 4 minutes like we've used historically according to Jarred.

**Comment by donshefer** [comment]
Change average song length to 4 minutes, matching server
updated in build 73

**Comment by RPNate1** [comment]
This appears to be fixed in b73. Open new reports if there are additional DL manager issues.
