### ISSUE TITLE
[UI FB] Website / Info View: lyrics collapsed with a chevron not immediately obvious how to expand

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#124]
## Brief description of the issue:
Lyric view on the info pane are now collapsed and there is a chevron on the right side of the screen.  It is not immediately obvious that the lyrics are collapsed.  There needs to be an [...] ellipses below the last visible line, and make this tappable.  Or just show all the lyrics by default.  

See attached screen recording.  

### Steps to reproduce:
Play any song and display the info view.  

### Expected result:
All lyrics visible. 

### Actual result:
Lyrics collapsed.  

### Where did you see it? (App build version, device type and iOS version):
b58, iOS 16.4.1, iPhone 12 Pro

*(Please provide screenshots or error message text when possible.)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/c8aad5af-175e-4f41-9d65-c31b21171edd

**Comment by RPNate1** [comment]
I asked @jarro to add the ellipses

**Comment by bradtchapman** [comment]
Jon vetoed the ellipses or he vetoed your hatred of it ?—Sent from my iPhoneOn May 17, 2023, at 11:49 AM, RPNate1 ***@***.***> wrote:﻿
I hated the ellipse and Jon vetoed it.

**Comment by RPNate1** [comment]
Vetoed the ellipses.

**Comment by bradtchapman** [comment]
What about putting the chevron below the abbreviated lyric block?  That way you have a clear indicator as to what to do, and it still serves the same role.—Sent from my iPhoneOn May 17, 2023, at 12:37 PM, RPNate1 ***@***.***> wrote:﻿
Vetoed the ellipses.

**Comment by RPNate1** [comment]
Deal. @jarro make it so!

**Comment by RPNate1** [comment]
Turns out the ellipses at the bottom of the lyrics is what was implemented and it works for me. Fixed in b61
