### ISSUE TITLE
[BUG] b58: Unexpected behavior: sleep Timer does not block interaction with the rest of the app, and is missing its shadow.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#125]
## Brief description of the issue:
The sleep timer dialog box is not modal; it is not blocking interactions with the rest of the app.  Additionally, the shadow is not there.  

### Steps to reproduce:
Load the app.
Click the Kebab.
Click the Sleep timer icon.
Tap or double-tap on anything behind it - menu, album art, settings, etc...

### Expected result:
Interactions should be blocked until the sleep timer dialog is closed.

### Actual result:
Interactions are possible (unexpected).

### Where did you see it? (App build version, device type and iOS version):
b58, iOS 16.4.1, iPhone 12 Pro

*(Please provide screenshots or error message text when possible.)*

**Comment by RPNate1** [comment]
Placed in Trello for Don.

**Comment by donshefer** [comment]
fixed in build 60

**Comment by RPNate1** [comment]
confirmed fixed in b60
