### ISSUE TITLE
[BUG] b61: Unexpectedly cannot double-tap some areas in Simple Mode (to switch to Info mode)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#126]
## Brief description of the issue:
On the Simple Mode screen, apparently it is possible to switch to Info Mode by double-tapping on anything: the song title, album art, histogram., vote count, etc.  However, I found that only the **actual objects** are tappable, and not the dead space behind them.  For ease of use, I think it would help to have the entire area tappable. Otherwise, the user might think it doesn't work, or that it only works sometimes and not others.

See attached screenshot.  Green = currently tappable, red = not tappable, but should be.

### Steps to reproduce:
1. load any song in simple mode.
2. Try double-tapping the black space where a song title does not intrude (i.e.: right hand side of the screen, with a shorter song title)
3. Now try double-tapping the actual words.

### Expected result:
I expected double-tapping anywhere to change to info mode.

### Actual result:
Only the elements on screen actually respond to double-tapping.  The background is not considered a tappable element.

### Where did you see it? (App build version, device type and iOS version):
b61, iOS 16.4.1, iPhone 12 Pro

In the screenshot below, the green zones are currently tappable.  The red areas are not tappable, but should be made tappable for ease of use and to avoid possible user frustration.

![rp-tap-zones-b61-simple](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/1e490601-40dd-4e5a-a65f-952b02a51686)

**Comment by RPNate1** [comment]
The only tappable/swipeable object is the album art. A swipe up or double tap invokes Info mode. To return to Simple mode is the same, double tap on the album art. Additionally, tapping on the gold song info in the play bar will return the user to Simple mode from anywhere. Working as intended.
