### ISSUE TITLE
[BUG] b61 offline caching: swipe up gesture should NOT be permitted

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#127]
## Brief description of the issue:
when listening to an off-line block of music, there should be no way for a listener to access the info page at all. 

I have discovered that swiping up on **ART, SONG TITLES, AND HISTOGRAM** will reveal the info mode.

### Steps to reproduce:
1. download a block of songs and start listening to it.
2. Swipe up on the album art.
3. Info mode loads unexpectedly

### Expected result:
The app should not attempt to make a connection to the Internet

### Actual result:
it does. 

### Where did you see it? (App build version, device type and iOS version): b61, ios 16.4.1, iphone 12 pro

*(Please provide screenshots or error message text when possible.)*

**Comment by RPNate1** [comment]
Good one. I knew you couldn't resist leaving us at zero bugs. It must have felt like a challenge...

**Comment by bradtchapman** [comment]
No rest for the wicked, as they say... :-)

**Comment by RPNate1** [comment]
fixed b62
