### ISSUE TITLE
[CRASH] b61: while playing offline cached music and updating the song remaining count.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#128]
## Brief description of the issue:
After caching a block of music, sometimes skipping ahead will result in the app crashing.  Wild guess: it's an 'out of bounds' issue where the app is trying to read items beyond the end of an array.  The count of songs remaining is not consistent or exact, and sometimes decreases by more than 1.  The crash occurred as the app was updating the # of songs remaining, for the purposes of displaying this in the station list.

### Steps to reproduce:
1. Request an offline block of music, any station, any quality, any quantity of songs.
2. Start playing the offline block.
3. Change to an ONLINE station (e.g.: RP Main)
4. Change station back to the offline cache.
5. Tap the station selector several times after each song, and note the # of songs remaining
6. Skip a song while offline OR perform Step 3.
7. Repeat steps 4-6 until a crash occurs.

### Expected result:
App should be able to list the blocks and the remaining song count accurately without crashing.

### Actual result:
App did not perform as expected and crashed.

### Where did you see it? (App build version, device type and iOS version): b61, iOS 16.4.1, iPhone 12 Pro

*(Please provide screenshots or error message text when possible.)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/c9d1c158-28ec-4157-b8df-d3d5de77b52f

**Comment by bradtchapman** [comment]
Attaching three crash analytics from the phone...

**Comment by bradtchapman** [comment]
[RadioParadiseMk2-crash-analytics.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11512334/RadioParadiseMk2-crash-analytics.zip)

**Comment by RPNate1** [comment]
The mode icons disappeared as well. I noticed that couple times on my phone.

**Comment by donshefer** [comment]
crash fixed in build 63

**Comment by bradtchapman** [comment]
This might not still be 100% fixed in b63.  I was able to **hang** the app again when attempting to play an **empty block** more than a couple of times.  Edit: the app just crashed.  TestFlight submitted a bug report from my phone at ~6:25 - 6:30 PM.

The offline block contained a station bumper, which decreased the song count by 4 (including the next song).  I reported this in a different issue, so it might be related.

**Comment by donshefer** [comment]
@bradtchapman I am pretty sure at this point that this issue is fixed in build 63. I can now see the crashes live through sentry.io and I am no longer seeing this crash show up.
If you were trying to play an empty block more than a couple of times, I would kind of expect the app to hang. Certainly a different issue. The download manager is being completely overhauled.

**Comment by donshefer** [comment]
fixed in build 66
