### ISSUE TITLE
[BUG] b61: comment count is cramped in the icon for very popular and long-standing songs

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#129]
## Brief description of the issue:
The song "Hallelujah" by Jeff Buckley has over 1,500 comments.  Anything by Pink Floyd, or other long-standing songs in RP's library, are guaranteed to have hundreds of comments.  The comment icon needs to be expanded to fit these rare cases where the comment count does not start with, or contain, any 1's (which, in a proportional font, are rather slender).  I have other screenshots (see below) showing that even a comment count of 200-999 will appear cramped inside the icon.

### Steps to reproduce:
Play a song that has a large number of comments.  Examine the comment icon and observe the (lack of) space between the numerals and the wall of the comment icon.

### Expected result:
The comment box has enough room to display all numbers with 'breathing room' 

### Actual result:
Numbers were cramped or overlapping the icon.

### Where did you see it? (App build version, device type and iOS version): 
Starting in b59 actually, after the icon was changed.  iOS 16.4.1, iPhone 12 Pro

![IMG_4297](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/70c5ccad-f053-4685-8ec6-484036b6fc07)

![IMG_4263](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/df5234db-6c29-4947-b01c-3b6ae379e162)

![IMG_4262](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/77a671e9-b431-461c-b8d6-fb9b5a809a1f)

If I may, I would suggest sizing the icon for "8888" and then centering the actual count.

**Comment by donshefer** [comment]
Fixed in build 62
