### ISSUE TITLE
Unexpected: tapping "Back" from the History View goes to the Home Page (A).

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#13]
If I am listening to a song, the default view is the album info view.  

If I tap "History" to view the most recent tracks, and want to go back to the song / album art view, I see the "Back" button at the top and expect that to take me there.

Instead, the "Back" button loads the Radio Paradise home page, which is the same as clicking the RP headphones at the top of the screen, or the "(A)" button at the top right (not sure what that's for?)

I think most listeners will expect that they'd like to logically go back to what they were doing before, which is listening to a song.  App interactions should be stateful: remember what the user was doing, and let them go back logically.  If this is not possible, give them an easy out to reset to a preferred default state.

If the app design tells users "You can't go back; you have to go forwards in order to go back" a la Willy Wonka and the Chocolate Factory, they'll just end up confused.

**Comment by RPNate1** [comment]
I agree with this. I'm not afan of the back button. I'm not sure how to fix this. We need to discuss all the cases and behavior.

**Comment by donshefer** [comment]
I updated the back button to hide and show as appropriate.
The fix is targeting build 27.

**Comment by RPNate1** [comment]
Appears to work properly. Will keep an eye on it.
