### ISSUE TITLE
[BUG] b61: Tapping on the cached item prematurely while downloading may start playback, lead to inaccurate song count and possible crashes

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#130]
## Brief description of the issue:
By accident, I tapped on a cache that was still downloading, and it began to play.  I did this repeatedly and found that the song count could be as low as 5, but eventually I could get the app to crash if tapping an in-progress block was the first action.

Note: to test this effectively, you may need to use a connection that is a little slower than gigabit fiber-optic so it is slow enough to observe and repeat the behavior consistently.  

The download manager should not allow tapping the music block until it is fully prepared for offline listening.

### Steps to reproduce:
1. Access the download manager.
2. Start downloading a block of music (e.g.: Main, High, 20 songs)
3. Tap on the item representing the cached block until it begins to play (the download manager will be dismissed).
4. Go back to the Download manager (via kebab or station selector).
5. Observe that the download is still in progress.
6. Tap the block again.
7. Tap the station selector to check the song count.  Note any discrepancies.
8. Skip songs and check the song count each time.

### Actual result:
The app crashed **un**expectedly while skipping.

NOTE: Also check the song count right around the RP bumper.  It jumps from 19 down to 16.

### Where did you see it? (App build version, device type and iOS version): b61, iOS 16.4.1, iPhone 12 Pro

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/cfb6e082-8001-4cfc-967e-aa461f2e2407

**Comment by donshefer** [comment]
fixed in build 62

**Comment by RPNate1** [comment]
@bradtchapman check this please?

**Comment by bradtchapman** [comment]
Yes.  Appears to be fixed.  In build 62, it is no longer possible to tap the block before the songs are fully downloaded.
