### ISSUE TITLE
[BUG] b61 Typo in offline caching page: "swift left to remove" should be "swipe"

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#131]
## Brief description of the issue:
Grammatical / typo error on text label.  Unless the developer was asking people to make a **_swift_** gesture to remove it.  ;-) 

### Steps to reproduce:
1. Access the download manager.
2. Access a dictionary.

### Expected result:
Text should read "swipe left to remove."

### Actual result:
Text reads "swift left to remove."

### Where did you see it? (App build version, device type and iOS version): b61, iOS 16.4.1, iPhone 12 Pro

![IMG_4302](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/d4622b2b-23b0-4930-8806-6d52ee67e994)

**Comment by donshefer** [comment]
fixed in build 62

**Comment by bradtchapman** [comment]
Yes, confirmed OK in Build 62.
