### ISSUE TITLE
[BUG] b62 offline listening tries to load data while in Airplane mode, resulting in repeated network error messages

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#132]
## Brief description of the issue:
When starting an offline block from Airplane mode—or engaging Airplane mode while listening to an existing offline block—the RP app displays connection error modal alerts.  This is inappropriate for a mode designed for offline listening.

It appears the app is trying to load the lyrics and comments.  These **_must_** be fetched while the block is being generated, not after.  OR, you need to warn users that Lyrics and Comments are unavailable while listening offline.  I do believe you intended for this data to be available and portable with the offline block, though I can't comment on the legality of saving lyrics to an ephemeral cache.

### Steps to reproduce:
1. Create an offline block in the Download manager.
2. Engage Airplane mode.
3. Tap to play the block.
4. You will see an error message immediately.

Alternatively: switch steps 2-3, then skip a song.  You'll receive an error message also.

### Expected result:
Offline mode should pre-cache everything and not try to fetch data.

### Actual result:
Offline mode fetched data unexpectedly.

### Where did you see it? (App build version, device type and iOS version): b61, iOS 16.4.1, iPhone 12 Pro.

*(Please provide screenshots or error message text when possible.)*

With pleasure!

![IMG_4308](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/5db0599b-2b91-445b-8386-0badc897db69)

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/28a2f67d-3db3-430e-ac1d-f681f9e6b343

**Comment by RPNate1** [comment]
Lyrics and comments should be cached, not fetched.

**Comment by RPNate1** [comment]
This appears to be fixed for me.

**Comment by bradtchapman** [comment]
This is *not* fixed in b62.  

Warning appears after the first song.  The download manager needs to cache lyrics and comments for ALL songs.  

See attached screen recording.

**Comment by bradtchapman** [comment]
Recording attached. 

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/121e3fc8-83b4-455d-bcf4-30553e28bb84

**Comment by RPNate1** [comment]
The lyrics and comments should be pre-loaded. @donshefer take a look at what's happening here.

**Comment by donshefer** [comment]
Now caching lyrics and comments with songs.
Updated in build 68

**Comment by RPNate1** [comment]
fixed b71
