### ISSUE TITLE
[BUG] Low and medium rate caches don't play back

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#133]
## Brief description of the issue:
Low and medium rate caches don't play back

### Steps to reproduce: 
1. Go to cache manager
2. Click "+"
3. Choose 20 songs, Main mix (not sure this matters).
4. Click download
5. wait for the download to complete
6. Click the cached songs
7. See error in song control bar

### Expected result: 
Songs should play

### Actual result: 
No playback, error "Song in cache is damaged"

### Where did you see it? (App build version, device type and iOS version): 
Mk2 Version 0.9 Build 61 

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 9 59 09 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/b1b40d8e-0d34-45e7-9214-b0d96b068870)

**Comment by bradtchapman** [comment]
@RPNate1: Confirmed & Reproduced with Low and Medium bitrates on multiple streams.

**Comment by RPNate1** [comment]
@jarro has been notified.

**Comment by donshefer** [comment]
This has been fixed.

**Comment by RPNate1** [comment]
confirmed fixed b71
