### ISSUE TITLE
[BUG] Download status message (EN) is incorrect

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#134]
### Where did you see it? (App build version, device type and iOS version): Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 9 59 50 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/c7fc81b9-a847-4ce0-8c3e-71f5398cd2e1)

**Comment by bradtchapman** [comment]
@RPNate1 : you may need Github tabs to describe bug severity: suggestion, cosmetic, minor, moderate, major, crash, etc...

**Comment by donshefer** [comment]
fixed in build 62

**Comment by RPNate1** [comment]
@bradtchapman done

**Comment by RPNate1** [comment]
fixed b62
