### ISSUE TITLE
[BUG] Info Mode "Dark Theme" setting doesn't affect anything

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#135]
### Where did you see it? (App build version, device type and iOS version): Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
Switched on
![Screenshot 2023-05-18 at 10 11 15 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/8ec60bfc-f630-4b41-a2be-6ae991e11ba2)
Switched off
![Screenshot 2023-05-18 at 10 11 18 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/0aeb229c-586a-4577-9cc8-1cb17ed7e04e)

**Comment by k00ka** [comment]
I take this back - it affects some things. Perhaps I expect it to affect more. It seems to affect only some smaller panes in the app.

**Comment by bradtchapman** [comment]
The entire app is dark themed. 

The setting you're looking at only affects "Info Mode," which is the app view that shows the lyrics, wikipedia entry, comments, etc.
