### ISSUE TITLE
[BUG] App UI hangs (playback continues) when using arrow keys to move in comment

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#136]
### Where did you see it? (App build version, device type and iOS version): Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 10 17 09 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/f8262754-ef97-4cc1-8b68-6e228b25cc1e)

**Comment by bradtchapman** [comment]
@RPNate1 : you need GitHub labels for **iPhone** , **iPad**, and and **Mac**.

**Comment by k00ka** [comment]
@bradtchapman All findings from me so far are Mac. I have a 9th gen iPad I could retest these findings on and flag them. Let me know - and let me know plans for tagging.

**Comment by RPNate1** [comment]
added new labels

**Comment by RPNate1** [comment]
I can't replicate this one

**Comment by k00ka** [comment]
I can create a video.
I can also try recreating on iOS.
Let me know.

**Comment by bradtchapman** [comment]
@RPNate1 @donshefer : 

I was able to reproduce this on the first attempt.  

Steps to reproduce: 

1. Open the Mac app and resize it to the "tall" view.
2. Start playing a song.
3. Switch to Info Mode.
4. Scroll down to the comments.
5. Start a new comment.
6. Press the up or down arrows.
7. Beachball appears, but music keeps playing.  

First time I reproduced this, there was no audio glitch.  Second time, there was.

**Comment by bradtchapman** [comment]
FYI, pressing ANY KEY in this view also causes the player bar to disappear.   This behavior may or may not be related to #138 .

**Comment by bradtchapman** [comment]
I cannot reproduce this behavior 100% of the time, but I think if I'm fast enough on the keys, I can trigger it.  Press the arrow keys before the CSS template can react and resize / rearrange the box.

**Comment by donshefer** [comment]
This has been changed in many different ways since this ticket was opened. 
I tested and it appears to be working as expected in build 80.

**Comment by RPNate1** [comment]
UI didn't hang for me in b80
