### ISSUE TITLE
[BUG] Info Mode intermittently loading in webview - WAS- Video on home page doesn't play

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#137]
## Brief description of the issue:
 Going to the home page and clicking the video lands on a wierd split page with some song data on right and nothing on the left. The video doesn't play.

### Steps to reproduce: 
1. From the hamburger menu, click home.
2. Click on the video play button 
3. See a strange screen.

### Expected result: 
The music playback should stop and the video should play. 

### Actual result: 
A page with a strange layout is shown

### Where did you see it? (App build version, device type and iOS version): 
Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 10 26 34 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/ed1329bc-2c80-489b-8985-76377be11bd6)
![Screenshot 2023-05-18 at 10 26 40 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/78bb37aa-6b62-4666-a936-8f63fe962ec6)

**Comment by bradtchapman** [comment]
@k00ka : known issue / limitation of the in-app browser.

**Comment by RPNate1** [comment]
A couple things... The play button is supposed to start the player when visiting the website in a browser. That's something that hadn't been pointed out about this element which has lived on the homepage for about 9 months. So thanks!

The page is the Info Mode of the player (history on the left, with the current song data/ratings/lyrics/artist/comments on the right), but for some reason the columns don't load fully. I had to stop and start playback to get them to fully load. @donshefer @jarro

**Comment by bradtchapman** [comment]
> A couple things... The play button is supposed to start the player when visiting the website in a browser. That's something that hadn't been pointed out about this element which has lived on the homepage for about 9 months. 

That's funny; I just assumed it was broken / not working due to the changes made to restrict the in-app browser.  😄

**Comment by RPNate1** [comment]
the one bug in this appears to be fixed in b71
