### ISSUE TITLE
[BUG] Download Manager top margin missing

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#139]
### Where did you see it? (App build version, device type and iOS version): Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 10 56 09 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/950b6492-0958-475c-a2be-e43be7cd741b)
![Screenshot 2023-05-18 at 10 58 35 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/2d2e56a1-a809-4fcc-93b2-eaeeda4cada7)

**Comment by bradtchapman** [comment]
This is also occurring on iPhone and iPad.

**Comment by donshefer** [comment]
fixed in build 62

**Comment by bradtchapman** [comment]
@RPNate1 @donshefer : Confirmed; looks better in b62.

**Comment by RPNate1** [comment]
Fixed in b62
