### ISSUE TITLE
Suggestion: Don't show the "Back" button if the user is already at the home page (or can't go back any further)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#14]
The "Back" button doesn't seem to do much of anything right now except load the home page.  Is there a navigational trail?  I couldn't get more than one link deep to test it.

**Comment by RPNate1** [comment]
yep

**Comment by donshefer** [comment]
I updated the back button to hide and show as appropriate.
The fix is targeting build 27.
