### ISSUE TITLE
[BUG] Song list doesn't update

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#140]
### Where did you see it? (App build version, device type and iOS version): Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 11 08 04 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/e9c6d26a-c5ea-4a83-9ee3-daa701ee30a3)

**Comment by bradtchapman** [comment]
@RPNate1 @donshefer : the song list (history view) is an online-only feature, right?  Shouldn't this be blocked when a user is playing a cached block?

@k00ka : The view you're looking at is intended to update when listening online.  The player sends a message to RP saying "here is what song this device just listened to," and it appears in that list.

**Comment by bradtchapman** [comment]
@RPNate1 : if this is now tagged as a feature request, is it a [bug] anymore?  :)

**Comment by RPNate1** [comment]
leaving it here for now. It'll be fixed shortly, I'm sure. The feature request label is for me to remind me that I had asked for the feature that was expected.

**Comment by RPNate1** [comment]
Created a ticket for the new feature for offline, as well as limiting functions to offline uses only will make this not available. As this was working ,mostly as expected, I'm closing.
