### ISSUE TITLE
[BUG] List mode web view has player bar displayed above native play bar

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#142]
## Brief description of the issue:

web view is showing the online play bar within the frame

### Steps to reproduce:

navigate to list mode and the webview shows an additional playbar

### Expected result:

List mode would not display an additional playback interface

### Actual result:

doubled up controls

### Where did you see it? (App build version, device type and iOS version): 

Macbook pro 2021 desktop app b61

*(Please provide screenshots or error message text when possible.)*

can't take a screen shot the control button bug makes it impossible

**Comment by bradtchapman** [comment]
@RPNate1 : to take a screenshot of the app, click outside the app (i.e.; on a Finder window or the desktop), then start the screenshot process.  
You can press Shift-Cmd-3 to screenshot the whole screen, then crop in Preview.  
Or you can press Shift-Cmd-4 to drag-select an area of the screen.  
In this alternate mode, you can also press the Space bar to change to "window / element selection" where the cursor is a camera, and it highlights the window or UI element under the cursor.  Click to capture.

**Comment by bradtchapman** [comment]
@RPNate1 : I can't reproduce this issue with build 62 as described.  Tried it in both the wide (square) aspect, and tall aspect, of the Mac app.  (FYI : the wide view appears to provide 3-column layout in Info view, but the tall aspect will result in a 2 column view like the iPad).

Can you press Shift-Cmd-5 and take a screen recording of a portion of the screen while using the app?

**Comment by bradtchapman** [comment]
@RPNate1 : here's what you see when pressing Shift-Cmd-5.  Click the 'record selection portion' button and then use the controls on the toolbar to start a recording.  When done, press Shift-Cmd-5 and press "Stop."

<img width="633" alt="Screenshot 2023-05-20 at 12 22 52 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/56910bf6-efdf-430b-ae3a-9bc03eb9c7a7">

<img width="576" alt="Screenshot 2023-05-20 at 12 24 18 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/254de64c-b42b-4212-a00e-e407373a13dc">

**Comment by RPNate1** [comment]
It seems to be an issue with recognizing our webviews in the app where
there shouldn't be a play bar vs. a mobile browser view where the play bar
is needed

**Comment by RPNate1** [comment]
@jarro this your side?

**Comment by JoschiW64** [comment]
Hi, also can confirm this behavior. I had it once, too, yesterday, didn’t know exactly how I get there, but might have been as described above. Happened on my iPad.

**Comment by JoschiW64** [comment]
Maybe this screen is helpful? 

Looks very strange and confusing. Just seen on my iPhone 12 Pro Max iOS16.5.
![IMG_0387](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/4c842dca-f264-4585-afef-20f451cf8f81)

**Comment by RPNate1** [comment]
@donshefer @jarro it appears the web view is frequently displaying the web player above the app's play bar. How can we stop it?

**Comment by jarro** [comment]
There was an issue,  I'm not sure if it ever got fixed  might be the same one.   
iOS can wipe the webview from memory and then reload the last  active url.   Which will load it without  the  required userstate.

This would be more likely to happen when switching between apps.

**Comment by bradtchapman** [comment]
I've seen this happen after long pauses of not using RP.

**Comment by RPNate1** [comment]
@donshefer can we override the wiping of the webview from memory to see if this fixes this issue?

**Comment by bradtchapman** [comment]
I wouldn't try to hold that in memory.  iOS will aggressively scavenge RAM if it can.  App design and programming guidelines tell you to expect to have your app closed or put to sleep at any time.

**Comment by jarro** [comment]
I found an old email thread on this from feb.
My hope was to  detect this in the app.   And append the  required  parameters to the url before the page reloads incorrectly.


============

Looks like there is a way to detect  navigationtype = 'reload'
https://stackoverflow.com/a/50966407
Not sure if it will be categorized as reload,  but should be some way to detect that it's loading an url,  with no page currently loaded.  If an expected function is undefined etc.

**Comment by RPNate1** [comment]
Let's see if we can get this fixed. I've seen it less often, but usually, it's after leaving the app going in the background and coming back to it.

**Comment by donshefer** [comment]
@RPNate1 As far as I can tell, the app is always adding the correct parameters. This is happening infrequently and I am having a hard time pinning it down.
I have made a slight change based on Jared's suggestion about the ".reload" navigation type.
Let's keep on eye out of it and see if we can still see it.
Updated in build 74.

**Comment by RPNate1** [comment]
I haven't seen this today in b74. I'll close. Generate a new report if this happens more.
