### ISSUE TITLE
[BUG] Completed cache downloads are visible

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#143]
### Where did you see it? (App build version, device type and iOS version): Mk2 Version 0.9 Build 62

*(Please provide screenshot
Last time I looked, this said "0 songs in cache" - it now popped up to 5 (??because that was the original chunk size??)
<img width="590" alt="Screenshot 2023-05-19 at 2 35 41 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/d356b0d5-f1cc-4024-991a-2538d0fc4837">
s or error message text when possible.)*
Clicking the cache piece shows this
<img width="160" alt="Screenshot 2023-05-19 at 2 35 47 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/e69826fb-8e45-4ec4-99db-ddca6c9a9402">

**Comment by k00ka** [comment]
One thing I was able to reproduce is: revisiting the download manager when a cache block has 0 songs to play causes the cache block to reload - kinda cool, unless the user is on cell data and didn't intend it.

**Comment by RPNate1** [comment]
I just got the auto-refill bug with a high bitrate cache. Not designed to do that. Though auto-refill will be a feature shortly.

@donshefer two different things going on here with the cache not disappearing and auto-refilling by itself after tapping. 
tapping it a few times crashed the app for me.

**Comment by bradtchapman** [comment]
@RPNate1 : I can confirm that it appears to be auto-refilling the exhausted caches, which is unexpected behavior.

**Comment by RPNate1** [comment]
DL manager is being fixed.  Functions and instructions. See email sent out to testers.

**Comment by donshefer** [comment]
should be fixed in build 66
