### ISSUE TITLE
[FR] Download directive text improvement

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#144]
## Brief description of the issue: 
When first looking at the download manager, it may not be clear what to do.

### Steps to reproduce: 
1. Open the download manager 
2. See "DOWNLOADS: none"

### Expected result: 
What if, instead you saw text "Click on the + to download music for offline playback". This is similar to the directive text provided once there is a cache object in place "Press to play, swipe left to remove" - it parallels it nicely.

### Actual result: 
I see "None" which is not helpful.

### Where did you see it? (App build version, device type and iOS version): 
Mk2 Version 0.9 Build 62

*(Please provide screenshots or error message text when possible.)*

<img width="754" alt="Screenshot 2023-05-19 at 2 46 22 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/c12368af-8d5a-43bc-aa37-c6dc24e89169">

<img width="754" alt="Screenshot 2023-05-19 at 2 46 14 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/0c9362cf-10d3-4fb4-a1ed-d8ef8c11301d">

**Comment by RPNate1** [comment]
This is a good suggestion. The download manger is currently a work in progress.

**Comment by donshefer** [comment]
updated in build 63
