### ISSUE TITLE
[BUG] App won't start at all in airplane mode b62

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#145]
## Brief description of the issue:

app only loads logo screen when in airplane mode

### Steps to reproduce:

turn on airplane mode and try to start app

### Expected result:

app opens in Simple Mode with cache ready to play/playing. If no cache is available, there should be a warning that a network connection is needed for streaming or downloading a cache of songs. Offer to connect to an available network. after connecting prompt to stream or open download manager. If no network is available, get warning there isn't one.

### Actual result:

logo loads, no app functions at all

### Where did you see it? (App build version, device type and iOS version):

b62 iPhone 11 pro 16.4.1
iPad Air 5th gen 16.4.1

*(Please provide screenshots or error message text when possible.)*

**Comment by bradtchapman** [comment]
Confirmed and reproduced on build 62 on the Mac as well.  In Airplane mode when not connected to the Wi-Fi, the app hangs at the logo.

If there is no block available, there needs to be a fallback screen with the RP logo but no song loaded.  Warn the user that an internet connection is required.

**Comment by bradtchapman** [comment]
Edit: the app doesn't launch even if there is a cacheable block available to play.

@donshefer : this persists in build 63.

To reproduce this, you must kill the app, engage Airplane mode AND disable WiFi, then try to launch.  The app will hang.

**Comment by RPNate1** [comment]
Confirmed. Will design to allow entry into app and prompt reconnection to download content or stream.

**Comment by JohnADilley** [comment]
Confirmed this persists in b66 as well.

**Comment by donshefer** [comment]
Fixed in build 69

**Comment by RPNate1** [comment]
fixed and confirmed in b71
