### ISSUE TITLE
[BUG] App crash when viewing channels (not reproducible)

### ISSUE THREAD

**Issue by jadRafay** [BillGoldsmith/iOS-bugfest#146]
## Brief description of the issue:

App crash.

### Steps to reproduce:

Playing from cache while in wifi.
Selected channels from upper menu/listen section.
Switched channels to see what’s playing now.
Clicked a song to jump to that channel. 

### Expected result:

What normally happens in this app: the song from the other channel is shown,
the app keeps playing the song from cache.

### Actual result:

App exited. 
I tried the same thing again but it didn't recur.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by RPNate1** [comment]
hmmm. can't replicate.

**Comment by bradtchapman** [comment]
Seconded.  Cannot replicate.
