### ISSUE TITLE
[FR] Download Manager auto-refill is missing

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#148]
## Brief description of the issue:

Download Manager auto-refill is missing

### Steps to reproduce:

Open Download Manager.  Select a cache block to load.

### Expected result:

A toggle allows me to say "auto-refill the cache block".
When the block gets below a threshold it is topped up automatically.

### Actual result:

There is no selector.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by bradtchapman** [comment]
@jadRafay : you are referring to the behavior from the original Radio Paradise app (v1).  

For RP v2, this constitutes a **feature request**, since it hasn't been implemented yet.

**Comment by JohnADilley** [comment]
OK, thanks for the update. Will use FR for future feature requests...

**Comment by donshefer** [comment]
implemented in build 66

**Comment by JohnADilley** [comment]
Can mark this as FIXED and VERIFIED (although note FR #191 -- auto-refill waits too late IMHO).

**Comment by JohnADilley** [comment]
(Closing issue; didn't noticed I could close it before.)
