### ISSUE TITLE
[BUG] b62: Download Manager can only load one block at a time

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#149]
## Brief description of the issue:

The DM shows "+" in top right corner but can't start a new cache block until
the current download is complete.

### Steps to reproduce:
Enter DM; start a download; click "+".

### Expected result:

DM starts a second download running with feedback showing progress on both.

### Actual result:

Nothing happens on repeated click of "+".

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by bradtchapman** [comment]
This is a regression of behavior from RPv1.  In the original app, you can queue up multiple offline blocks and they download in sequence until they're all done.

**Comment by JohnADilley** [comment]
On a positive note: download progress bar is now correct. :-)

**Comment by donshefer** [comment]
The add download button was disabled, but not greyed out while a download is in progress. 
Only supporting a single download at this time.
Updated in build 63

**Comment by bradtchapman** [comment]
Confirmed fixed.  Thanks @donshefer !
