### ISSUE TITLE
Suggestion: expand the size of the tap zone for the metadata bar

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#15]
The "metadata" bar is the graphical element at the bottom that contains, in this order: album art, title/artist, empty space, heart.

Currently, the only thing that is tappable in this area is a box around the album art and the artist/title.  The dead zone between these and the heart does nothing at all.  This entire area (minus the heart of course) should be tappable and load the song info.

**Comment by RPNate1** [comment]
yep, I agree.

**Comment by donshefer** [comment]
Fixed targeting build 29

**Comment by RPNate1** [comment]
Works
