### ISSUE TITLE
[BUG] b62: Select the same cache block you're listening to, get a new song

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#151]
## Brief description of the issue:

The new app fast-forwards upon change of channel, losing the rest of the
current song.  Also the ability to play the song from the start.

### Steps to reproduce:

Play a song from a cache block.
Open the bottom left dialog to select a channel.
Choose the cache block you're listening to... boom.

### Expected result:

There should be no interruption in the playback.

### Actual result:

The song that was playing is lost; you get the next song in the block.
This also happens when changing cache blocks, or going from cache to live.

I really like the fact that I can exit the current app and when I restart it
starts the song I was listening to fresh from the beginning.  I acutally use
that feature quite a lot with favorite songs!  Exit app at the end of the
song (or switch channels), and I get a goody back when I restart.  Can you
please bring back that behaviour?

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by bradtchapman** [comment]
Confirmed.  I observed this multiple times while testing offline playback.  Switching back to the offline cache should resume exactly where the listener left off.

**Comment by bradtchapman** [comment]
Video demonstration:


https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/1b69ba8c-6191-4a76-a554-515249fbcda5

**Comment by bradtchapman** [comment]
Video demonstration:

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/5586c6fb-7ed3-4f9d-ad4e-57d4fb3ed584

**Comment by donshefer** [comment]
function updated in build 63

**Comment by RPNate1** [comment]
Confirmed. Discussed with Don. Song will only leave cache once its played all the way through. Actively fixing.

**Comment by donshefer** [comment]
fixed in build 66

**Comment by JohnADilley** [comment]
No interruption now.
