### ISSUE TITLE
[BUG] b62: Can't view the playlist with Download Manager

### ISSUE THREAD

**Issue by jadRafay** [BillGoldsmith/iOS-bugfest#153]
## Brief description of the issue:

Can't view the playlist with Download Manager

### Steps to reproduce:

Get to the song image, TAC, lyrics, and author info page.
How how to get back to the list of songs that have played?
This appears to be possible playing live; it would be nice from cache, too.

### Expected result:

I like the new TAC (Title, Author, Copyright)/lyrics/info page -- but
navigation is clumsy.

### Actual result:

There is no three-line option to get to the playlist when from cache.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by bradtchapman** [comment]
Duped by newer issue #154 .
