### ISSUE TITLE
[Bug] Odd display behavior when app is in vertical display

### ISSUE THREAD

**Issue by scryer999** [BillGoldsmith/iOS-bugfest#155]
## Brief description of the issue:
Playing with window sizing on MacOS.  App constrained in display sizing to only two modes - vertical/portrait and horizontal/landscape.  (This may be by design)

In vertical mode, when reading the blog, strange display artifacts appear.  

### Steps to reproduce:
1. open RP app
2. resize to vertical
3. select Blog from ULH menu
4. artifacts appear
5. artifacts (sometimes) persist when resizing to horizontal, blotting out the RP controls

### Expected result:
able to read the blog cleanly

### Actual result:
blog obscured, sometimes resulting in loss of control and need to reset the app

### Where did you see it? (App build version, device type and iOS version):
Build 62, Mac Pro M1 Max, Ventura 13.3.1 (a)

*(Where possible, please attach Please provide screenshots or error message text)*
<img width="639" alt="Screenshot 2023-05-20 at 9 40 25 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/134152552/7fa29b12-e17b-4260-95af-2c8fd6a49d01">

**Comment by bradtchapman** [comment]
@scryer999 : is this repeatable?  Try quitting and relaunching the app and do it again.  Same or different result?  Are you using the keyboard at all in the app?

**Comment by scryer999** [comment]
steps to repeat:

open RP on Mac, cold app start
select Blog from ULH hamburger menu with mouse
resize RP window to vertical

<img width="754" alt="Screenshot 2023-05-21 at 8 41 48 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/134152552/a01dca9b-0946-4ce3-847c-78947a31eb6e">

**Comment by RPNate1** [comment]
@jarro what's this?

**Comment by bradtchapman** [comment]
The main website currently allows keyboard interaction: up / down for scrolling, and right arrow to skip songs.  This is probably unexpected in the SwiftUI contexts because they were designed for touch-input devices (iPhone, iPad)

Maybe the Javascript that listens to keyboard input is causing areas to disappear?

**Comment by RPNate1** [comment]
Don will be working on getting the keyboard functions to play nicely! In
the pipeline!

**Comment by RPNate1** [comment]
discussed with Don. Looking into what's causing it.

**Comment by RPNate1** [comment]
Still seeing this intermittently.

**Comment by donshefer** [comment]
should be fixed in build 74

**Comment by RPNate1** [comment]
fixed in b74
