### ISSUE TITLE
[Bug] avatar button should open AND close profile page

### ISSUE THREAD

**Issue by BillGoldsmith** [BillGoldsmith/iOS-bugfest#156]
## Brief description of the issue:
clicking the avatar button opens the profile. but then theres no intuitive way to close it again. 

### Steps to reproduce:
click the avatar button to open the profile.

clicking it again does nothing. not sure how to get back to the info display.

### Expected result:
clicking avatar button with profile showing should close profile and reveal whatever screen I was on before opening it.

### Actual result:
clicking avatar button does nothing

### Where did you see it? (App build version, device type and iOS version):
b62, iPhone 12, iOS 16.4.1

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by BillGoldsmith** [comment]
Reported by Jon (while inadvertently logged in as bill)

**Comment by bradtchapman** [comment]
A wild @BillGoldsmith has appeared!

The current intention is to tap something else, but you're right - there is no intuitive way back.

**Comment by RPNate1** [comment]
Redesigning a menu under profile icon for a slimmed-down main interface and
getting to the profile to match the mobile version of the site.

**Comment by mtnbrit** [comment]
I love the new single avatar button up there with profile, settings and logout under it, but when you have the profile open, clicking the avatar button again should close the profile and go back to the view you were on before you opened it. In b64 it just reopens the avatar-button-tapped menu. The settings modal has a X to get out, but profile doesnt. 

by the way we need to remove Log Out from the top-left hamburger now.
