### ISSUE TITLE
[Bug] Song info view(s) do not respond to mouse wheel scrolling — intermittent, random

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#158]
## Brief description of the issue:
There are two different "info views" available for song info, depending on how you reach them:

Path 1: Playlist View (three lines) > click current song.  
* Two column view
  * Left side: Album art, metadata, and lyrics
  * Right side: Artist wiki entry and comments

Path 2: Simple Mode > double-click album art.
* Two column view
  * Left side: Play History
  * Right side: All song info (art, metadata, wiki, lyrics, comments).

In both of these views, sometimes the contents do not scroll when using the mouse wheel.  They *do* however respond to two-finger trackpad gestures to scroll, but there is a slight delay (~0.25 seconds) before they respond.

Mouse wheel scrolling should be available globally across the app when the mouse is over **scrollable content**, and does not require clicking first to set focus.  Mac apps behind the current window also respond to mouse scrolling events by design.

### Steps to reproduce:
1. Obtain a Mac laptop and attach a desktop mouse with a scroll wheel — not a Mighty Mouse, Magic Mouse, or Magic Trackpad.
2. Launch the RP app and start playing music.
3. Switch to song info by either Path 1 or Path 2 as described above.
5. Ensure the mouse is over a scrollable area and try to scroll window content.
6. Switch back to Simple Mode or a different view.
7. Repeat steps 3-5 with mouse first, then with the internal Mac trackpad over the same areas.

This is not 100% reproducible but happens often enough that you should be able to trigger it at least 50% of the time.

### Expected result:
Content in the window should always respond to mouse scroll wheel events.

### Actual result:
Sometimes, content does not scroll.

### Where did you see it? (App build version, device type and iOS version):
Build 62, macOS 13.3.1, MBP 2021

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Don will be dialing in the Mac version for keyboards, trackpads, etc.

**Comment by donshefer** [comment]
I managed to dig up an old optical mouse and test this. Everything worked as expected.
Given that two finger scrolling works perfectly, and mouse scroll wheel works most of the time, but only guess is that it might be an issue with your specific mouse or drivers.
@RPNate1 Can we see if this is a prevalent issue that others are seeing?

**Comment by donshefer** [comment]
@RPNate1 Tested this again and seems to be working with mouse scroll and scroll gesture.

**Comment by RPNate1** [comment]
I don't have an optical mouse...someone else will have to validate this. @bradtchapman

**Comment by RPNate1** [comment]
@bradtchapman please validate this one. I don't have an old-fashioned mouse.

**Comment by bradtchapman** [comment]
@RPNate1 : I tested this with an old wireless scroll mouse and it seems to be working properly.
