### ISSUE TITLE
[Bug] In Offline cache mode, RP station IDs and bumpers consume more than 1 song count.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#159]
## Brief description of the issue:
In offline mode, if there is an RP bumper ("You're listening to..."), the song count is decreased by 3 songs, sometimes 2.

Problem occurs on any device : iPhone, iPad, Mac.

### Steps to reproduce:
1. Open the app.
2. Access the download manager.
3. Create a block of music and start playing.
4. Click the station list selector to see the songs remaining (should be n or n-1, i.e.: 20 or 19).
5. Skip a song and repeat step 4.
6. If you encounter a station bumper, check the song count again.

### Expected result:
The station bumpers should consume ZERO songs.

### Actual result:
The station bumpers consume 2-3 songs.

### Where did you see it? (App build version, device type and iOS version):
Build 62, MacOS 13.3.1 and iOS 16.4.1.

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
This should no longer be an issues because we are displaying the amount of time in the cache instead of the number of songs.
