### ISSUE TITLE
[Bug] CarPlay UI only switches between other cached stations, does not load a live station on demand

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#160]
## Brief description of the issue:
I cached a block of music from RP Main and then wanted to switch to RP Mellow live, but the app said "stopped" and played nothing.

If I am on a long drive, I want to be able to switch between live stations and cached blocks.  

### Steps to reproduce:
1. Go to download manager and load a block of music. 
2. Connect phone to CarPlay.
3. Play current block.
4. In the CarPlay UI, switch to another station that doesn't have a block cached. 
5. App stops playing music.
6. In CarPlay UI, switch back to station that has a block cached. 
7. Music resumes. 

### Expected result:
I expected the CarPlay app to show me a list of stations that included the cached block.  Instead, the list is limited to the four main stations plus My Favorites.  Furthermore, I expect switching to an uncached station will load that one live.

### Actual result:
RP simply stopped.  

### Where did you see it? (App build version, device type and iOS version):
Build 62, iOS 16.4.1, iPhone 12 Pro.

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
I was able to validate the conditions around this bug by caching a block of music from the Mellow station, then switching back-and-forth between Main and Mellow. 

The Mellow off-line block played just fine after having been prepared. But then I switched to Global, and the music stopped again.

**Comment by RPNate1** [comment]
Carplay somehow got screwed up in a build recently. Actively fixing it.

**Comment by donshefer** [comment]
fixed in build 69
