### ISSUE TITLE
[Bug] Offline playback is blocked if "stream on WiFi only" is enabled and user disables WiFi

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#161]
## Brief description of the issue:
Users will be unable to play offline blocks of music if Wifi is disabled while the "stream on wifi only" option is enabled. 

### Steps to reproduce:
1. Connect to Wifi.
2. Cache music in the download manager.
3. Start playback of offline block.
4. Change setting to "stream on wifi only" to ON.
5. Disable Wifi.
6. Error message appears. 

### Expected result:
Offline music should play no matter the current connection.

### Actual result:
Music stopped and refused to play.

### Workaround
Set phone to airplane mode and music may resume playing. 

### Where did you see it? (App build version, device type and iOS version):
Build 62, iPhone 12 Pro, iOS 16.4.1

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_4420](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/0495382c-6005-458c-896e-66048f4983ea)

**Comment by donshefer** [comment]
updated in build 68
