### ISSUE TITLE
[Bug] Buttons without any text on iPad 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#163]
## Brief description of the issue:
See screenshot

### Steps to reproduce:
1. Just open the app

### Expected result:
Normal Buttons with text

### Actual
![IMG_0083](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/868239a7-7abe-4657-9a61-d2c26b23198c)
![IMG_0084](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/34a6863d-e011-4eae-a394-c4e0a802db01)
 result
See Screenshot

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (62), iPad mini 5, iOS iPadOS 16.4.1 (20E252)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
Lieber @ChristianNoc,

Bitte überprüfen Sie die folgende auf Ihren iPad:

Einstellungen > Anzeige & Helligkeit > **Tastenformen**.  
Es scheint hier in Ihrem Screenshot EIN zu sein.  Können Sie das bitte kürzlich AUS machen?

Einstellungen > Anzeige & Helligkeit > **Textgröße**.  
Wo liegt der Schieberegler?  In der Mitte, oder irgendwo auf der rechten Seite?

Danke im Voraus.

**Comment by bradtchapman** [comment]
Lieber @ChristianNoc,

Bitte überprüfen Sie die folgende auf Ihren iPad:

Einstellungen > **Bedienungshilfen** > Anzeige & Helligkeit > **Tastenformen**.  
Es scheint hier in Ihrem Screenshot EIN zu sein.  Können Sie das bitte kürzlich AUS machen?

Einstellungen > **Bedienungshilfen** > Anzeige & Helligkeit > **Textgröße**.  
Wo liegt der Schieberegler?  In der Mitte, oder irgendwo auf der rechten Seite?

Danke im Voraus.

———

Dear ChristianNoc,

Please review the following settings on your iPad:

Settings > Accessibility > Display & Brightness > Button Shapes
It looks like this is ON in your screenshot.  Can you please turn it OFF briefly?

Settings > Accessibility > Display & Brightness > Text Size
Where is the slider?  In the middle, or somewhere on the right side?

Thanks in advance.

**Comment by ChristianNoc** [comment]
Hi @bradtchapman ,

Settings > Accessibility > Display & Brightness > Button Shapes
It looks like this is ON in your screenshot. Can you please turn it OFF briefly?
When off it looks ok.

Slider for text Size:

![IMG_0102](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a27da1d4-a37d-4b36-bbff-e3f530bfd11a)

In portrait mode (also Hochformat) it is ok with button shapes off:

![IMG_0103](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/83cca345-e522-4058-a31d-ff16b159a7bc)

In landscape (also Querformat) it’s not ok. 

![IMG_0104](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/fcbc643c-34b7-4bf0-addc-9f158463a4de)

Shall I open a new case or is this still the same?

**Comment by RPNate1** [comment]
The off-center alignment is known and is being fixed.
