### ISSUE TITLE
[Bug] Rating of already rated Songs are not displayed in song overview, only in play list view: iPad and iPhone 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#164]
## Brief description of the issue:
See screenshots

### Steps to reproduce:
1. Just play and you will never see an available rating in song overview, in playlist it shows the rating correctly…

### Expected result:
See screenhots

### Actual result:
See screenshots

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (62), iPad mini 5, iOS iPadOS 16.4.1 (20E252)

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0086](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/80e3b749-862b-45aa-8ae8-0edf1a9917fc)
![IMG_0087](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6ee97bd3-4d6e-4794-91d6-2b13e60f5171)

![IMG_0085](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/2fa8dee6-4579-4d2a-bd73-994f5a38d113)

**Comment by bradtchapman** [comment]
Lieber Christian,

Thanks for the bug report.  We think you mean to say that a song, upon which you have **previously** cast a vote, is not showing your vote in the player but only in the playlist / history view.

@RPNate1 @donshefer : this is a report from a user that looks exactly like my previous bug reports of #117 and #120 .

**Comment by ChristianNoc** [comment]
Yes exactly!

**Comment by donshefer** [comment]
Hmm. It is very curious. I have still not been able to replicate this issue in my account. 

Question: When you listen to the "My Favorites" channel, do you see the same issue, since those should all be rated?

![Screenshot 2023-06-02 at 2 42 39 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/1120075/29aa13b7-9c12-467e-ac19-e88023ccabed)
![Screenshot 2023-06-02 at 2 42 56 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/1120075/aedab0ab-ea33-47d7-8de2-07da86c1fcdb)

**Comment by ChristianNoc** [comment]
@donshefer i will try, I realised that the only ratings that are visible at the main screen are the 10 ratings. I will try my favourites an will come back…

**Comment by ChristianNoc** [comment]
Ok back again… for my favorite channel I can see the ratings…

![IMG_0154](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/f64c68a2-9e87-432d-b428-9056d0778339)
![IMG_0155](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a4fb985e-4b08-4b50-874b-846186b573b9)

Have you changed something at the back end because it looks like that it works now maybe with a little time lag. 

![IMG_0156](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/0d519b3c-faef-4dd5-83c8-449ae924461d)

I looks good now but I will test it during the weekend,,,

May I ask you what Programm you use for the iOS emulation. Is it a Windows Programm?

**Comment by ChristianNoc** [comment]
@donshefer @RPNate1 
It’s looks now that this issue is solved…

**Comment by donshefer** [comment]
@ChristianNoc I am testing using Apple's Xcode environment, which includes simulators for most of the available devices and iOS versions. Lucky for me, it would be tough for me to own every Apply device. =)

**Comment by ChristianNoc** [comment]
Issue is solved so I close it. Thanks for fixing.
