### ISSUE TITLE
[Bug] UI on small screen iPhones: The two buttons in the very bottom are almost out of the screen… 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#166]
## Brief description of the issue:
See screenshot: The two buttons in the very bottom are almost out of the screen… 

### Where did you see it? (App build version, device type and iOS version):
0.9 (62), Oldtimer iPhone 6s, iOS 15.7.5

![IMG_0513](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/5915807d-a606-48cf-b243-90c883cc8bbc)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
@ChristianNoc : bitte überprüfen Sie Ihre **Textgröße** Einstellungen.  Wo liegt der Schieberegler?  Probier' doch mal in der Mitte und bitte zurückmelden...

**Comment by ChristianNoc** [comment]
Hello @bradtchapman,

ok I have tried to change the text size but it doesn’t change that behaviour:

![IMG_0516](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/44cd7d42-4316-4120-9783-2e90f6e6f3be)
![IMG_0515](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/00f9b095-eb1e-415b-9ee2-01e5182647e6)

My normal setting (the first picture I sent you) was in the middle. It looks like that the app doesn’t support dynamic text size…

![IMG_0514](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6cdb386c-d751-4882-b8d8-2fe02d7b3f96)

**Comment by bradtchapman** [comment]
I just noticed you have an "old timer" iPhone 6s running iOS 15.x.  I also bug tested on iOS 15, but on an iPhone SE first gen (the tiny phone, my favorite!)

@donshefer : are you still running simulators on iOS 15 with devices that have a screen size of 1334x750?  This includes the iPhone 7, 8, SE2 and SE3.

**Comment by ChristianNoc** [comment]
> I just noticed you have an "old timer" iPhone 6s running iOS 15.x. I also bug tested on iOS 15, but on an iPhone SE first gen (the tiny phone, my favorite!)
> 
👍🏼 for the tiny phone, my favourite too!

**Comment by donshefer** [comment]
@bradtchapman Yep, I am still testing on smaller screens. The iPhone 6, 7, and 8 slipped through my custom formatting code to handle SE.
Fixed in build 71.

**Comment by RPNate1** [comment]
Tiny screen guys, check this out... @bradtchapman @ChristianNoc

**Comment by ChristianNoc** [comment]
@RPNate1  
I will as soon build 71 is on my device and will be back with the result…

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

Fixed I close that chapter

Build 0.9 (71), Oldtimer iPhone 6s, iOS 15.7.5 

![IMG_0583](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/d65cbeca-1a18-4d81-bc11-1b4628795834)
