### ISSUE TITLE
[Bug] UI: ipad: Button for Playlist View: no toggle function available

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#167]
## Brief description of the issue:

[Bug] UI: Button for Playlist View: no toggle function available: Ju can just turn the playlist view on. I think this is not how it should be. In my opinion t he button should toggle playlist view on/off.

### Where did you see it? (App build version, device type and iOS 
Build 0.9 (62), iPad mini 5, iOS iPadOS 16.4.1 (20E252)

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0089](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/1d41d75b-3f3a-46e9-aece-8f369e2ae433)

**Comment by bradtchapman** [comment]
@ChristianNoc : Danke für den Vorschlag.  Thank you for the suggestion.  

@RPNate1 : what should the default screen be if someone taps the playlist view button again?  Can the app track their previous state, or should it default to Simple mode?

**Comment by RPNate1** [comment]
Simple Mode. great suggestion. Toggle it is.

**Comment by RPNate1** [comment]
Added to trello

**Comment by bradtchapman** [comment]
@RPNate1 : tagged as **Planned**.  This would be a way of identifying valid Feature Requests that make it to the Trello board instead of being closed as 'won't fix' etc.

**Comment by RPNate1** [comment]
I'll get on that after I get out from under some emails!
