### ISSUE TITLE
[UI-Improvment] Replace order of rows on iPad in mixed Titel and playlist view: Left Playing Songtitel - Right Playlist 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#169]
## Brief description of the issue:
In my opinion on the left row should be the item in focus and that is definitely the song. So I would change the rows: on the left the detailed a song view, on the right the playlist. See screenshot.

![IMG_0092](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/496614b2-64e5-424c-9e5d-613bbabb8275)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (62), iPad mini 5, iOS iPadOS 16.4.1 (20E252) 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
Try something please:

1. Tap the 'Playlist' button (three lines).
2. Tap the current song.
3. Examine the view.

Would this be preferable?

**Comment by bradtchapman** [comment]
@ChristianNoc, try something please:

1. Tap the 'Playlist' button (three lines).
2. Tap the current song.
3. Examine the view.

Would this be preferable?

**Comment by ChristianNoc** [comment]
Ok I think that this mixed screen with detailed view and playlist appears only when the iOS setting “setting/ bedienerhilfen/tastenformen” is on. 

It may not have been your intention to use this view. But it is cool and appears by means of the gesture up. I like the gestures control more than to much buttons.

If this view with track information and playlist should stay then the track information should be on the left and the playlists on the right. And of course independent of the button shapes setting in the iOS settings app.

This view appears this way:

![IMG_0095](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/66aa2d86-d372-4366-a709-a042cd264565)

And now this cool view appears (maybe it’s an Easter egg, but I like that view)

![IMG_0097](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/82a8389b-9d0b-4458-87fd-e783b252f51c)

I hope that my explanations are understandable.

**Comment by RPNate1** [comment]
This is how the player columns appear on the website and will stay within the app. I understand the thought behind the switch and will bring it up in a meeting.
