### ISSUE TITLE
UI Suggestion: ensure status bar text is in "dark mode" or set it to white

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#17]
See attached screenshots.  

When my device is in light mode, the status bar text is black because it's not expecting an app to use a dark background, which makes it very hard to read.  

Workaround: set the device to dark mode, and the status bar text turns white.  

Desired behavior: RP should set the status bar color explicitly, or inform the system that the app uses a dark theme.  Not sure what's possible in UIKit.

Dark Mode:
![418D3217-2962-4611-9E7D-0AC5395F34B9](https://user-images.githubusercontent.com/32527656/215286915-e9ca97b7-db87-4ee2-88dc-28d9cad09bb6.jpeg)

Light Mode:
![A64320EB-ECD3-466C-AE40-B971174F4643](https://user-images.githubusercontent.com/32527656/215286916-c91ef759-19ac-415a-910a-58826e0ed324.jpeg)

**Comment by RPNate1** [comment]
@donshefer let's look into this. This wasn't anticipated.

**Comment by bradtchapman** [comment]
Do you alpha test on real devices or the Xcode simulators?

**Comment by donshefer** [comment]
@bradtchapman I test on both. I usually try to test on a large screen, small screen, and my iPhone 13.
But we support a lot of devices so I certainly can't cover them all.

I updated the status bar style to dark mode (meaning white text for all device modes.)
targeting build 27

**Comment by bradtchapman** [comment]
CONFIRMED FIXED.
