### ISSUE TITLE
[Bug] Song Info album art suddenly shrank to half size

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#170]
## Brief description of the issue:
Within the last 24 hours, the song info view shows album art at half size. 

### Steps to reproduce:
1. Play a song. 
2. Switch to info view.  

### Expected result:
Album art should be full width.

### Actual result:
Album art is half width of screen.

### Where did you see it? (App build version, device type and iOS version):
Build 62, iPhone 12 Pro, iOS 16.4.1.

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_4430](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/ce1e152b-5653-4423-b225-6015f97dd3e9)

@jarro @mtnbrit - this appears to be a change on the web view rendered for the app, not anything changed in the app code.

**Comment by RPNate1** [comment]
This is intentional, as William wanted the switch to Info mode from Simple
Mode to be more apparent. Making the album art smaller allows for more of
the Info mode to appear with less swiping. Should we center the album art?

**Comment by bradtchapman** [comment]
I don't think that would help with all the wasted space.

Part of the joy of listening to "albums" is looking at the artwork.  If the artwork is suddenly half-size in the alternate view, it's not as enjoyable.

**Comment by RPNate1** [comment]
This was a directive from on high. I'll touch base with him now that it is
as asked. See how he feels now...
