### ISSUE TITLE
App doesn’t remember the selected audio quality

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#171]
## Brief description of the issue:

In contrast to the official app, this version to be tested does not remember the selected streaming quality under certain circumstances.

### Steps to reproduce:

1. Tap on the cogwheel symbol

2. Under Audio Settings, select (for example) FLAC as the setting

3. "kill” (swipe away) the app

4. Go to the Audio Settings again

### Expected result:

After restarting the app, the audio setting still should be (in this example) FLAC as it is the behavior of the official version of the app

### Actual result: 
![IMG_0245](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/7034a7bd-a3c6-431d-aba6-e33743df0493)
![IMG_0246](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/7059f449-8523-4f0c-87a3-ceb0d55844c3)
After restarting the app, the audio setting always is “high” by default

### Where did you see it? (App build version, device type and iOS version):
Build Mk2 09 (63), iPhone 12 Pro Max, iOS 16.5

**Comment by RPNate1** [comment]
Yes, this should be persistent.

**Comment by donshefer** [comment]
fixed in build 66

**Comment by JoschiW64** [comment]
I was not able to reproduce this error again now.
Thank you!
