### ISSUE TITLE
[FR] iPad and iphone: UI: Add swipe up for closing slide show

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#174]
## Brief description of the issue:
Just another gestures control. This time for the slide show. In my opinion the closing x disturbs the image. But it can stay if really necessary ;-)…

![IMG_0113](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6bb50f94-9912-45b0-960c-5350ea8995c8)

### Where did you see it? (App build version, device type and iOS version):
Build 123, iPhone 13 Pro Max Ultra+, iOS 16.X.X

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
I'm gonna say swipe down. We'll leave the x, though.

**Comment by ChristianNoc** [comment]
Yeah I thought swipe up because ending apps is that gesture and so ending the slide show is for me a similar wish… but it really doesn’t matter if up or down as long it’s a logical swipe. About the x, I know you @RPNate1 would say that :-). I like to have both ways the classic one and a modern… it’s the good combination that’s matters… 
I started to like the new interface it remains me on a classic amplifier (can’t say radio because I have not had a radio receiver for many many years) with buttons and LED controls AND with modern functions. That’s really cool. That is exactly what RP stands for me: hand made music selection (in a very positive way old fashioned) WITH really good and modern innovations…

**Comment by RPNate1** [comment]
@donshefer another swipe request. Will those work with webviews? Maybe slideshow because it doesn't have multiple elements?

**Comment by RPNate1** [comment]
I have a meeting scheduled with Don about swipes on Monday and we'll come up with the plan we're sticking to for this feature. Closing.
