### ISSUE TITLE
[FR] UI: The selected active channel should be in orange... 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#175]
### 1. Cosmetic and branding issue
This suggestion is neither a bug or a feature request is more a cosmetic issue, but not only it's maybe more. It is kind of marketing issue, branding and connection between the main logo and the channel. And of course a little bit of a uniformity UI issue.

That's the reason why I add you to this proposal: @BillGoldsmith : 👋. 

I have now spent several hours testing the mk2 app (while listening to RP anyway). For me, the top headphone logo (which I think is great by the way) is emotionally connected to the music channel (so in my case, the "RP Mellow Mix"). It is the "Radio Paradise Mellow Mix" or one of the other channels.

Orange is the brand colour of Radio Paradise (at least in my perception) so for me the channel selector should be in orange. This would symbolise and visually create the link between THE RP headphone logo and the unique RP channel selected. That’s an important strong connection (at least for me) even when it’s maybe only unconsciously.

### 2. Uniformity of the UI: The channel display is also an activated button
But there is also a technical aspect besides the psychological one: To ensure the uniformity of the UI, the currently selected channel should be highlighted and in any case not white but orange like the other active buttons. Or like the old fashioned LED indicators on an amplifier in the real world.

So much for my perception or opinion.

Please give me feedback if this is the right place for such less technical comments, because I have more such ideas…

### Where did you see it? (App build version, device type and iOS version):
Build 123, iPhone 13 Pro Max Ultra+, iOS 16.X.X

![IMG_0117](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/3192db4e-2676-4a30-ae58-2817b12f83c1)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Good suggestion and easy to implement.

**Comment by RPNate1** [comment]
@ChristianNoc I'll send an email about your other thoughts

**Comment by ChristianNoc** [comment]
On the way…

**Comment by RPNate1** [comment]
@donshefer please highlight the channel selector's active channel on the main screen.

**Comment by donshefer** [comment]
updated in build 69

**Comment by ChristianNoc** [comment]
Wow there comes quite a lot of new versions in very short time…

**Comment by RPNate1** [comment]
should be almost daily.

**Comment by ChristianNoc** [comment]
Oh that’s sounds a lot of testing work

**Comment by ChristianNoc** [comment]
@donshefer Looks awesome! Perfect!
