### ISSUE TITLE
„Sync channel with Sonos“?

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#176]
## Brief description of the issue:

I use Sonos as my audio system at home. Radio Paradise runs through it most of the time. I like to open the app additionally, especially on the iPad, sometimes also on the TV, and let the nice slideshow run along. I remember a setting "Sync Channel with Sonos". I can't find that option on the website or in the app at the moment. It would be nice if there was this option (again?). Sonos is a very common audio system after all, and the slideshow is a great feature of Radio Paradise, and I'd like to keep that synced with Sonos. Maybe I just haven't found that option anymore.

Thanks a lot!

**Comment by RPNate1** [comment]
The sync button was removed with the update last fall. We have briefly touched on the best way to reimplement a sync function for use cases like this. I've made a note. Nothing has been determined yet.

**Comment by JoschiW64** [comment]
I would like to add that I practically always stream my music via Sonos at home. It is very nice, for example, on the iPad, to view the wonderful photos that match the song. However, this only works correctly with a synchronization. To get this synchronization, as currently necessary, by hand, is difficult to impossible. I have also noticed that there are problems with the Radio Paradise Alexa Skill. For example, if I'm working in the kitchen and don't have my iPhone or iPad handy, and I ask the RP Alexa Skill what's playing, it tells me the wrong song due to the lack of synchronicity.
I (and I'm sure a great many other Sonos users and Radio Paradise fans) found this feature very useful. I would be happy if it came back. 

Thank you.
