### ISSUE TITLE
[UI] Pixels outside visible area

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#177]
In my opinion it should be an empty frame for important elements, maybe 10px left than the max. technical screen size. As the iOS does it in top with date and battery symbol. It should be at least that gap in both mode portrait or landscape mode..

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (64), iPad mini 5, iOS iPadOS 16.4.1 (20E252) 

![IMG_0119](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/c3ba5371-b248-4570-8b0d-ccfd6c8df529)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
@RPNate1 : I've mentioned before that the margins are a little tight. 

Tagging as P5 cosmetic.

**Comment by RPNate1** [comment]
Yep. I've noticed this as well. As we make formatting changes, the effects can ripple across various devices in bad ways. We'll make sure that there are appropriate amounts of padding across devices once all the formatting changes take place.
We'll make it a focus of the last pass of testing, ensuring proper margins and spacing before this goes out.

**Comment by RPNate1** [comment]
My iPad 8 displays the same issue in landscape

![IMG-0114](https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/b3431d59-7abc-4827-87bc-0576a32bce63)

**Comment by RPNate1** [comment]
This will all be sorted with plenty of padding on all devices before e public release...

**Comment by RPNate1** [comment]
I'm going to close this as we know there are issues with the landscape in iPad and this is the same issue. The app will be reviewed to ensure we have padding ALL devices before public release.
