### ISSUE TITLE
[Suggestion] Improve UX around lock icon

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#178]
## Brief description of the issue:
What is the lock icon about?

### Steps to reproduce:
1. display the track list
2. roll over the lock, click the lock, wonder what it does.

### Expected result:
tooltip or some other supportive instruction

### Actual result:
it locks, which is nice. but it's not clear what it's doing. It either:
1. does something to the song, related to updating the rating??
2. locks the view from changing (but it's on a particular song, so that can't be it)
3. does something with favouriting?
4. I'm at a loss..... all I can tell is it's something to do with locking the song... if it's not that, it should be reconsidered. 
5. ok, it's not #2 because the view updated. But the lock moved to the newest song. Really lost on this one - assume I won't be the only one.

### Where did you see it? (App build version, device type and iOS version):
Mk2, Version 0.9, Build 64

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by k00ka** [comment]
![Screenshot 2023-05-25 at 3 27 42 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/4c7b11ad-e077-4aec-9600-1ebb7c127f02)

**Comment by RPNate1** [comment]
The lock indicates the information is locked to the currently playing
track. It will refresh the song data when the next track begins. If a user
scrolls any of the content, data becomes unlocked from updating with the
track. As soon as the user scrolls back to the top of the content (after
reading whatever they were checking out), the lock will reengage and the
content will update to the current track.
This blog covers the functions of the player (and app, as it is based on
the player functions on the website).
https://radioparadise.com/blog/tour-of-the-new-web-player

**Comment by bradtchapman** [comment]
Closing, since this is not an issue.

**Comment by k00ka** [comment]
Appreciate the update - and that this is a website player feature ported here. I do UI design and I still can't quite wrap my head around the utility of it... my 2c.

**Comment by RPNate1** [comment]
It will irritate users, who could be in the middle of reading about the
artist or reading comments about a particular song, when the data updates
with the new track and they lose what they were reading. The content would
just disappear and be replaced by the new track info, resulting in a few
clicks for them to find the info they were reading by exiting the player
and navigating to an individual song info page.
The app currently leans heavily on webviews for the various modes outside
of the native Simple mode. The lock function is operating inside a webview
as a part of the data and function of the Info Mode in the mobile version
of our site. Not really a true port.
