### ISSUE TITLE
Suggestion (b27): in the RP embedded view, hide the download button from user profiles

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#18]
It's not possible to download user data from the app, so don't show the cloud button.  

Steps to arrive here:

- Scroll to comments section
- Tap a user.
- Tap Song Ratings.
- Tap the "cloud" download icon

![2A2C186B-0ABC-4BA5-ACD3-E0B3DD990038](https://user-images.githubusercontent.com/32527656/215837761-74c2332a-620f-40c1-b5c3-0a057b15a2dc.png)

**Comment by RPNate1** [comment]
You can download your rated songs list. However, in the app it doesn't appear to download the files, it just displays them within the app. @donshefer let's make sure this feature works.

**Comment by donshefer** [comment]
@RPNate1  Do you mean download the list of songs at text or download the song files to listen to?

**Comment by RPNate1** [comment]
Text files.

**Comment by bradtchapman** [comment]
The way I look at this is this:

- Traditional online boards dont let you examine someone's profile without registering

- People sometimes leave details in their comments that would allow someone to find them

- The profiles can be potentially scraped by a bot

- Everyone makes regrettable comments sometimes

- You have a large chunk of listeners in Germany, which has one of the strictest data privacy laws in Europe and the world

- People have a "right to be forgotten" and an expectation of privacy

- You should have some way to audit who is viewing whose profiles and comments



—Sent from my iPhone

**Comment by RPNate1** [comment]
I think this comment goes on the profile ticket not here. @bradtchapman I did forward to William with your concerns. We'll see what the boss says. I hear you and will defer to him.

**Comment by RPNate1** [comment]
We're gonna hide this for now. We'll add support for downloads in the future. Closing this.
