### ISSUE TITLE
[FR] Karaoke (as an option)?

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#180]
What do you think about the idea of adding a karaoke function (as an option that the user can select, mind you) for the texts? (not only Apple has implemented this in the meantime). From my point of view, it would have the advantage that you could concentrate on the music and let the text run past you, without having to be distracted from enjoying the music (by manually calling up the text area and searching for the corresponding text passages). If you don't like this option, you don't have to turn it on. I would find this option very cool.
![IMG_0405](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/7103e9dd-4f52-4903-8097-f41f57443012)
![IMG_0406](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/3708ae27-7dbe-48d4-8146-a7b2852b85e6)

**Comment by RPNate1** [comment]
We will be implementing a lyric-tracking function in the future. This is
planned. You will still have to open the lyrics panel.

**Comment by RPNate1** [comment]
This will be added but not before launch. Closing.
