### ISSUE TITLE
[Bug] Album cover image / Album title not loading

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#182]
## Brief description of the issue:
See screenshot.
I saw this only once until now.

In my opinion this should still not be displayed like this

### Expected result:
Correct display of album cover/album
name (or info, in case that it is not available?)

### Actual result:
-Broken album cover display
-Album name „null()“

### Where did you see it? (App build version, device type and iOS version):
Build Mk2 
![IMG_0443](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/2c297c9b-d07f-44a1-a2ee-ded2d58294c4)
0.9 (65), iPhone 12 Pro Max, iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by JoschiW64** [comment]
This was not an isolated case, but, as I have since discovered, happens from time to time. Probably when there is simply no album? Nevertheless, the type of display is of course not optimal
![IMG_0471](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/ccc5f788-21e6-47bd-8896-a8f830b66600)

**Comment by RPNate1** [comment]
Confirmed. Also and more importantly, album art isn't loading for cached blocks in b65. @donshefer

**Comment by donshefer** [comment]
@RPNate1 The cached blocks not loading album art is a different issue on the simple mode screen. That one, I believe, is now fixes in build 66.
The examples in this ticket are load issues associated with the player info webview.

**Comment by RPNate1** [comment]
got it.

**Comment by RPNate1** [comment]
I haven't seen this repeated. Closing.
