### ISSUE TITLE
[Bug] The phrase "No song loaded" can be seen in Lyrics and Comments sheets between songs, and with Station ID tracks.

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#184]
## Brief description of the issue:

I was reading something in the comments section of a song. When Bill spoke his station ID, suddenly a white page with the sentence "No Song Loaded" (or similar, it was too short to take a screenshot) appeared where the comments were before.

### Steps to reproduce:

Go to the comment section of a song and leave it open until Bill's voice comes on and watch the comment section

### Expected result:

Do not show white page with "No song loaded" during Station ID

### Actual result:

A white page with the sentence "No Song Loaded" (or similar, it was too short to take a screenshot) suddenly appeared

### Where did you see it? (App build version, device type and iOS version):
Build Mk2 0.9 (65), iPhone 12 Pro Max, iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
@JoschiW64 to clarify, is this in the comments in the Info Mode view (web view) or the comments when you click the comments icon in Simple Mode (native screen)?
@donshefer let's put a small logo there as a placeholder if possible until the new song starts

**Comment by JoschiW64** [comment]
I try to remember:
First I clicked onto the bubble displaying number of comments. 
![IMG_0484](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/7ea27ce5-6299-472e-9221-cf9dca2905ad)

Then the comment page opened, example attached. 
![IMG_0483](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/99ff63e1-4a04-40b8-aad2-0c4b63ad4137)

Then at some point the short announcement from Bill came and then the comment page was white for a short time and it had the "no song loaded" message on it.
I hope this information helps.

**Comment by bradtchapman** [comment]
I have seen this at least once before.

The comment pane should not refresh if the song type is bumper or station ID.

Or, if it must refresh, display something generic like "thanks for listening to Radio Paradise."  I'm not sure if that is possible; just spitballing.

**Comment by bradtchapman** [comment]
this is actually fairly easy to reproduce and observe without having to control the app on the device:

1. Connect the iPhone / iPad to a Bluetooth speaker that has a "skip" function, or to EarPods/AirPods with a skip function, or to CarPlay.
2. Play a song and show the comments on the phone.
3. **Skip** the current song using one of these ***external*** controls.
Watch the comments pane you left up on the screen.  
4. If the next song is not a bumper, you will briefly see "No song loaded" in Times New Roman font on a white background... and then the next song's comments will load.
5. If the next song is a bumper, this message will stay on screen a lot longer.

**Comment by bradtchapman** [comment]
![IMG_4730](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/07bbadd6-e95e-4d7f-be9d-326c073e895c)

![IMG_4731](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/2174a7cd-4d72-4bdb-96a5-0c33b2b44ded)

![IMG_4732](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/89159a9e-3953-4001-85c2-8c5f50afc846)

**Comment by JoschiW64** [comment]
As an addition: I also had this just now, when I was reading the lyrics (not the comments!) of a Pink Floyd song in my Favorites channel. At the transition to the next song, which was an instrumental piece, the "no song loaded" message came up again (without Bill's Station ID, to fast to take a screenshot), but this time followed by the in my opinion correct display "(instrumental)".
So the "no song loaded" message doesn't just occur in the comments section.
![IMG_0485](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/9c464ed5-5542-4999-895f-eebfe3bd12e7)


![IMG_0486](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/9efcdeac-d279-48a0-ad53-f9ff3f11b12a)

**Comment by bradtchapman** [comment]
Try this for fun:

Drag the lyrics or comments sheet down and hold it near the bottom of the screen while you skip the song on the remote control.  

Demo of this technique done with Bluetooth in the car, using the skip button mounted on the steering wheel.


https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/ffb4210c-2f13-4f8e-8eb5-daceb4cf7041

**Comment by JoschiW64** [comment]
„Nice“ and interesting. Thanks. I confirm. I was able to reproduce it with your technique using my „Sonos app (as a remote control) on iPad setup“, streaming from b95 via Airplay to Sonos.

**Comment by RPNate1** [comment]
@donshefer let's make this a black panel with the headphones logo and "Thanks for Listening!" in RP gold

**Comment by donshefer** [comment]
Replaced "No Song Loaded" with logo and text.
Updated in build 73

**Comment by RPNate1** [comment]
fixed b73
