### ISSUE TITLE
[Bug] Profile: edit fields truncated

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#185]
## Brief description of the issue:
I was attempting to update some details of my profile. edit fields were cut off on the right side.

### Steps to reproduce:

Open the profile
Try to edit some text
(I don't know if it's relevant, I updated the profile picture before).
The input fields for the profile text were cut off on the right.

### Expected result:

The input fields for the profile text should not be cut off at all. The input fields should be easily readable and complete accessible.

### Actual result:

The input fields for the profile text were cut off on the right.

I could also reproduce the error myself again.

### Where did you see it? (App build version, device type and iOS version):
Build 65, iPhone 12 Pro Max, iOS 16.5
![IMG_0487](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/7dc3538e-55a2-4bf2-a872-65b32a052fce)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Confirmed. Web view issue. @jarro this on your end?

**Comment by RPNate1** [comment]
Confirmed the weird editing formatting on my iPad 8 as well...
Note- landscape view isn't scaled properly either.


![82871](https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/721880cc-8869-4d44-90f9-1eaff9845ecc)
![IMG-0114](https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/04af380c-ebd5-4e6f-a534-fb4feca0750f)

**Comment by jarro** [comment]
There are a couple of things going on here.
- rotating screen pretty much breaks layout both in app and webview.    Will need to look into that.   Anything height related might be something I need to look at.   As there is some iOS specific hacks around calculating screen height.
- Anything width  seems more app related as native assets  are getting pushed off screen as well.

**Comment by donshefer** [comment]
I added a refresh on orientation change that may have made this better. Please check it out.

**Comment by donshefer** [comment]
I'm not sure why the edit fields are not filling the whole view. It seems like they are locked to that size.

**Comment by RPNate1** [comment]
@jarro is there any way to fix this?

**Comment by jarro** [comment]
this is just a generic site design issue.   There is an arbitrary limit on width so  things  don't use the full desktop width.   Not a big thing to refactor.

**Comment by RPNate1** [comment]
jarred is fixing this. Gonna close.
