### ISSUE TITLE
[Bug] Poor formatting when "Button shapes" is switched on in the iOS settings in portrait AND landscape mode (even worst)

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#186]
## Brief description of the issue:
Poor formatting when "Button shapes" is switched on in the iOS settings

### Steps to reproduce:
1. Just change the setting “button shapes” (see screenshot in German) in the iOS setting from off to on.

### Expected result:
Nicely formatted buttons with symbols in adequate size not depending from the iOS settings for the button shapes…

### Actual result:
See screenshot… in portrait and landscape mode… at least on iPad

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (65 ), iPad mini 5, iOS iPadOS 16.4.1 (20E252) 

![IMG_0134](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/e18d24b5-54d3-44ce-9287-ba634bc9b476)

![IMG_0137](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/afa8e304-8d3f-402e-aa41-24fa291d81ff)

![IMG_0136](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/29ce9a97-a81a-45a0-99e9-7596faece3ae)

![IMG_0138](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/2769ab5b-1550-400c-9c07-866f82f5e8a7)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by ChristianNoc** [comment]
Suggestion: if it is programmatically possible, I would ignore the button shape switch and never show buttons in the RP app, regardless of whether button shape is on or off (may contradict the iOS design guides). Keep it as much simple as possible ;-).

**Comment by RPNate1** [comment]
Good suggestion. @donshefer is this possible?

**Comment by RPNate1** [comment]
We can't avoid the accessibility buttons. We just need to make sure the icons are still visible within them.

**Comment by RPNate1** [comment]
@donshefer when we do the final checks on formatting, can we make sure the button icons stay a usable size with accessibility button turned on? I'll close this b79
