### ISSUE TITLE
[Bug] Comment area slips away while scrolling down

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#187]
## Brief description of the issue:

I I have now repeatedly and reproducibly noticed that the comment area sometimes does not stop, if you "let go" of it, but slides away upwards again and you then of course get out of the reading flow. 

### Steps to reproduce:

I start reading the comments section and scroll down through it slowly. Then I stop scrolling. Suddenly, the comment area shifts to its original position by itself, and I have to find the last accessed place again by hand. If I'm unlucky, the comment area shifts again after a short time.

To be honest, it doesn't happen every time. Maybe only after a longer period of not using the app. I could not reproduce it NOW when I tried to reproduce it again. Earlier, after not using the app for a few hours, I was able to reproduce it. I have attached a screen recording.

### Expected result:

The comment area should stay unless I actively move it.

### Actual result:

In certain cases, which are not yet clear to me, the comments section moves on its own.

### Where did you see it? (App build version, device type and iOS version):
Build b65 , iPhone 12 Pro Max, iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/aab81f01-02bd-4af9-b6ab-fc0e67846972

**Comment by RPNate1** [comment]
I wonder if this is related to a web view refresh?  iOS losing the state, like what is causing the web view display the web player above the app player bar... thoughts anyone?

**Comment by JoschiW64** [comment]
https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/b0f10457-395d-43de-885f-b76ca044220c

**Comment by RPNate1** [comment]
I cannot replicate this.

**Comment by RPNate1** [comment]
Anybody else see this? Still happening @JoschiW64 ?

**Comment by JoschiW64** [comment]
@RPNate1 
In the last few days I have not been able to see this by chance, nor have I been able to provoke it. It seems that this behavior has been turned off in one of the latest versions.

**Comment by RPNate1** [comment]
closing b73. appears to be fixed. Let's keep an eye out for it.
