### ISSUE TITLE
[UI] Song information should be placed in the middle like the album art (just an other cosmetic improvement)

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#189]
## Just an other cosmetic improvement in portrait mode

The **song information** (song title, artist and album) should be **placed centered** below the album art. Because this information is connected (belongs) to the album art, and the album art is centered, so should be the text song information.

Further on at least in my opinion the **focus** should be clear at the **song title**, so I would print the artist and album titel in different less conspicuous colour like rp.grey? White for song title is ok or maybe rp.orange but the other 2 lines should be not in the some colour as the title.

![IMG_0148](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/0708edcf-c74f-4439-ba3d-fe028360fdff)

## Just a suggestion how it could look like with clear focus on song Titel and centered:

![IMG_0149](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/644b1ede-f87f-4620-84c7-23c044ec8625)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (67), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by JoschiW64** [comment]
Improving the display of song title, artist or band name and album title is a good point that I would like to support with an example.
At the moment I also find the font a bit too "chunky" or "clumsy", but that's ultimately a matter of taste. I'll attach an example where it's not obvious at first glance: what's the band name, what's the album name, and what's the song title?
Especially if you might be new to Radio Paradise. Here, in fact, every line could apply to anything. In fact, you should differentiate that a bit.
![IMG_0393](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/6a340e05-b040-4d77-85ac-db6f4194026b)
![IMG_0394](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/2a5bb563-5c2d-45d6-925d-b503bd34259f)

**Comment by ChristianNoc** [comment]
@JoschiW64 : thanks for your supporting screenshots. Nice that you have a similar opinion. In my suggestion the song title is in the middle in white on focus, above the artist und below the song title the album in different size and colour. For me that’s very intuitive. The song title on focus is in the middle. But it’s totally a matter of taste.

I totally agree with you for some people it may not be obviously what the lines are, even for me I need sometimes more than one look to get it clear and that’s confusing. 

Grüße nach Deutschland…

![IMG_0149](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/644b1ede-f87f-4620-84c7-23c044ec8625)

**Comment by JoschiW64** [comment]
@ChristianNoc: thanks and Grüße zurück!

I like the proposal and design of Christian.
It should only be considered with the small white font that it should not be chosen too small, so that it is still readable on smaller devices.
The clear typographic distinction of the 3 lines and focus on the track title I think is important and correct.
I also think it is important that the typeface and the presentation of the information in all views or in app and webview is consistent and not different.

**Comment by RPNate1** [comment]
@donshefer let's take this suggestion and reformat the Simple mode song info text to match the font size differences in the web view for consistency (making the artist and album slightly smaller text). 

Will keep it left aligned though. ;)

**Comment by ChristianNoc** [comment]
@RPNate1: May I asked you why that song info block has to be left aligned? Is this a fixed design rule?

**Comment by RPNate1** [comment]
@ChristianNoc William says so. ;)

**Comment by ChristianNoc** [comment]
@RPNate1 OK that is a good argument. He is the boss ;-).

**Comment by RPNate1** [comment]
Sometimes that's all it takes. Other times it's worth a discussion.
