### ISSUE TITLE
Privacy / Security (b27): Restrict user profile data to logged in / verified users only.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#19]
Based on my previous issue submission, I think that some parts of the user profile area should be locked off to authenticated and validated users only.  Otherwise you run into privacy issues.  Your new CTO would probably have kittens.

**Comment by donshefer** [comment]
@bradtchapman You should be able to get to the profile unless you are validate. If you can, it's a bug. Please include step to repo.

**Comment by bradtchapman** [comment]
Steps to reproduce:

1. Launch the RP app.
2. Ensure you are signed out by tapping Settings > Log Out (even if it says you are anonymous)
3. Tap "Listen Anonymously."
4. Start playing RP on any stream.
5. Scroll to the comments section.
6. Tap the username of anyone in the comments section.
7. You will now see their profile details.

I should, at this point, note that I am logged into testing.radioparadise.com in the MAIN MobileSafari app.

Is there *any* possibility that your app is reading cookies from a common store used across the whole system, or is your cookie set totally isolated / sandboxed from the main browser?

**Comment by bradtchapman** [comment]
Additional path to view user data:

1. Go to the RP site anonymously.
2. Access the RP site menu.
3. Select Community > Listener Forum
4. Tap any post.
5. Tap a listener's username to view their profile.

**Comment by RPNate1** [comment]
This has always been available on RP, as far as I'm aware. There isn't any sensitive data that's accessible. What do think should be locked off @bradtchapman ?

**Comment by bradtchapman** [comment]
Adding the comment here for consistency's sake:

- Traditional online boards dont let you examine someone's profile without registering
- People sometimes leave details in their comments that would allow someone to find them
- The profiles can be potentially scraped by a bot
- Everyone makes regrettable comments sometimes
- You have a large chunk of listeners in Germany, which has one of the strictest data privacy laws in Europe and the world
- People have a "right to be forgotten" and an expectation of privacy
- You should have some way to audit who is viewing whose profiles and comments

**Comment by RPNate1** [comment]
Passed along and discussion started. Gonna remove from bugs.
