### ISSUE TITLE
[Bug] Image shifted to far right returning in portrait mode 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#190]
## Brief description of the issue:
See steps and screenshot

### Steps to reproduce:
1. Start with ipad in portrait mode
2. Open the new download manager (ipad still in portrait mode)
3. Test the new download manager ;-)
4. Turn from portrait to landscape mode with open download manager
5. Close download manager 
6. Turn from landscape to portrait mode

### Expected result:
Centered album cover in portrait mode as before

### Actual result:

![IMG_0151](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/cf2a8c1c-8ba9-4816-b205-4d86380cb696)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (67), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by ChristianNoc** [comment]
Maybe a timing problem with the sensors? Because sometimes it jumps from that shifted view to the centered and quite often not. The problem is that you can’t operate the player when the view is shifted to the right because the buttons are out of view. Only solution is to kill the app and start new. Hope that helps…

**Comment by RPNate1** [comment]
The reorientation is proving to be tricky. :/

**Comment by RPNate1** [comment]
I'm not seeing this anymore. @ChristianNoc check it out please

**Comment by ChristianNoc** [comment]
@RPNate1 
It seems to be better, but it’s still there. It’s definitely a timing problem. Sometimes you can see that it jumps to the right position. But it’s better…

Build 0.9 (70), iPad mini 5, iOS iPadOS 16.5 

![IMG_0166](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/f3bb649d-9fb1-49b8-a14f-26a4ca496363)

**Comment by ChristianNoc** [comment]
For me it’s not so an big problem anymore because it helps to open the burger menu on the left top and then it jumps to the right position… maybe that information helps for fixing…

**Comment by donshefer** [comment]
I believe this may have been fixed in 74 with the orientation change refresh.

**Comment by RPNate1** [comment]
This appears to be fixed on the iPad Air. @ChristianNoc give it a try please

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 
Yes it looks good now. Sometimes you see the the image is a lil bit right but then it jumps in the Center position. For me it looks fine, so I close that issue.

Build 0.9 (74), iPad mini 5, iOS iPadOS 16.5 
75 not yet in TestFlight…
