### ISSUE TITLE
[FR] Cache auto-refill waits until only one song left

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#191]
## Brief description of the issue:

Auto-refill is very helpful when sporadically connected.  Any time on a wifi network it can fill up a block that is getting low.  However the current refill waits too long IMHO.

### Steps to reproduce:

Create a cache block; in my case it was one hour long.
Play songs until auto-refill kicks in.  
See it was on the last song. 

### Expected result:

It would be nice for auto-refill to engage when the block is half empty.
Or 75% empty. 

Also for an empty block with auto refill to stay until back on Wi-Fi to refill. 

### Actual result:

Auto-refill kicked in on the last song.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 66, iPhone Xs running iOS 16.2

**Comment by ChristianNoc** [comment]
Maybe a stupid question: What exactly should the auto-refill function do? I only know the offline mode so far…

**Comment by RPNate1** [comment]
You know, I've not really used this feature. It was implemented in the mk1 version so we've moved it over to mk2. Can't lose functions! 
Evidently, there are users who like to play cached blocks almost exclusively ( I assume to avoid using constant cell data). This allows them to always have content without streaming. I assume that the original mk1 refill function works like the current mk2 version, reloading at 1 song. @donshefer ?  If they have stream on wi-fi only selected, does it wait for wi-fi to refill? or does it connect to cell anyway to refill?
I think reloading at 50% would be too soon. A lower threshold is better, but maybe more than 1 song ...10%, 5%?

**Comment by JohnADilley** [comment]
> Evidently, there are users who like to play cached blocks almost exclusively (I assume to avoid using constant cell data). 

Yes, when traveling I use cache to avoid cell data, PLUS when out of cell range (camping out!) or on a plane.

> This allows them to always have content without streaming. I assume that the original mk1 refill function works like the current mk2 version, reloading at 1 song. @donshefer ? If they have stream on wi-fi only selected, does it wait for wi-fi to refill? or does it connect to cell anyway to refill?

The mk1 refill kicks in before the last song.  I don't know the fraction of cache remaining, I can try to determine that if it's not evident from the mk1 code base.  LMK if you need me to do that.

My experience with mk1 is when I get back home (or on coffee shop wifi or whatever) I would see the message "Cache block reloaded" indicating it had done the good thing in the background. (The app has to be open for this to work, but it doesn't need to be playing.)

> I think reloading at 50% would be too soon. A lower threshold is better, but maybe more than 1 song ...10%, 5%?

Can we agree on 25% of cache remaining?  :-)

Also it will be helpful for an empty block with auto refill set to stay (empty) in the cache until back on Wi-Fi to refill.

**Comment by ChristianNoc** [comment]
That’s a perfect explanation. Now I understand what this feature is for. Cool. 25% sounds reasonable…

**Comment by JohnADilley** [comment]
One more regression noted: In RP Mk1 when the auto-refill runs it raises a Notification (on iPhone) that says something like "cache block refilled". It will be nice if that can port over to Mk2 as well (just a FR, not a bug). Thanks!

**Comment by RPNate1** [comment]
Implement the "cache block refilled" notification @donshefer

**Comment by donshefer** [comment]
updated in build 72
Caches now refill at 25%
and I added a periodic check every 5 minutes to refill

**Comment by RPNate1** [comment]
b72 fixed

**Comment by JohnADilley** [comment]
Nice job in build 72. It refills at 25%, and in addition to the periodic check (every 5m) it also appears to check when I hit fast-forward on a short block (30m). This would have been an easy one to miss, so good work out there. I'll keep testing longer blocks when I'm traveling, at the gym, etc. But closing this one out as complete. Thanks!
