### ISSUE TITLE
[Bug] Modal dialog box "Warning: network issue" appears when playing from cache while offline

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#192]
## Brief description of the issue:

This is an improvement over previous behavior where you'd get stuck in pause (issue #193 ).

### Steps to reproduce:

Select "stream over wifi only" in settings.
Create a cache block.
Disconnect from the network (e.g., airplane mode; happens when still on cellular though).
Play from a cache block (as if you're traveling to William's birthday party :-)

### Expected result:

Smooth playback song after song, until the end of the block is reached.
On end of block, if you switch to a live stream the dialog box is appropriate.

### Actual result:

Upon switch from block to block a warning dialog pops up on the screen:
    Warning
    There appears to be a network issue.
    Please check your connection and try again.
    "OK" button (it's a modal dialog box, other action blocked)

This dialog box also appears:
- after every new song starts playback
- when switching cache blocks while offline
- when switching from live stream into a cache block after losing network

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 66, iPhone Xs running iOS 16.2

**Comment by RPNate1** [comment]
We can't have it constantly reminding people they are offline. 

If a cache block is selected, they should already know they aren't connected. 

Switching cache blocks shouldn't trigger the pop-up, either. 

It SHOULD appear when the block has played through and the app needs to stream.

**Comment by donshefer** [comment]
This has been updated in build 66.

**Comment by JohnADilley** [comment]
Looks good (now testing b68). Clean in both fast forward and song-to-song transition.
