### ISSUE TITLE
[Bug] App crashes when you move the preload slider to the left again

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#195]
## Brief description of the issue:

The app crashes completely as soon as you move the preload slider from the far right to the far left after a successful preload.
I was also able to reproduce this behavior.

### Steps to reproduce:

Go to the download manager

Do a preload by moving the slider all the way to the right. Wait until the preload is complete.

(Continue using the app normally or stay in the download manager).

After the download is complete, move the slider from the far right to the far left.

As soon as the slider is on the far left, the app crashes.

### Expected result:
App should not crash

### Actual result:

The app crashes every time I do this

### Where did you see it? (App build version, device type and iOS version):
Build 68, iPhone 12 Pro Max, 
![IMG_0518](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/4a904434-8208-4bbd-91c1-819f4619aff5)
![IMG_0517](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/8dacd6e7-c297-4672-8c0a-774ce07dbcda)
iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
@JoschiW64 Good catch. I was just looking at this in the crash logs. Thank you for the details.

**Comment by JoschiW64** [comment]
> @JoschiW64 Good catch. I was just looking at this in the crash logs. Thank you for the details.

You are welcome!

**Comment by donshefer** [comment]
Fixed in build 69

**Comment by bradtchapman** [comment]
Confirmed that I saw this yesterday and a crash log was sent automatically by TestFlight.

**Comment by JohnADilley** [comment]
I tried to reproduce the failure but never saw the cache. I moved the slider part way up and let it download; then moved it back down, and nothing happened. Then moved all the way to the right; while loading it didn't allow me to move the slider. After the pre-load was complete I moved it back shorter and again nothing happened.
(iPhone Xs running iOS 16.2)

One thing I did notice when I first pre-loaded it jumped from the currently playing song to another song, presumably the first in the pre-load block. This was disappointing; it was a good song (so many are!).

**Comment by ChristianNoc** [comment]
@donshefer 

On my devices this issue is solved
Build 0.9 (67), iPad mini 5, iOS iPadOS 16.5

**Comment by RPNate1** [comment]
Let's make sure the currently playing song isn't interrupted to play the Pre-load. It should finish and then start the per-loaded cache. We can't be missing good songs! @donshefer

**Comment by RPNate1** [comment]
Updated trello with the current song playing issue. Closing this one
