### ISSUE TITLE
[Bug] Channel missing in channel selection under some circumstances 

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#196]
## Brief description of the issue:

When playing content from the download manager, going directly to the corresponding channel is not possible. The return to the original channel is somewhat awkward.

### Steps to reproduce:

Create a download from any channel, for example Mellow Mix

Play this download

Decide to go back to the „live“ Mellow Mix

In the channel selector the current "Mellow Mix" does not appear anymore, only the preloaded Mellow Mix appears.

You have to select another channel first and only then you can jump back into the „current“ Mellow Mix.

### Expected result:

My suggestion: shouldn't the Mellow Mix also appear there for selection, instead of just the Mellow Mix from the download manager?

### Actual result:

The current running Mellow Mix is missing. To access it, you first have to select another channel, and then you can select the current Mellow Mix again.

(The Mellow Mix is of course only an example at this point).

### Where did you see it? (App build version, device type and iOS version):
Build 68, iPhone 12 Pro Max iOS 16.5
![IMG_0519](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/17307386-1550-4832-8f71-aa9613bd19b4)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
@JoschiW64 I believe this is working as expected. The preload is for the currently selected channel only. If you selected another, it clears the preload. If the user wants to load a block and listen to another or the same channel, they can do that downloading that specific block. @RPNate1, please correct me if I'm wrong.

**Comment by JoschiW64** [comment]
My actual use case was, I go out of the house and listen to the downloaded part on the go. When I got back home, I wanted to listen to the same channel again, but "live..." - to achieve that, I then had to select the Main Mix and only then could I select the "live" Mellow Mix again.

**Comment by RPNate1** [comment]
We have cooked up an idea here at HQ to reinstate the former ability to
sync with the live stream.
Emails have been sent to the devs.

**Comment by donshefer** [comment]
Sync channel has been added in build 70

**Comment by JoschiW64** [comment]
I already noticed this yesterday with pleasure. I could not see any problem with it so far either.
Many thanks for that!

**Comment by RPNate1** [comment]
You're welcome. Fixed
