### ISSUE TITLE
[Bug] UI glitch: preload slider bounces if the pane is dragged up.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#197]
## Brief description of the issue:
I dragged the slider up because I was playing around with the UI, and the slider bubble jumped unexpectedly.  This is a cosmetic issue. 

### Steps to reproduce:
1. Open the download manager.
2. Drag UP and release. 
3. Follow the bouncing ball!

### Expected result:
Ball slider does not bounce.  

### Actual result:
The ball slider bounced. 

See attached screen recording.  

### Where did you see it? (App build version, device type and iOS version):

Observed on two devices:

- Build 68, iPhone 12 Pro, iOS 16.4.1
- Build 68, iPhone SE 1, iOS 15.7.6

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/48c8094c-6e0a-4bbd-ac91-9dac42f3fab2

**Comment by donshefer** [comment]
@bradtchapman That was a weird one. Good catch.
Fixed in build 71.

**Comment by RPNate1** [comment]
fixed b71

**Comment by bradtchapman** [comment]
Confirmed.  Thanks @donshefer @RPNate1
