### ISSUE TITLE
[Bug] UI: Display of Song title information is inconsistent (colour) in the different screens -> confusing.

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#199]
## Brief description of the issue:

- In the simple song screen all song fields (i.e. song title, artist and album) are in kind of white color.

- If the playlist view is switched on, the song title and artist are displayed in RP.orange.

- In portrait mode on the iPad everything is white, if the iPad is rotated the song information changes to RP.orange.

**This is confusing and makes the UI unclear and disturbs the UI flow (beside the music flow).**

### Expected result:
A uniform representation for the same information fields in **all screens.**

### Actual result:
See screenshots

### MY RECOMMENDATION: 
**- Song title ALWAYS in RP.orange; artist and album in that (kind of) white. In all screens.**

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (70), iPad mini 5, iOS iPadOS 16.5 

![IMG_0161](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/f3b2b5d8-d36a-4589-9baa-e8400d7f498d)

![IMG_0160](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a6999902-8f6e-4080-ba6e-87b1679be8fc)

![IMG_0162](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/d8e6072c-ba5b-464b-bcfe-6c6ae77d5fae)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by ChristianNoc** [comment]
Short clarification:
It’s ok when some screens just show the song title and artist instead of all 3 lines. But the colour scheme should be the same: song title in rp.orange the other line(s) in that white colour. My suggestion doesn’t mean that on every screen has to be the whole 3 lines. My first comment wasn’t clear in that point…

**Comment by RPNate1** [comment]
It changes when the song info moves from the main display to the "play bar" this matches the website.
