### ISSUE TITLE
won't resume when connected to Bluetooth speakers

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#2]
app doesn't resume playing when connected to Bluetooth speakers

**Comment by RPNate1** [comment]
Bradley reported- Related to AirPlay, one issue that persists from RP 1.0 revolves around **some** Bluetooth speakers.  If RP is already playing when a bluetooth speaker is connected, RP does not automatically resume playback.  It's the only app I have that uses the standard media / transport mechanisms which does *not* automatically resume playback.  If RP was stopped when connecting the bluetooth speaker, the RP app does not start playing.  It starts to buffer and then stops.  I'm comparing this to the Music app, Spotify, and many others that use standard methods and engage the "Now Playing" widget.

**Comment by donshefer** [comment]
Made some tweaks to this logic and tested. Seems to behave correctly now.

The player will continue on the new speaker when it is joined, but will pause playback when an external speaker (or headphones) are removed. This appears to be consistent with the Music app.

Targeting build 28

**Comment by RPNate1** [comment]
Play was paused when I removed my headphones from Bluetooth, but the play/pause button stayed on play and I couldn't use the button to resume play. Had to exit app to restart. @donshefer

**Comment by donshefer** [comment]
@RPNate1 Please check build 29. I think it's been updated.

**Comment by bradtchapman** [comment]
CONFIRMED.  Bluetooth speaker handoff is improved now.
