### ISSUE TITLE
Bug (b27): user profile page goes black if RP idle too long

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#20]
If I am browsing a user profile in the RP app and the app is idle/background for too long while playing music, the MobileSafari session inside RP is forced out of memory.  This causes the entire area to turn black with no clear way to navigate out.

**Comment by RPNate1** [comment]
@bradtchapman how long is a while? I've tried to recreate on b29. No luck.

**Comment by RPNate1** [comment]
I tried 30 minutes, as that's the suspected timeout according to my google searches, an couldn't replicate. Closing.
