### ISSUE TITLE
[Bug] UI: Inconsistent Display of screens and button functions

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#200]
### UI: Inconsistent screen display and button function

The button control via toggle on/off function for the screens "Playhistory" and "Infomode" really works very well according to my tests. And at the moment I use to 100% the new mk2 app for listening.

In contrast to that, 2 screens behave completely different: the "Lyrics" and "User Comments" screen. These two open an overlay window (the controls and even the song informations are then completely hidden) which can be only closed with an X. In my opinion, this is impractical and for non pro user confusing. And I don’t like it either ;-).

Apart from the worse functionality, the X method to close a window is uncommon on iOS (at least for the apps I know). This is MS Windows like. I don't want to be reminded of MS Windows on an iOS device. ;-).

### Suggestion:
Uniform functionality and operating concept of all windows, namely in one frame within the screen as already implemented in the "Playhistory" and "Infomode". 

@RPNate1 
The only screen where I would leave the X to close for now is the slideshow. However, if the swipe commands are fully implemented, this X would probably also no longer be necessary.

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (70), iPad mini 5, iOS iPadOS 16.5 

![IMG_0163](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a823c2a9-fe76-47e1-94b9-c5b30f427c8b)

versus

![IMG_0164](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/3f2512c4-9f77-46a9-985f-373486659963)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by ChristianNoc** [comment]
Additional remark:
If the two screens for lyrics and comments cannot be displayed in one frame in the main screen, at least a double touch to close the window would be useful and would be a slightly improvement.

**Comment by JoschiW64** [comment]
@ChristianNoc „I don't want to be reminded of MS Windows on an iOS device. ;-).“ 👍👍👍

**Comment by RPNate1** [comment]
They are overlays to maintain functionality when offline. The lyrics and
comments are part of the download cache along with tracks.

The Mode views are web views. Obviously these are only going to
function when connected.

Double touch is a good suggestion. Swipe down would work as well.

The thing with the Xs is that we have a LOT of non-tech-savvy users.
Simplicity is necessary for those users. I appreciate you guys for your
expertise, but there is a portion of the listeners that are easily lost and
a big X is super easy to see, find, and understand. I'm struck fairly often
by how little users actually explore and try new actions/modes. So, we have
to consider that as well.

I intend on having a meeting with Don soon about finalizing the
swipe/touch/etc actions for the app so we can get this thing public ASAP.
It's not quite there but we are close.

**Comment by RPNate1** [comment]
Does a caret feel better than an X? That's what Spotify uses for their lyrics overlay screen (which is what I use a lot for reference for music app interfaces, though I hate some of their choices). 

I think implementing swipe and double touch on most of our buttons and functions will probably be the answer to most of these UI discussions. That way a user can "pick their poison" for their own experience.

**Comment by ChristianNoc** [comment]
@RPNate1 

Oh ok that 2 screens are offline screens. I understand. A carret is this typo ^, isn’t it?

Ok I do understand that the X is well known for closing something, especially for non IT people. Even on iOS to close a safari tab it’s a X sign there. So I must admit that under this circumstances the X is ok and maybe the best solution.

The problem with the X is that for me it’s easier to close a windows with double touch or swipe down because I have not to reposition the hand to reach that X on the top of the window.

> I think implementing swipe and double touch on most of our buttons and functions will probably be the answer to most of these UI discussions. That way a user can "pick their poison" for their own experience.

Yes I totally agree with you, it will be very fine for me with that two other options (double touch and swipe). By the way I like your sentence “to pick their poison” haven’t heard that before…

**Comment by RPNate1** [comment]
@donshefer  swipe down to close both comments and lyrics panels. Keep the X as well.

**Comment by RPNate1** [comment]
b72 this works

**Comment by ChristianNoc** [comment]
@donshefer @RPNate1 

good improvement, x doesn’t disturb me now. Thanks for fixing.

Build 0.9 (72), iPad mini 5, iOS iPadOS 16.5
