### ISSUE TITLE
[UI] „My Favorites“ should be named „RP My Favorites“

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#202]
## Brief description of the issue:

In order to name all channels according to the same scheme, it would make sense to align the "My Favorites" channel according to the other channels in "RP My Favorites".
Otherwise, for example, when streaming via Sonos, this channel is only displayed as "My Favorites" and the reference to Radio Paradise (RP) is missing.

### Expected result:

For each channel should be "RP" in front of it

### Actual result:
„RP“ is missing at My Favorites Channel

Not dependent on a version of the app or OS
![IMG_0613](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/d18a6c01-9a60-4719-b119-843a3d322ee6)

![IMG_0612](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/c4f665da-53c8-46af-add1-37a4a2abd5ba)

**Comment by ChristianNoc** [comment]
Good catch ! Haven’t realised that.
What do you think about that word order?

My RP favourites 

But I think for a native speaker the word order is easier to set in the right way.

**Comment by JoschiW64** [comment]
In my opinion, the information should first be available, which station it is or which radio station. In that case, it's just „RP“. And then, so to speak, as a distinguishing feature, the name of the channel. So it would be logical and the same for each channel.

When I soon get home from work, I'll attach a screenshot of what it currently looks like in Sonos. You can also imagine. But it just looks weird, if only it says "my favorites". If you don't know - which source of music is that supposed to be?

**Comment by JoschiW64** [comment]
![IMG_0619](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/8ed395e5-deb1-4f61-baeb-3a5785d31c8f)
![IMG_0618](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/c635f372-6ed5-4e19-912f-da6383db2805)
![IMG_0616](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/7eae828f-2935-428b-9eb8-d9267d3575ec)

**Comment by RPNate1** [comment]
The reason we have the RP at all is to differentiate between our core channels and upcoming channels that will be made by users and not us here at HQ. The ability to make your own mixed station is coming...

We can add the RP, but the order would be My RP Favorites. I realize it doesn't match the naming convention, but makes sense as Christian says.

**Comment by RPNate1** [comment]
We have enough Sonos (and similar systems) users that this would help out. @donshefer

**Comment by donshefer** [comment]
@RPNate1 The name of the channel is coming from the server. Do I want me to change it manually. Or do you want @jarro to change it on the server?

**Comment by RPNate1** [comment]
Manually. @donshefer

**Comment by donshefer** [comment]
updated in  build 72

**Comment by RPNate1** [comment]
great! This will help out our sonos users. b72

**Comment by JoschiW64** [comment]
❤️🙏

**Comment by JoschiW64** [comment]
![image](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/ac7e57b7-5060-42f6-a262-80ba09b4296d)

looks good!

**Comment by ChristianNoc** [comment]
@RPNate1 
But within the app the channel selector is now a little bit too narrow. Doesn’t look nice on iPad mini. On my tiny phone Oldtimer 6s it’s ok.

Build 0.9 (72), iPad mini 5, iOS iPadOS 16.5 

![IMG_0179](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/286aaf5d-b14a-414c-8bea-e3d5a45c144a)

**Comment by RPNate1** [comment]
@donshefer we're going to need to scale the font size to fit the selector button.

**Comment by RPNate1** [comment]
Moving to Trello. it'll be sorted. Closing it because the main issue is dealt with and this is merely formatting at this point. b73
