### ISSUE TITLE
[Bug] Functions in extra (kebab) menu do not follow network state if  the menu is left open

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#203]
## Brief description of the issue:
If the menu is open and the network becomes unavailable, the controls are not locked out and it will be possible for users to invoke functions that should be available offline.

### Steps to reproduce:
1.  Start a stream.
2.  Open the kebab menu.
3.  Set device to Airplane mode.
4.  Observe buttons are still active.
5.  Optional: try one.  
6.  Close and reopen kebab.  Button state is now accurate. 

### Expected result:
The buttons should immediately change to reflect state.  

### Actual result:
They do not reflect current state until the menu is refreshed.  

### Where did you see it? (App build version, device type and iOS version):
build 71, iOS 16.4.1, iphone 12 Pro

*(Where possible, please attach Please provide screenshots or error message text)*

See enclosed video. 

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/cae00034-7e2d-4d2f-8dd3-4cf9908c0ab2

**Comment by donshefer** [comment]
Menu now closes on network change.
Updated in build 74.

**Comment by bradtchapman** [comment]
@donshefer : silly question perhaps, but what would it take to update the icons **live** without closing the menu?  Closing the menu may startle users.  

In general, some items in the UI could react dynamically to network conditions, but don't presently.

**Comment by RPNate1** [comment]
The menu closes. I'm ok with this as activating Airplane mode blocks the app with a panel, so the menu closes while user is using the other panel. It's not a big deal to reopen the menu once you return to the app. I think this is an acceptable fix.
 
@bradtchapman what other items could react dynamically to the networks conditions. Go ahead and respond here even though I'm closing this bug report.
closed b74
