### ISSUE TITLE
[Bug] Browsing channels causes controls to disappear

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#207]
## Brief description of the issue:
Browsing channels causes controls to disappear.

### Steps to reproduce:
1. Launch the app
2. Choose Listen > Channels from hamburger menu
3. Click on Mellow Mix
4. Choose back + back (twice)
5. Type any key (including shift/command/option/etc)
6. Controls disppear

### Expected result:
Controls should still be visible

### Actual result:
Controls disappear and one has to navigate around or restart to get them back.

### Where did you see it? (App build version, device type and iOS version):
Mk2, version 0.9, build 71, OSX ARM M1 Ventura 13.2.1

*(Where possible, please attach Please provide screenshots or error message text)*
![Screenshot 2023-06-08 at 11 58 12 AM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/38c829a0-4422-4ac3-9648-350b1fae7082)

**Comment by RPNate1** [comment]
This is a known bug. #138 closing as a duplicate.
