### ISSUE TITLE
[Bug] b72 - FATAL - Preload crashes repeatedly, attempts to preload after crash

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#208]
## Brief description of the issue:
in build at 72, I try to pre-load 30 minutes of music, or nine songs. The app showed download progress and got to about song number seven, and then crashed. After restarting the app, I pressed play, then went to the download manager to try again. Unexpectedly, I discovered that it was already trying to load the preload block that I had attempted earlier. I did not ask the app to do this.

### Steps to reproduce:

Watch the video please. 

I believe the crash happens a split second after the attempted music download, when the app it tries to download comments, lyrics, etc.

### Expected result:
I expected post crash for the app to return to a default state with no downloads in progress.

### Actual result:
since the app is trying to restart a download endlessly, I cannot stop it.

### Where did you see it? (App build version, device type and iOS version):
b72, iOS 16.4.1

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/cc45ffff-4315-4296-91c7-78bc2f4e8999

**Comment by bradtchapman** [comment]
I will be attaching the crash logs analytics shortly.

**Comment by bradtchapman** [comment]
[radioparadisemk2-2023-06-08-173554.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11699594/radioparadisemk2-2023-06-08-173554.zip)
[radioparadisemk2-2023-06-08-173646.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11699595/radioparadisemk2-2023-06-08-173646.zip)
[radioparadisemk2-2023-06-08-173509.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11699596/radioparadisemk2-2023-06-08-173509.zip)

**Comment by donshefer** [comment]
Yep, I see it. =)
Fixed in build 73

**Comment by RPNate1** [comment]
fixed b73
