### ISSUE TITLE
Bug (b27): username / password screen field not suggest stored keychain password from www.radioparadise.com

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#21]
### Brief description of the issue:
The username and password field will accept a stored keychain password, but none is currently suggested in the app.

### Expected result: 
iOS should automatically suggest the stored password from an app/site matching the domain name.

### Actual result:
A password was not suggested.  

### Workaround: 
I tapped "Passwords" and searched for "radio paradise" and inserted the existing one from production.

### Steps to reproduce: 
1. Have at least two Apple devices signed into the same iCloud account.
2. **Enable iCloud Keychain** (if not enabled already).
3. Sign into RP at least once in Safari to store the password in your keychain.
4. Access the sign in screen from the RP app.
5. Tap into the username field.
6. Observe the bar just above the keyboard.

The bar should show an option to insert a password saved from www.radioparadise.com.  When tapped, it would check for biometrics and then insert the required credentials.

### Where did you see it? 
Build 27, iPhone 12 Pro iOS 15.7.1.

See attached video.  I had to manually seek out the saved password for Radioparadise.com.  Users will expect AutoFill to suggest their credentials based on the matching domain name.

https://user-images.githubusercontent.com/32527656/215841106-d3f51c12-6fe6-41b2-b006-fd86433c56bb.MOV

**Comment by bradtchapman** [comment]
Updated this ticket with the requested issue template.

**Comment by bradtchapman** [comment]
@RPNate1 @donshefer

**Comment by RPNate1** [comment]
Yep. I was just noticing this today. Luckily, I remember my password, but nobody else does. Let's make sure this works @donshefer

**Comment by bradtchapman** [comment]
Here's the complete guide for password autofill:

https://developer.apple.com/documentation/security/password_autofill/

Apple suggests using "Associated Domains" for "the best experience" and this might be necessary for RP, since these fields are custom made for the app and not part of a web interface.  

Adding support for associated domains:

https://developer.apple.com/documentation/xcode/supporting-associated-domains

It requires setting an app entitlement in the app AND placing a hidden file on your web server.

**Comment by bradtchapman** [comment]
@RPNate1 : what build is this going to be implemented in?

**Comment by bradtchapman** [comment]
@RPNate1 reopening this, since it was not resolved and persists today.

**Comment by donshefer** [comment]
This is working for me, although it is a little clunky. When I click on "Passwords" on the keyboard bar, it sends me to my third party password manager (1Password). I do have to enter "radioparadise" to find the entry (it should come up automatically with associated domain), but then I click fill and it goes back to the app. I tap on the text field and my email and password are autofilled.
Not the smoothest process, but it does seem to work.
I do not have iCloud passwords set up so I haven't tested it with that one. 
I will continue to look into it.

**Comment by bradtchapman** [comment]
> This is working for me, although it is a little clunky. When I click on "Passwords" on the keyboard bar, it sends me to my third party password manager (1Password). 

That is not how the feature is supposed to work.   If the user is in a supported credential field, and they have a password for that domain name saved, it should immediately offer it without tapping Passwords.

Please set up an Apple ID and try saving some passwords in iCloud Keychain.

**Comment by ChristianNoc** [comment]
@bradtchapman 
Here the same. At the login fields I have to tap on “passwords” then I can choose between iCloud and my extra password safe strongbox. But I have to search for the entry in the password safe. It works for me but I guess for the majority of the user it won’t. I can try keychain too…

**Comment by ChristianNoc** [comment]
There is definitely an issue with the login process and password manager. With strongbox it works clumsy but I works. With iCloud passwords I also have to search for the Radio Paradise entry but when the entry is found the login window is closed and after opening the login window again the fields are filled in. This is not as it should be. And as mentioned before the majority will have problems with that procedure…

@RPNate1 I would classify that bug higher, I guess that some users will not be able to login easily…

**Comment by bradtchapman** [comment]
https://stackoverflow.com/a/72921193

This comment here literally outlines exactly what to do, and is summarized from the information I put in an earlier comment on February 2.  The feature requires changes to the app AND the website.  If Don already modified the field for associated domains, you or Jarro have to add a file on the main website so iOS will trust that the app is entitled to request a saved password for your domain.

**Comment by donshefer** [comment]
OK, I have the app side of this working better now, but the password doesn't come up automatically, you still have to search for it to autofill.
In order for it to be automatic, we need to place a file on our webserver. 
I will contact @jarro and ask him to do it.
Updated in build 87

**Comment by bradtchapman** [comment]
Thank you for continuing to work on this.  Your iPhone / Mac users will be very happy.

**Comment by donshefer** [comment]
@bradtchapman @RPNate1 This should be working now. Please retest.

**Comment by scryer999** [comment]
It's not working on my end, at least for Mac version.  Logged out of RP, attempted to log back in.  No password prompt (I use 1Password).  I've checked to ensure 1Password is functioning as expected (logout and login on WSJ.com work fine).  Rebooted Mac, recreated, same result.

Bringing up the RP login page and right-clicking on the password field shows only cut/copy/paste in the context menu. 

Entering cut-and-pasted username and password and hitting "return" key - no result

Entering cut-and-pasted username and password and using mouse to hit "login" link - appears to work fine.

RP version 0.9 (87).  MacOS Ventura 13.4.1(c).  1Password 8.10.8

**Comment by bradtchapman** [comment]
I can also report that this is not working using the iOS app and iCloud Keychain.

**Comment by RPNate1** [comment]
yep. not working.

**Comment by ChristianNoc** [comment]
Different behaviour here on all my devices iPad mini 5, 6s, 11 pro
I still have to search for the Radio Paradise entry but the fields are definitely filled out after choosing the entry for RP.
Tested with keychain and StrongboxPro 1.58.17

**Comment by bradtchapman** [comment]
@jarro @RPNate1 @donshefer : the password saving feature requires a certain kind of file &/or DNS record to be placed on your servers to cover the domain(s) for which password saving can be made available.  

Was this configuration made on:

- radioparadise.com
- new.radioparadise.com
- testing.radioparadise.com 
- some other domain?

**Comment by ChristianNoc** [comment]
Nothing changed in 0.9 (90): I still have to search for the right entry in the password database. Beside that issue the login process is working as it should…

**Comment by donshefer** [comment]
Autofill appears to be working, except for the associated domain which facility the suggestion. I am not sure why. Everything is in place and should be working, but isn't.
I will retest this once the app is moved over and re entitled in the production app in preparation for public deployment.

**Comment by donshefer** [comment]
This now appears to be completely working in build 1001.

**Comment by RPNate1** [comment]
This is fixed in b1001
