### ISSUE TITLE
[Bug] Just cosmetic: Avatar not shown at App launch - “loading channels” should change into “ready to play” when channels are loaded

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#210]
## Brief description of the issue:
After app launch the avatar is not visible on main screen, even when you are logged in. When you open the user Menü with tapping on the empty avatar in the menu the avatar is visible only within the menu.
After pressing play it needs some time (minimum 30 sec but mostly much longer even 5 or 10 min is possible) until it is shown. For me not really important but for new users of the app maybe a lil confusing. 

2nd cosmetic thing: After launching the bottom status message “loading channels” stays forever. It would be nice when that status line changes into “Ready to play” when the channels are loaded. For me also not so important but for the perfection of the app.

### Steps to reproduce:
1. Just launch the app and see…

### Expected result:
Screen update with avatar because in the Menü it’s visible. Status text chage to ready to play.

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (73), iPad mini 5, iOS iPadOS 16.5 

![IMG_0186](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/52d0ab9c-4432-4765-960a-825b2c688b38)

![IMG_0187](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/70d70c94-f877-49ab-b841-475430df1bc1)

## Even after some minutes of playing the avatar is still not shown… and even after the next song… and the next…

I don’t know what makes the avatar appearing…

![IMG_0188](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/95cd14f2-ef28-4407-a917-b4e8c628fa1b)

![IMG_0189](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6d0b45b8-856e-429b-853a-8533a02840fd)

![IMG_0190](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/5d4814be-7e79-408f-abe7-3b1a3e92e856)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
I noticed the avatar thing yesterday. 
+1 on "Ready to Play"

**Comment by ChristianNoc** [comment]
@donshefer @RPNate1 
The avatar appears immediately when you switch to playlist view…

**Comment by ChristianNoc** [comment]
@RPNate1 
Maybe I would print that “Ready to play” in RP.orange colour. Just an idea 💡.  But only that status, for the others grey is perfect.

**Comment by donshefer** [comment]
updated in build 74

**Comment by ChristianNoc** [comment]
Fixed! Thanks!
