### ISSUE TITLE
[Bug] iPad: Infoscreen doesn’t act responsive when turning from landscape to portrait mode

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#212]
## Brief description of the issue:
Start in Landscape Mode, turn on Infoscreen, turn iPad  in portrait mode -> the web view doesn’t fit the new height in portrait mode…

### Additional question
For what is the lock for? Just for jumping to the top of the list screen on the right? 

### Expected result:
Change format of the web view to fit in the screen.

### Actual result:
See screenshot

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (73), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0195](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/e2170c46-b0db-4c88-9f93-5ac859a634b6)

![IMG_0194](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/b42b773b-dece-41d6-8473-49fa584c59f9)

**Comment by donshefer** [comment]
Should be fixed in build 74

**Comment by ChristianNoc** [comment]
@donshefer 
Thanks for fixing, working now. I close that issue…
