### ISSUE TITLE
[Bug] Rating menu: Highlighting only works from the main screen and not from the play history

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#213]
## Brief description of the issue:
Rating menu: Highlighting only works from the main screen and not from the play history

### Steps to reproduce:
1. Open rating menue from main screen
2. Open rating menue from play Historie
3. See the difference

### Expected result:
Equal behaviour view of the same menue

### Actual result:
See screenshots

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (73), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0196](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/04c58aca-6a98-458a-83dd-e6267b6e3aef)
![IMG_0197](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/f9da734e-e2f4-4cfb-a864-da1bae4d76ca)

**Comment by ChristianNoc** [comment]
## additional suggestion for better visibility:

Even if the color for highlighting the frame is well chosen, it is not that visible (logical with the color bar, can't be otherwise). I would also highlight the text of the current score. I am not so sure but I measured the rating text and it’s not pure white. So the chosen rating text could be in pure white and in **bold** or underlined if necessary. Then it’s more difference from the not chosen options. But anyway I would leave the highlightet frame also it’s nice.

What do you think @RPNate1

**Comment by donshefer** [comment]
Fixed selection highlighting from history screen, set selection text color to white
Updated in build 74

**Comment by ChristianNoc** [comment]
@donshefer 
Perfect, looks really good. Thanks for improving… 
I close that issue…
