### ISSUE TITLE
Rock Mix does not start

### ISSUE THREAD

**Issue by toadflaxlane** [BillGoldsmith/iOS-bugfest#214]
iPhone SE ver. 16.5. Connecting iPhone to car, RadioParadise repeated welcome message 6 times then fell silent. This happened after connecting to the car later but then played when changed from Rock Mix to Main mix. I cycled through the mixes, all working but the rock. After 15 minutes, cycling back through mixes the Rock Mix played. Hooking the iPhone to Bluetooth and my hearing aids the issue resurfaced. The Thanks for Listening screen stayed up when on the Rock Mix. Later tried on iPad Air Gen. 5 and it was happening there as well.
![80921](https://github.com/BillGoldsmith/iOS-bugfest/assets/136252701/c2af743b-a546-418a-b783-11581946517c)

**Comment by RPNate1** [comment]
This is site-wide currently. Fixing it. Not app related. closing.
