### ISSUE TITLE
[Bug] UI: The active play indicator should be RP gold/orange instead of the unique green

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#215]
## Brief description of the issue:

This is a similar topic to #175  about using colors and connections within the elements of the app, I mentioned more of the background there.

When I play a song through the app the play indicator (the pause symbol) is a kind of green. A green that is only used once in the app. Already during the first test run, the green play indicator looked like a disturbing foreign object to me at first glance. By the way as on the website.

**During my tests, however, it became clearer to me what is bothering me about it. Here are the reasons:**

### Reasons to change that colour from green to RP.gold/orange

1. Uniformity of the UI - all other active elements are in gold-orange (even the tiny thumbs up button in the forum turns orange when a post is liked).
2. Visualisation of the connections between logo, channel and the play display (And within the app this is only possible with the color match).
3. Clear recognition value of the RP logo (branding), also in terms of color.
4. Even in the past the **only** special colour on a (vintage) tape deck, minidisc, dcc or dat system was the record button in red.
5. My graphic designer might say that this kind of green doesn't match perfectly with the golden orange. Luckily I'm not a graphic designer ;-), so I can't explain the background and how exactly he would explain it. But there is something like a colour wheel and complementary colours for a perfect match.

## How it will look like

I am really convinced that the gold/orange for the play indicator looks much better. So I started photoshop… this is how it looks like in gold/orange… 

@RPNate1 what do you think about it?

![IMG_0202](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/87ec55e6-513a-419e-ae86-8de2bf2b730d)

### Where did you see it? (App build version, device type and iOS version):
Build 123, iPhone 13 Pro Max Ultra+, iOS 16.X.X

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Gold is great. @donshefer 
And center it! lol The screen shot above shows how off center it is.

**Comment by ChristianNoc** [comment]
@RPNate1  :-) Yes!

**Comment by donshefer** [comment]
updated in build 76

**Comment by RPNate1** [comment]
fixed b76
