### ISSUE TITLE
[Bug] The rating menu does not refresh on song change (and then shows the rating of the previous song)

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#216]
## Brief description of the issue:

The rating menu does not refresh on song change (and then shows the rating of the previous song) - maybe works as designed? For me not so an important issue…

### Steps to reproduce:
1. Open rating menue
2. Leave it open until the next song is played
3. Rating menue doesn’t refresh or close at song change

### Expected result:
Refresh with actual song rating OR just close the window at song change; don’t know what’s better… I would maybe just close that rating window at a song change…

![IMG_0208](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/4f4dcad0-c37b-4cac-81c5-39d0f9407acd)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (74), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Let's close it on song change. It shouldn't stay open. @donshefer

**Comment by ChristianNoc** [comment]
@RPNate1 maybe it would be nice to have a message for the normal users like “time’s up for rating… next song already playing”. 
Difficult for me to make suggestions in this case because I can deal with it as it is… but I know normal users are sometimes mh… a totally different thing… 

I will see how it works when my parents starting to test the mk2 app. But I have to be near them and watch how they are acting with the controls…

**Comment by donshefer** [comment]
Dismissing menus on song change
updated in build 75

**Comment by RPNate1** [comment]
@ChristianNoc let's get them going with the app. I want to see what "normal" users think overall. We are getting close to adding a large group of testers. We just need to sort out the remaining issues. Then Don can get going on the TV app.

**Comment by ChristianNoc** [comment]
@RPNate1 
My plan is to install them the app on next weekend, they should be in the beta Programm. I am now travelling back to Vienna…
I am quite curious too how they are dealing with the app. Because they are around 75 and not typical it users, but my mother started to rate songs with the old app without having an account and without any explanations. So I know they spent both time with the app… at least the old one… 

How would you start? I thought that I just install them the app and then just watching what they are doing… or should I give basic explanations about the icons and command.

by the way: How many people are now in the alpha testing Programm. For me it looks like that just around 5 are really active…

**Comment by ChristianNoc** [comment]
TestFlight just shows me the 74 version…

**Comment by RPNate1** [comment]
yeah, no b75 yet.

**Comment by ChristianNoc** [comment]
Rating window is closing now at the beginning of a new song… fixed. Thanks 🙏. 75 just released…

Build 0.9 (75), iPad mini 5, iOS iPadOS 16.5
