### ISSUE TITLE
[Bug] When playing from downloaded cache the infoscreen and playlist buttons are still active and both showing something but not the song information for the cached songs…

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#218]
## Brief description of the issue:

When playing from downloaded cache the infoscreen and playlist buttons are still active and working but shows nothing to do with the cached songs…

### Steps to reproduce:
1. Download a channel cache (without or with refill, it doesn’t matter)
2. Just play the downloaded cache (remark: internet connection is available).
3. Switch to playlist and/or infoscreen. That information has nothing to do with the cached songs, it looks like it’s from the online channel but it’s useless information at this moment.

### Expected result:
As long as the playlist and info mode buttons are active, they should always display correct information. If the playlist or info is not available for downloaded channels, this is not a problem, but the buttons should be marked as inactive.

### Actual result:
No useful information in both screens when cache is played. For normal users, this would definitely be confusing and they would not trust the other functions to work correctly.

![IMG_0212](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/65558b10-e81e-407c-9f7f-1e1c9d9d7191)

![IMG_0213](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/744d4527-816e-4cd9-9d40-a8ef8c3af408)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (74), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by ChristianNoc** [comment]
@donshefer you are located somewhere in Europe uk, aren’t you?

**Comment by donshefer** [comment]
@ChristianNoc Yes, I'm in southern France. About two hours south of Bordeaux.

**Comment by ChristianNoc** [comment]
@donshefer very nice location… good red wine 🍷 and cheese 🧀 ;-)

Can you tell me for for cached songs do you cache the individual Rating too in the local files or is the rating for cached songs only available when internet connection is available during the cached play session… then testing would be easier…

**Comment by donshefer** [comment]
@ChristianNoc The any with existing user ratings should be shown, I think, but without connectivity, it can't be updated to the server.

**Comment by JoschiW64** [comment]
I find the artist info extremely important. Especially on Radio Paradise there are many artists I have never heard of before. Currently I don't have the chance to see artist info when playing from cache. I also miss the wonderful slideshow. At least the artist info is indispensable though IMHO.
![IMG_0730](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/261f45d3-c6e5-4097-8a92-0e1645fe20a2)
![IMG_0731](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/fda00946-70ba-4ec2-93c5-9486abb6a60d)

**Comment by JoschiW64** [comment]
Maybe my last comment is a different but related issue?

**Comment by ChristianNoc** [comment]
@JoschiW64 yeah maybe you open a feature request with that topic… or we ask @RPNate1 what he want with the song information with cached songs and with available internet connection. I think as that screen is just a web view it will not work easily for cached channels, even when it would be nice…

**Comment by JoschiW64** [comment]
> @JoschiW64 yeah maybe you open a feature request with that topic…

Deleted my comments here and opened #221

**Comment by RPNate1** [comment]
William wants the app to call and get any info the user requests when a connection is available. if there is no connection, there will be a pop-up telling the user they need a connection to do that. no more disappearing functions based on connection state. just working function when a connection is present, or a pop-up when no connection.

**Comment by ChristianNoc** [comment]
@RPNate1 
That sounds logical for me… the app is going to be brilliant… :-)

**Comment by RPNate1** [comment]
So close. I had Don push b76 to just here at HQ so we could go over the issues and decide what to do with them. We are streamlining some navigation (no more swipes or toggles, I watched people struggle with them. So simple buttons and streamlined navigation it is) and added a native Play history for downloaded content. Let's give Don a day or two to update the app and push a new build to us all and see what needs addressing after that...

**Comment by ChristianNoc** [comment]
@RPNate1 

As for the toggle function, I must disagree. 
**The simplest switch (every on/off switch is a toggle switch!!!) is the toggle switch.** Everyone uses such switches 100 times a day. So that can't be the reason why someone can't handle a simple toggle switch. **Never ever. There must be some other reason(s).**

Maybe there is a misunderstanding about the wording toggle. 

I totally agree with you that a streamlined simple UI is important for a good usability, and that means also unified elements, less distractions (as well as from additional unique colors with no real function, to much buttons) and so on. That’s why I have consistently reported these UI things as bugs. But that's more of a psychological thing with the streamlined and distractions.

**Comment by ChristianNoc** [comment]
@RPNate1 
But it’s interesting that you mentioned that people struggle with the (first?) use of the app, because frankly said for me (and I haven’t used the mk1 app so much) it was quite difficult too… maybe I get it clearer in mind for what reasons…

**Comment by RPNate1** [comment]
You'll see. I have a new version I'm testing. it cleans up navigation. I have a few things that Jarred and Don are implementing and we should have b78 early next week which should be one of the last couple before we release to the large testing pool of regular users. Then public.

**Comment by ChristianNoc** [comment]
Thanks for letting me know. You're really making it exciting. I am already curious what will change.

**Comment by donshefer** [comment]
Menus updated in build 78

**Comment by RPNate1** [comment]
FYI everyone- Simple Mode now acts as Info Mode (which we dropped since all the data is now available through buttons- artist/lyrics/comments). We are waiting on access to the artist and fully functional comments pages. Those will be implemented in the next build or two.

**Comment by ChristianNoc** [comment]
Thanks for info

**Comment by ChristianNoc** [comment]
@RPNate1 
By the way you are right, the navigation looks cleaner now…
