### ISSUE TITLE
[Bug] Downloaded cache delete itself under some circumstance one by one :-((

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#219]
## Brief description of the issue:
Maybe similar to #217 but a lil different…
Downloaded cache delete itself under some circumstance

### Steps to reproduce:
1. Playing mellow mix
2. Preparing my offline cache collection as I wanted (see screenshot)
3. Download is ready
4. I don’t touch the prepared downloads anyway I just downloaded it for later
5. Then I start a preload and one of the downloaded caches get deleted (grr)
6. Every new preload session deletes my prepared caches, one by one… (grrgrrr)

### Expected result:
Only I decide what I want to delete… 

![IMG_0220](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/c1579afd-f372-414e-98c6-9d90093f8c3f)

![IMG_0221](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/16581672-c765-4ad2-a5cf-81afc4d4436d)

![IMG_0222](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/8dae3466-3f49-40e9-af8b-813d705f109a)

![IMG_0223](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/fc772962-f38c-48a4-8ac7-26d0460b8bc4)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (75), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Oh yeah, this should not happen. Weird.

**Comment by RPNate1** [comment]
I can't recreate this. I'll try some more. Try uninstalling and reinstalling the app @ChristianNoc

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

i reinstalled the app… then it seems to work… played around with different downloads… problem occurs again… pls reopen… there is definitely a problem… how can I show you? Definitely in combination with preload… 
I didn’t delete any cache manually…

![IMG_0228](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6a143575-1b9f-4f4a-86e6-bc77cb0d42b6)
![IMG_0229](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/0bb32b48-8e4b-447b-9ba7-0297442afbb2)

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

Happened again

problem seems to exist under the following circumstances: (I am still verifying):

- It must be the same channel that is already downloaded (in my instance the mellow mix downloads). The latest was the mellow low 52 min (see pic).

- Then start a preload session for the **same** last downloaded channel (again the mellow mix) -> the last downloaded mellow mix cache is gone… in the pic the mellow low 52 min And as seen in the pic it plays the preload session…
- I didn’t delete it manually

![IMG_0234](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/dfc1b6a1-8d4b-4af3-b5e8-8a4228faabb8)

![IMG_0235](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/d4efe972-25dd-432b-af12-645281f3d4eb)

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

But now I can’t delete the mellow high 3 with the procedure… Mh but there is a definitely a sneaky bug somewhere… it’s not every time. On the afternoon testing session it was clearer and every time…

is there with iOS an Programm like the windows problem step recorder available?

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

New insight: the downloaded cache must be low in quality, then I can currently reproduce the deletion at the moment every time... 

![IMG_0247](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/2632250c-e0d9-46c2-8816-ab15204f662f)

![IMG_0246](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/7146bc3b-fa6a-4172-8685-c430852a2d15)

Build 0.9 (75), iPad mini 5, iOS iPadOS 16.5

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

Now I can delete the Rock Channel Cache too! It seems to be that there must be at least 2 downloaded cache blocks of the same channel. Now let the bug delete the rock channel cache…

rock mix low 7 min
Rock mix med 21 min

![IMG_0248](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/f3161405-4497-43db-9c95-a902e4b8946d)


Start preload rock channel and the **rock mix low 7 min** is gone

![IMG_0249](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/472c5de6-8b38-4f25-8ad1-9f3c69501a9b)


I am sure now I can play that bug with every downloaded channel. 

Enough testing for today…

**Comment by RPNate1** [comment]
I just reproduced it. That's a weird one.

**Comment by ChristianNoc** [comment]
@RPNate1  It was a bad fight with that nasty bug, it tried to hide and come out some times. I always find such nasty things in software. But it really makes me tired 😴 
Happy that it is visible now…

**Comment by donshefer** [comment]
@ChristianNoc @RPNate1 Great sleuthing. There was indeed a subtle bug in the identity code causing havoc. 👍🏻 
Fixed in build 76.

**Comment by RPNate1** [comment]
Fixed in b76
