### ISSUE TITLE
[Bug] Downloaded Cache is always shorter then requested (approximately 1 Song or 6 min per hour)

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#220]
## Brief description of the issue:
Downloaded Cache is always shorter than requested (approximately 1 Song or 6 minutes per hour). Yes it’s maybe only cosmetic but easy to fix (in my opinion).

### Expected result:
Nearer the requested time, sometimes a little longer and sometimes shorter. But not always shorter and the gap is growing with longer requested time…

### Actual result:
See screenshots (requested 1 hour, 2 hour, 1 hour)

![IMG_0220](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/552d6640-2093-4f35-991b-40934f0caac2)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (75), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Changing to a song average of 4 minutes from 3.5 would fix this. @donshefer can/did you make this change?

**Comment by ChristianNoc** [comment]
@RPNate1 
Maybe I am wrong but to fill in more songs in the same time the average song time must be shorter from 3.5 to 3.0 min?

**Comment by RPNate1** [comment]
You're right. I wonder if the idents are counting as songs...

**Comment by donshefer** [comment]
@RPNate1 Yes, the average song length used for time calculations is 4 minutes in the app and on the server. The block requested has to end on a song, so it will always be at least a few minutes off of the requested time.
If you want it to be more accurate, you'll need to have the server take a time input instead of a number of songs.

**Comment by ChristianNoc** [comment]
@donshefer @RPNate1 
Just my short thoughts: I would do that quick and dirty: for every minute requested I would add internally 0.1 minutes, for instance requesting 30 minutes the Programm would calculate with 33 minutes, 60 min request will use 66 min internal.  I think it’s not a problem when it is a little more than requested, always less is for me not nice… In my logic it will never be the exact time requested but it should be definitely not in that way that the gap between requested time and actual time is getting bigger… what do you think about my quick and dirty idea, is there a chance that it will work or is it nonsense?

**Comment by RPNate1** [comment]
I'd like to get this as close to spot on as possible @jarro can you get with @donshefer and figure out the best solution on this?

**Comment by donshefer** [comment]
Because we are downloading individual songs,
There will always be a few minutes off, plus or minus.

I don’t see a problem with that.

- Don

**Comment by ChristianNoc** [comment]
@donshefer Agree with you that’s clear for me, but it shouldn’t be always shorter and the gap getting bigger 

https://github.com/BillGoldsmith/iOS-bugfest/issues/220#issuecomment-1597688776

>I think it’s not a problem when it is a little more than requested, always less is for me not nice… In my logic it will never be the exact time requested but it should be definitely not in that way that the gap between requested time and actual time is getting bigger…

**Comment by RPNate1** [comment]
Let's stick with what RP has always used- 4 mins. Users can request more songs easily to fill in. Closing b79
