### ISSUE TITLE
[Bug] Artist Info (and more) missing when playing from cache

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#221]
I find the artist info extremely important. Especially on Radio Paradise there are many artists I have never heard of before. Currently I don't have the chance to see artist info when playing from cache. I also miss the wonderful slideshow and other features. At least the artist info is indispensable though IMHO.

### Steps to reproduce:

Start playback from the cache
-Try to find the artist info of the played track
-Try to find the lyrics
-Try to start the slideshow
-Try to display playlist of cache channel

### Expected result:

(These functionalities are available in the Favorites channel, for example. The "cache channel" is actually a full-fledged channel, except that it is supposed to be available offline or on the go.) Therefore, I would expect identical functionality to the other channels. (Of course also swiping l/r)

### Actual result:
Functionalities mentioned above are missing in Cached channel 
### Where did you see it? (App build version, device type and iOS version):
Build 75/74… /?
![IMG_0730](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/fd6ac637-ac15-4db9-a1a7-a8229871d60e)
![IMG_0731](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/ef5c88e7-d8d1-46b3-86d8-5d195b9884ee)
, iPhone 12 Pro Max, iOS 16.5

**Comment by ChristianNoc** [comment]
@JoschiW64 
>Therefore, I would expect identical functionality to the other channels. (Of course also swiping l/r)

👍🏼👍🏼👍🏼 especially when there is a internet connection available… and extra 👍🏼👍🏼👍🏼 for swiping…

**Comment by RPNate1** [comment]
When offline, Artist info and slideshow won't be available. William wants the icons to remain but cause a notification popup that says you have to be connected to do that. 

The List Mode (history) will be a native panel that will function offline (currently being built). Lyrics are always available by clicking the lyrics button.

However, when a connection is available, William wants the app to make an API call and pull up all the functions for songs while playing from a cache block. 
@donshefer

**Comment by JoschiW64** [comment]
Thank you for the comments. I hope I have understood everything correctly.
It's not about "offline" in the case I'm thinking of, which is more the rule for me and probably for many others: my typical use case and one reason for my request was that before I head out (hiking, biking, driving, shopping... ) I often fill the cache manager.
I do this because mobile data volume is relatively expensive here, and I want to enjoy music in the highest possible audio quality on the go - without using up my limited mobile data volume. Nevertheless, I have an Internet connection via the mobile phone network, of course.
If I understand correctly, there would be no message in that case, since there is an Internet connection. Nevertheless, I would not be able to get information about the artist/band in the app for artists I do not know yet. That would be a not insignificant disadvantage for me.
Well, of course, I could then switch to Wikipedia on the go and check, but that's not comfortable ...
That was the background of my comments or idea.

**Comment by RPNate1** [comment]
I get it. To clarify, you WILL get the info. If the connection is
available, the app will pull the data for you. The data will be small
relative to the music download.
I discussed it with William and he wants it this way.
He wants the icons/buttons available at all times. If offline you'll get
the notifications that the function requested isn't available.

**Comment by JoschiW64** [comment]
Thanx a lot! Now I understood! Great!

**Comment by RPNate1** [comment]
Awesome. I'm happy to steer it this way, as it cleans up some things that
were getting needlessly complicated and will allow us to get out of
development quickly and move on to more things at RP.

**Comment by ChristianNoc** [comment]
Perfect solution. Like it!

**Comment by donshefer** [comment]
Updated in build 79

**Comment by RPNate1** [comment]
@don artist link leads to the RP homepage, it should link to /artist-wiki

**Comment by donshefer** [comment]
@RPNate1 This has been fixed in build 80

**Comment by RPNate1** [comment]
this all seems fixed in b80
