### ISSUE TITLE
[Bug] As #188 much better but not 100% ok, right bottom Menue in landscape not still not visible

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#222]
## Brief description of the issue:
As closed #188 

![IMG_0269](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/cdc86188-679a-45b3-bb9a-43d0bc30de71)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (78), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by ChristianNoc** [comment]
In List view it looks different

![IMG_0272](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/2563109b-20ad-4574-98fe-fbfffa37a6b6)

**Comment by RPNate1** [comment]
@ChristianNoc check in b79 please. Works perfectly on my iPad Air at work. Will try to remember to check my iPad 8 at home.

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 
B79

no still doesn’t work. Not useable on iPad mini in portrait mode… without the bottom burger menue… that the channel selector is cut off ok that’s just clumsy because there is enough space… but the menue has to be there. 

![IMG_0278](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/b33fc983-27ea-4c7c-a3a3-47ba8a96773a)

![IMG_0277](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/0928db40-e824-4352-b63e-aa40bc73e26e)
![IMG_0276](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/e5f7efe0-865c-4856-92fd-d4668c0b49dd)
