### ISSUE TITLE
[Bug] A quick feedback on the interface and a final cosmetic improvement 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#223]
## Brief description of the issue:

To me the interface looks really harmonious now, especially the color scheme shows the RP gold. I like that very much.

One small thing that catches my eye again is the slightly too dark number display within the heart rating. Sometimes I almost feel like Mr. Monk, because such little thing really catches my eyes immediately (I don't like this series Monk at all, by the way).

## How it looks now

The little bit too dark grey makes the rating digit unclear because of the missing contrast. It looks a kind of dirty for me… and as it’s my rating it shouldn’t look like this ;-)…

![IMG_0270](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/5cbf4ad6-ab73-415b-8ea3-f0fd0719b985)

## It will look much cleaner and easier readable in 198,198,198 (and one unique colour less)

Since I don't want to write too much, I started using Photoshop again. Probably would have to change that in the playlist view as well, but definitely in the main interface. Color 198,198,198 as the other buttons on the main view.

![IMG_0273](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a95ec0ce-ff0d-4433-aa56-89c2124e60ea)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (78), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Thanks! Gonna leave them this way. Settled on that while launching the 'new' website many months ago.
