### ISSUE TITLE
[Bug] Comments / web view refreshes unexpectedly, intermittently (animated headphones appear)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#224]
## Brief description of the issue:
In the last few builds, the web view has refreshed spontaneously and without warning, which causes the animated headphones to appear.  Sometimes while sitting still, sometimes while scrolling, sometimes while entering comments.  Without any 'web inspector' or debugger in this view, it's difficult to audit.  I presume it affects all devices, but I have observed it on the iPhone 12 Pro and also the iPhone SE (tiny phone).

### Steps to reproduce:
1. Start playing a song.
2. Load the comments view.
3. Wait.  It might refresh immediately, or in a few seconds.
4. Try to scroll, it might happen again.

### Expected result:
The comments page never did this until the last few weeks.  I'm guessing it's a change made in the web code, not induced by the RP app.

### Where did you see it? (App build version, device type and iOS version):
Build 79, iPhone SE 1st Gen, iOS 15.7.x
Build 78, iPhone 12 Pro, iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

Screen recording from the tiny phone attached.

**Comment by bradtchapman** [comment]
https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/65f4103c-234d-48b0-b73c-a91515cc9dc0

**Comment by bradtchapman** [comment]
In the above video, scrub to 0:10 and watch closely.  A couple of times, the scrolling gets a bit jerky, or something unexpectedly appears on screen, right before the crash / reload.  

I don't know if WebKit is crashing, or if there is some bit of code inducing a refresh, but that should not happen.

**Comment by donshefer** [comment]
I have not been able to replicate this issue.
@RPNate1 Can you please verify?

**Comment by bradtchapman** [comment]
Could we ask our other bug submitters to check / validate this?

**Comment by RPNate1** [comment]
I can't replicate the web view reload issue. I scrubbed through the video several times. Something is definitely going on there. Weird how it doesn't affect any of my devices. 

However, I do have an issue in b80 where the web view won't update to the various pages consistently, but I brought that up in Trello with Don. Probably not related but I don't know...

**Comment by RPNate1** [comment]
I deleted and reinstalled the app and it cleared up my unrelated web view issue. 
@bradtchapman delete and reinstall and confirm or clear this bug, please

**Comment by RPNate1** [comment]
did a reinstall fix this for you? @bradtchapman

**Comment by bradtchapman** [comment]
@RPNate1 : I think so... but I'll keep an eye on it.

**Comment by RPNate1** [comment]
tentatively fixed in b80
