### ISSUE TITLE
[Bug] In simple mode, song info shifts unexpectedly when paused / resumed.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#227]
## Brief description of the issue:
When I pause the music, the graphical elements disappear.. and the title/artist/album shift down to fill in the space.  When resuming, the graphics reappear and the text shifts back up.  This appears to be in recent builds.

### Steps to reproduce:
1. Load a station and start playback.
2. Press Pause.
3. Observe text shift. 
4. Press Play.
5. Text shifts up.

### Expected result:
Text should not move unexpectedly.

### Actual result:
Text moved unexpectedly.  

### Where did you see it? (App build version, device type and iOS version):
Build 81, iOS 16.5, iPhone 12 Pro

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/8cc04b66-2042-4659-b2f6-aa560daae9e7

**Comment by donshefer** [comment]
@bradtchapman This has been specifically requested for the informational elements to be hidden when pressing play/pause. It appears to be working as expected.

**Comment by bradtchapman** [comment]
Is there a way to hide the elements without causinf the text to move?  What about setting the opacity of the elements to zero (fully transparent) ?

**Comment by RPNate1** [comment]
It would be nice if the text didn't move. That will be brought up in the next team review, I'm sure.

**Comment by donshefer** [comment]
updated in build 84

**Comment by RPNate1** [comment]
The histogram/avg/comments/heart all stay present now on pause rather than disappearing. I'm just gonna be ok with this. I wasn't sold on them disappearing and William asked why they disappeared the other day, so we'll just close this one quietly lol.
