### ISSUE TITLE
[Bug] In recent builds, some popup controls are disappearing unexpectedly at random intervals

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#228]
## Brief description of the issue:
I believe Don introduced a change a couple of builds ago to refresh the kebab and other controls dependent on the stream state and whether the listener was online or offline.  Unfortunately this is causing the Kebab and Settings / Profile sheet to disappear randomly.  Sometimes after a couple of seconds, sometimes longer.  

This also occurs even if nothing is playing.  

### Steps to reproduce:
1. Open app.  
2. Play a stream, or not. 
3. Tap the Kebab and start a timer. 
4. Wait for it to disappear and note the time.  (This may be a clue.)
5. Tap it again and time it.
6. Wait for it to disappear, noting the time. 
5. Repeat steps 3-6 with the Settings / Profile button. 

Note: patience may be required to test this (up to 2-3 minutes to observe effect, but might be sooner).

### Expected result:
As in previous builds, controls should always stay on screen until the user makes a decision.

### Actual result:
Controls disappear unexpectedly, resulting in frustration and repeated attempts to access features in the app.  

### Where did you see it? (App build version, device type and iOS version):
Build 81, iOS 16.5, iPhone 12 Pro

*(Where possible, please attach Please provide screenshots or error message text)*

Screen recordings to follow.

**Comment by bradtchapman** [comment]
screen recordings: 

https://imgur.com/a/hAk8VKD

**Comment by RPNate1** [comment]
I cannot replicate this. When was the last time you did a fresh install? @bradtchapman

**Comment by bradtchapman** [comment]
When you asked me to do that last week.

**Comment by RPNate1** [comment]
Weird. My screen timed out and no disappearing panels. I had the app in the background as well and still no disappearing panels. It did disappear on a song change but that feels ok...

**Comment by bradtchapman** [comment]
Disappearing on a song change happens at slightly unexpected moments.  It can also happen if you're too quick tapping another menu immediately after hitting the Skip button.

**Comment by RPNate1** [comment]
Ah, I see that skipping, selecting a menu, and then the song changes causing the menu to disappear can happen if you're quick on invoking a menu. @donshefer have the menus stay until the user taps to dismiss or selects a menu item. Let's not dismiss the menu on song change.

**Comment by bradtchapman** [comment]
IIRC, Don modified this because I suggested to have the icons change dynamically depending on network state.  His suggestion was to close the pop ups.  I think there may be some hidden activity that triggers a closure.  

It was happening for me on cellular while out on the road, even with a moderate signal strength.  Did you also test on cellular?  Perhaps Don wrote the menu closing subroutine to respond to a "signal" from an Apple networking framework.  

Keeping the menus open is preferred; try not to do something unexpected for the user, or else they may get briefly disoriented or frustrated.

**Comment by donshefer** [comment]
I removed the dismiss menus on song change. Given that the menus are no longer changing based on the network state, should be ok now.
Update in build 84

**Comment by RPNate1** [comment]
fixed in b82
