### ISSUE TITLE
[Bug] Downloads are ephemeral and disappear before being fully used, cannot create multiple downloads

### ISSUE THREAD

**Issue by Rutenber** [BillGoldsmith/iOS-bugfest#229]
## Brief description of the issue:
When I create a download mix and begin listening and then interrupt it the downloaded mix disappears. (also - In MK1 both the downloaded mix AND the original mix would both be available and in MKII ONLY the downloaded mix is available)

This is less convenient than in MK1 since in MK1 one could make downloads of multiple mixes and switch play between them - nice for long car trips!

Also, since the download mix disappears when I use the regular mix, then I have to remember to recreate the download mix before I leave the house (...  I won't remember, lol)

### Steps to reproduce:
1- Select mix (I.e., "RP Global Mix")
2 -tap "RP Global Mix"
3- tap "Download Manager"
4- use slider to select length of download
5- tap "done" when download is complete
6- tap play icon (download plays normally)
7- tap pause icon
8- tap "RP global Mix preloaded"
9- tap "RP Main Mix" (Main Mix channel plays normally)
10- tap "RP Main Mix"

### Expected result:
I would expect that the "RP Global Mix preloaded" would still be there 

### Actual result:
"RP Global Mix preloaded" now completely gone (even though  I had only listened to a small portion of it) and only "RP Global Mix" remains.

### Where did you see it? (App build version, device type and iOS version):
v0.9(81) iOS version 16.5.1

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
There are two functions in the download manager now.  

The top is Pre-loading the current channel.  This is a new feature/tool. This is a temporary cache intended for use when the user knows they will have connection loss and want to store the upcoming (current) music from the stream for a one-time use. The channel will pick up the live stream at the end of that preloaded cache, if a connection is available. If you select any channel while listening to that preload, the app assumes you are back to regular listening and dumps that preload. You can still skip and pause like normal playback. However, if you don't have a connection when you reach the end of the pre-load, you won't have any more music to play. The slider is intended for you to select your pre-load length to your estimated time of not having a connection. 

The second part of the manager is below the preloading feature. This is the original download manager for downloading multiple cache blocks of content. This content is not from the currently playing live stream. It is designed like the past DL manager to cache blocks of songs from a different part of the RP stream in the past. This is what you are looking for to have blocks you can continually play from and will reload automatically (if you toggle the auto-reload on when downloading) causing them to persist. If you don't toggle the auto-reload, they too will disappear once you've completely listened to them. You can select any channel or sync to the live stream and these caches will not disappear. This functions just like RP MK1.

Each feature has a brief explanation below each function of the DL manager.

**Comment by Rutenber** [comment]
Hi Nate!  

Dang, well, I feel so unobservant!!  OK, that all makes sense and I get it.  I do like the idea of the new feature (pre-load) and I am also very happy to see that the "old" option is still all there.  I use it a lot and I love the auto-reload function.

So, maybe just for daft users like me you could make the two parts of that Download Manager screen more distinct?  Currently there is a soft grey bar between them, so maybe make that bar more vivid?  Of course, I see it all now, so it would just be for first time users...
Thank you very much for your explanation.
Earl

    On Tuesday, June 27, 2023 at 01:10:22 PM PDT, RPNate1 ***@***.***> wrote:  
 
 


There are two functions in the download manager now.

The top is Pre-loading the current channel. This is a new feature/tool. This is a temporary cache intended for use when the user knows they will have connection loss and want to store the upcoming (current) music from the stream for a one-time use. The channel will pick up the live stream at the end of that preloaded cache, if a connection is available. If you select any channel while listening to that preload, the app assumes you are back to regular listening and dumps that preload. You can still skip and pause like normal playback. However, if you don't have a connection when you reach the end of the pre-load, you won't have any more music to play. The slider is intended for you to select your pre-load length to your estimated time of not having a connection.

The second part of the manager is below the preloading feature. This is the original download manager for downloading multiple cache blocks of content. This content is not from the currently playing live stream. It is designed like the past DL manager to cache blocks of songs from a different part of the RP stream in the past. This is what you are looking for to have blocks you can continually play from and will reload automatically (if you toggle the auto-reload on when downloading) causing them to persist. If you don't toggle the auto-reload, they too will disappear once you've completely listened to them. You can select any channel or sync to the live stream and these caches will not disappear. This functions just like RP MK1.

Each feature has a brief explanation below each function of the DL manager.
