### ISSUE TITLE
Bug (b27): the "Scarlet Letter" is blank when logged in

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#23]
Someone's a fan of Nathaniel Hawthorne?  Is that why "A" is there for "Anonymous?"

At any rate, since I don't have a profile icon, you need a sensible default here.

![95469EFC-4B77-491A-89C9-BEC730B7ED97](https://user-images.githubusercontent.com/32527656/215842067-168cd969-bf29-4d2d-bcf9-8ae7eaae501a.jpeg)

**Comment by RPNate1** [comment]
That should default to your username initials.

**Comment by RPNate1** [comment]
Upload a damn picture, Bradley! lol

**Comment by bradtchapman** [comment]
Never!  🤣

**Comment by bradtchapman** [comment]
Suggestion: put SF Symbol: "person.crop.circle" or "person.crop.circle.fill" in this location, or your current RP silhouette icon.

**Comment by RPNate1** [comment]
Do we use a silhouette?? I never noticed. 

Silhouette works for me.

**Comment by donshefer** [comment]
Yeah, I like that better than the initial.

**Comment by bradtchapman** [comment]
So would Hester Prynne.

**Comment by donshefer** [comment]
Updated. Targeting build 29.

**Comment by RPNate1** [comment]
Worked! I definitely like the silhouette better. This way Brad doesn't have to upload a photo. I almost uploaded one for you @bradtchapman
