### ISSUE TITLE
[Bug] MacOS interface shifts left/right, up/down when accessing different functions

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#230]
## Brief description of the issue:
The entire UI (except top menu) shifts unexpectedly when switching between Simple Mode and Comments or List View.  

### Steps to reproduce:
1. Load app and resize to "tall" view.
2. Start playing music.
3. Press the Comments button.
4. Observe how elements below the top line (menu, RP logo, Support, Profile) shift to the left.
5. Switch back to Simple Mode.
6. Observe how lower elements jump back to their original position.
7. Click the Heart rating button several times.
8. Look closely as the top line moves up, the bottom section moves down, and the album art grows ever so slightly.

### Expected result:
UI elements should remain completely still.

### Actual result:
UI elements jumped back and forth, up and down, or scaled slightly.

### Where did you see it? (App build version, device type and iOS version):
Build 81, macOS 13.4, MacBook Pro M2.

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/7068596b-c9ae-43d1-8792-8363a9c650c3

**Comment by donshefer** [comment]
#230, #231, and #232 are all the same issue

**Comment by RPNate1** [comment]
Yep. Looks like they are all tied up together. It's a strange bug.

**Comment by bradtchapman** [comment]
OK so Build 82 resolves the large shifts... but there is still a slight up and down shift when opening the top menu, station selector, kebab, or profile icon.  You can see the shift in all elements in the app.  You have to look closely because it's tough to see the movement when they're alternating between dark and light... but it's there.

I *THINK* it's the dark overlay itself that's causing the shift now.

**Comment by bradtchapman** [comment]
https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9acab820-565b-4f8c-87e0-ecdd7efe9118

**Comment by bradtchapman** [comment]
In the above demo video, I was clicking on the Station Selector at the bottom of the screen.

**Comment by bradtchapman** [comment]
And in this demo, I am clicking the app menu at the top left while cropping to show the bottom of the app.

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/ac1c29d0-6924-46f9-bae5-f0a740a14f07

**Comment by bradtchapman** [comment]
https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/993c2371-1d6e-4145-91ad-bcffcd6a79f5


In this example, I am clicking the station selector.  Watch how the controls shift, and also the word "playing" is irregularly cut off after moving down.

**Comment by bradtchapman** [comment]
@RPNate1 : for some reason this still looks wrong on my M1 MacBook Pro, but looks fine on my M2 MacBook Pro.  Same display size, same OS (13.4).  

See attached screenshots.

<img width="943" alt="Screenshot 2023-06-29 at 1 44 03 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/54609d49-ffa0-48ae-8579-7ebb22cebf66">
<img width="735" alt="Screenshot 2023-06-29 at 1 43 58 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/d40eafb4-d714-47f2-8454-65f63feda779">

**Comment by RPNate1** [comment]
WTAF?

**Comment by bradtchapman** [comment]
That's pretty much what I said, lol! 

I tried uninstalling and reinstalling the app.  No change.

**Comment by donshefer** [comment]
@bradtchapman Yep, separate issue. It was the dark overlay. Good catch.
Updated in build 83

**Comment by RPNate1** [comment]
I'm still having the same issues with alignment and padding. It jumps around depending on the Mode selected...

<img width="637" alt="Screenshot 2023-07-03 at 10 35 28 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/65f86fce-8fae-46a3-a443-bb65e2596f33">
<img width="637" alt="Screenshot 2023-07-03 at 10 35 44 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/ef4d9df8-9ef5-45e7-a77a-d2356d5c4bc3">
<img width="637" alt="Screenshot 2023-07-03 at 10 36 31 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/ce956334-5b9e-48df-a441-aebc53f53b92">
<img width="637" alt="Screenshot 2023-07-03 at 10 37 27 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/a2bdfbf8-c273-43aa-9e38-cee2b9e0bad5">

**Comment by bradtchapman** [comment]
<img width="166" alt="Screenshot 2023-07-03 at 12 39 07 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/61f98188-847d-48c8-8f74-00d7ea4b4077">

In either narrow or wide view, the black overlay doesn't quite cover 100% of the screen.  See screenshot.  Brightened for emphasis.  You can see the dark gray status message — the black overlay covers a small part of it.  

In wide view, it's actually worse: the overlay only covers about 80% of the window.

See attached screenshot below.  Can you make the overlay really really big and center it?

<img width="1059" alt="Screenshot 2023-07-03 at 12 45 26 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/02460311-826a-44ff-907b-93a65c7def68">

**Comment by bradtchapman** [comment]
In build 83's wide view, the interface shifts slightly left and right when switching between comments and simple mode.

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/d1f9c8f4-848e-41f0-bd7f-1d8e1a064fe9

**Comment by donshefer** [comment]
Lots of UI updates in build 84.

**Comment by RPNate1** [comment]
<img width="916" alt="Screenshot 2023-07-10 at 5 21 02 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/dad13890-245a-43b1-9306-70edf015fb2b">

Only a bit off on the right side in wide mode now.

**Comment by RPNate1** [comment]
not shifting anymore. fixed in b84
