### ISSUE TITLE
[Bug] MacOS: Channel list popup is misaligned relative to channel box (both narrow & wide views)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#231]
## Brief description of the issue:
The channel selector popup is not aligned / centered over the channel ID popup.  This appears when clicked, and is observable in both wide and narrow views.

### Steps to reproduce:
1. Launch app and play something.
2. Click the channel ID button.

### Expected result:
I expected the popup menu to be centered over the button.

### Actual result:
The menu is misaligned left or right depending on the view (narrow or wide).

### Where did you see it? (App build version, device type and iOS version):
Build 81, macOS 13.4, MacBook Pro M1.

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/01abbb76-72ce-4e9d-8613-c3a717dad271

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/eab59a11-641e-4635-8d29-2ef62e7c4146

**Comment by bradtchapman** [comment]
Build 82 resolved the largest shifts, but I left comments in #230 and screen recordings showing a smaller shift that persists when the black overlay is on screen.  It's not consistent across the app.

**Comment by bradtchapman** [comment]
Note: build 82 did NOT fix the channel popup being misaligned.

**Comment by RPNate1** [comment]
still misaligned in b83

**Comment by bradtchapman** [comment]
Narrow:
![rp-chan-list-misalign-narrow](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/1f6b8afe-0048-4461-934b-657e26045c57)


Wide:
![rp-chan-list-misalign-wide](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/f15d9836-c5ad-4e61-8958-3bc149c525ab)

**Comment by donshefer** [comment]
@bradtchapman  I'm not sure why you are expecting that to be perfectly aligned with the button. In our case, in order to support all device type, I am popping the menu near the button. It seems to me to be clear that the popup is related to that button.

**Comment by RPNate1** [comment]
It's good where has landed in b84
