### ISSUE TITLE
[Bug] Kebab menu is inaccessible on MacOS

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#232]
## Brief description of the issue:
Related to the last two bugs filed for UI issues on Mac, the most important problem is that the Kebab menu is not visible at all.  The only way to access it is to switch to Comments view, which shifts the UI just enough to the left that it's visible.  It's outside the safety margin, as well as a whole bunch of other controls.

### Steps to reproduce:
See screenshots from Issue #230 .

### Expected result:
The Kebab menu should be visible.

### Actual result:
The kebab menu is not accessible

### Workaround:
Click "Comments" first to expose the kebab menu.

### Where did you see it? (App build version, device type and iOS version):
Build 81, macOS 13.4, MacBook Pro M1

*(Where possible, please attach Please provide screenshots or error message text)*

See Issue #230 .

**Comment by bradtchapman** [comment]
Additional note: the Kebab is inaccessible in both narrow and wide views.  Many UI elements are shifted way off center.

**Comment by donshefer** [comment]
@bradtchapman I am having trouble replicating this issue. I saw it, and now I can't get it to happen. Does it happen every time for you? What happens when you close and reopen the app?

**Comment by bradtchapman** [comment]
> @bradtchapman I am having trouble replicating this issue. I saw it, and now I can't get it to happen. Does it happen every time for you? What happens when you close and reopen the app?

Can you share a screenshot or screen recording of what you see on your Mac?

**Comment by donshefer** [comment]
Screen looks like this and doesn't change with the mode buttons:

![Screenshot 2023-06-29 at 5 37 21 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/1120075/ed491bb9-f537-433b-86a5-a0095b52b068)
![Screenshot 2023-06-29 at 5 37 33 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/1120075/3d01e409-8720-4e3c-a767-9cb616afee4c)

**Comment by donshefer** [comment]
@bradtchapman 
You seem to be on the latest version of MacOS. I will update my system and retest.

**Comment by RPNate1** [comment]
I am on 13.4.1. as well and see the same issues.

**Comment by bradtchapman** [comment]
This is resolved in build 82... but all the controls still feel too close to the margins.  If it were me, I'd use the playback progress bar as your left / right margin for the app, not the time elements.  Everything else feels too close to the edge.

**It needs about 1/2" padding or the width of a pinky finger.**

**Comment by RPNate1** [comment]
It looks good in wide view, but needs padding in narrow.

**Comment by donshefer** [comment]
Added more trailing padding for menu icon on Mac
Updated in build 83

**Comment by RPNate1** [comment]
Still has issues in b83

<img width="914" alt="Screenshot 2023-07-03 at 1 48 53 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/3eb911a2-afce-4036-a9d6-614562c39eee">
<img width="643" alt="Screenshot 2023-07-03 at 1 49 47 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/2f181092-4717-4240-8c1e-50f967c602ea">

**Comment by donshefer** [comment]
Updated in build 84

**Comment by RPNate1** [comment]
fixed b84
