### ISSUE TITLE
[Bug] MacOS app stuck in 'playing' state after laptop was asleep for a while.  Does not revert to "stopped."

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#233]
## Brief description of the issue:
I started playing RP and put my laptop away for the day.  When I got home and reconnected it, the app still showed "Playing" but no music was playing.  I pressed "Skip" and the app showed "stopped."  After this, I tried pressing Play/Pause to no effect.  The app did *NOT* warn me about requiring an Internet connection.

### Workaround
I chose a different station and the music started playing again.

### Steps to reproduce:
1. Start playing a station on one Wi-Fi network.
2. Wait a few moments for the music to fully load.
3. Put the computer to sleep and ensure it stays asleep **at least 30 minutes** or 6 songs (the traditional block).
4. Take the computer elsewhere, like home to work or vice-versa.
5. Open it back up and check the app.

### Expected result:
The app should have "stopped" and reflected this in the play control state.  Pressing the button should have caused the currently selected station to reload and resume playing.

### Actual result:
The app did not "stop" gracefully and I had to choose another station.

### Where did you see it? (App build version, device type and iOS version):
Build 81, MacOS 13.4, MacBook Pro M1

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
I should note that intentional actions to cut off networking, like disabling the network interface, *will* trigger the network loss condition.  I also tried blocking the computer from the Wi-Fi using a MAC filter temporarily.  While awake, the app discovered the loss of connectivity.  

Can SwiftUI generate alerts while the computer is asleep?  

At any rate, if there is no internet connection AND all the available music has run out, the app MUST switch to a 'stopped' state so that the user can easily restart it with a click.

**Comment by donshefer** [comment]
updated player logic to gracefully pause when streaming reaches end of queue and there is no network
update in build 84
