### ISSUE TITLE
[Bug] macOS clickable area of the "Support RP" button seems too small; clicking doesn't work over half of it.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#234]
## Brief description of the issue:
The Support RP button only seems to respond when clicked in the center.  See attached screen recording with highlighted mouse clicks.

### Steps to reproduce:
1. Try clicking the Support RP button in various places.

### Expected result:
The button should have a generous tappable area.

### Actual result:
The clickable area seems small and the button did not respond to clicks.

### Where did you see it? (App build version, device type and iOS version):
Build 81, macOS 13.4, MacBook Pro M1.

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/6286f29a-02e2-4ce1-b075-286b07c1e4ab

**Comment by donshefer** [comment]
updated in build 84

**Comment by RPNate1** [comment]
I turned on button shapes in accessibility and the button is larger than the lozenge. Fixed b82. 

@donshefer did you mean b82 or is there a b84 waiting in the wings?

**Comment by donshefer** [comment]
Yeah, Apple had its own ideas and ignored my build numbering. iOS b82 is
it.
