### ISSUE TITLE
[Bug] Web: comment box has no visible / blinking cursor bar on iOS

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#236]
## Brief description of the issue:
It is difficult to interact with, or get visual feedback from, the comment box because there is no blinking cursor bar.

### Steps to reproduce:
1. Make sure you are signed in on the app.
2. Play any station.
2. Load the comments. 
3. Tap "New Comment" button.
4. Observe that the blinking cursor bar is not visible.

### Expected result:
On a computer, the blinking cursor is visible.  

### Actual result:
There is no cursor visible at all.

### Where did you see it? (App build version, device type and iOS version):
Build 82, iOS 16.5, iPhone 12 Pro

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/8455567d-8982-4f83-b165-028d346fd3a8

**Comment by bradtchapman** [comment]
I just noticed that the absence of a cursor makes it practically impossible to **select** inside the box (press and drag your finger) to make selections, inserts, or edits to a comment already entered in the box.  Raising this to P3 due to elevated usability impact.

**Comment by RPNate1** [comment]
Confirmed this issue. @donshefer is this in your realm or is it an issue with the page itself? @jarro

**Comment by bradtchapman** [comment]
This affects the Mac version as well.  The lack of a cursor means you cannot click the mouse to place the cursor anywhere in a comment you're already writing.

**Comment by donshefer** [comment]
fixed in build 84

**Comment by RPNate1** [comment]
fixed b84
