### ISSUE TITLE
[Bug] Comments view only loads 20 comments, doesn't load anymore when scrolling to end of page

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#238]
## Brief description of the issue:
The comments view only showed me 20 comments on a song that had over 200.

### Steps to reproduce:
1. Load a song.
2. Tap the commments button.
3. Scroll to bottom, count up all visible comments.
4. Scroll to top and repeat step 3 after tapping oldest, newest, upvote, downvote. 

### Expected result:
I wanted to see all comments.

### Actual result:
I only see 20 comments.  

### Where did you see it? (App build version, device type and iOS version):
Build 82 (but this is a website / server side code thing, I think)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by jarro** [comment]
fixed.

**Comment by bradtchapman** [comment]
Confirmed.  Thanks!

**Comment by RPNate1** [comment]
I just had this same issue this morning. What's going on there @jarro 
There was a song with 148 comments. I could only see 20 displayed. No scrolling beyond that.

**Comment by RPNate1** [comment]
This should be being fixed now. We moved over to the production website from our testing site (which we have been using to make adjustments to the site for the app) with the outage this morning. Be on the lookout for other bugs. Though the changes we made should all be implemented on production now.

**Comment by RPNate1** [comment]
fixed b83
