### ISSUE TITLE
[Bug] Accessing the list view from 'Sync Current Channel' (not a real station) results in no page loaded, and endless headphone animation

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#239]
## Brief description of the issue:
There is an existing issue in CarPlay where the 'Sync Current Channel' option plays RP Main Mix, but that option also appears as a separate station in the list.  It's not supposed to be a real station.  But if you then tap "List View" while in this mode, it results in the headphones animating endlessly and nothing loads.

NOTE: This behavior persists even after the phone is disconnected from the car if the user is still 'listening' to "Sync Current Channel."

### Workaround:
Select a real station, then go to List View.

### Steps to reproduce:
1. Go to CarPlay mode.
2. Start playing a station.
3. Click "Sync Current Channel."
4. Ensure that the station selector on the phone says "Sync Current Ch..."
5. Tap the kebab menu > List View.
6. The screen will show "Sync Current Channel Play History."
7. The headphones will animate endlessly and never load anything.

### Expected result:
I don't know what I expected.

### Actual result:
The web view never loaded anything.

### Where did you see it? (App build version, device type and iOS version):
Build 82, iOS 16.5, iPhone 12 Pro.

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/556ca224-dafa-4812-8aa8-c0b56466980b

**Comment by donshefer** [comment]
Removed "Sync Current Channel" from CarPlay channel list.
Updated in build 83

**Comment by bradtchapman** [comment]
@donshefer @RPNate1 : I checked this in CarPlay the other day, and "Sync" is gone from the channels list.

The channels list doesn't currently refresh when something changes.  For an example of an app that does, please install **iHeart Radio**.  The tabs refresh their state based on your device's connectivity.

**Comment by RPNate1** [comment]
closing this particular issue. @bradtchapman file a bug about Carplay channel refresh according to connectivity.
fixed b84
