### ISSUE TITLE
[Bug] App is still not operable in landscape mode on an iPad mini: missing menu on the bottom right

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#243]
## Brief description of the issue:
I have already addressed this bug, however it is not fixed yet and the entry has been marked as closed.
I'll save further text as an explanation, the screenshots speak for themselves. And no this is not just a cosmetic bug the app is not usable because the burger menu on the bottom right is simply missing.

That’s really annoying.

### Actual result:

![IMG_0296](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/430fe296-24e9-4a59-b5cc-5a90360ea8d0)

![IMG_0297](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/220d5c58-5b87-482a-b304-f1e37a614e5a)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (83), iPad mini 5, iOS iPadOS 16.5.1

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
@RPNate1 : shouldn't landscape mode on any iPad show the 2-column layout with artist info ?

**Comment by RPNate1** [comment]
Nope. we ditched the Info mode in the iOS apps.

**Comment by donshefer** [comment]
updated in build 84

**Comment by ChristianNoc** [comment]
@donshefer
Ok I will check it after the build 84 is out…

**Comment by ChristianNoc** [comment]
Finally, the player is also operable on the iPad mini :-). With this I close this issue. Thank you!
