### ISSUE TITLE
[Bug] Poor formatting of the playlist history in downloaded channels.

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#244]
## Brief description of the issue:
Poor formatting of the playlist history in downloaded channels.

### Steps to reproduce:
1. Just enjoy the screenshots ;-)

### Actual result

![IMG_0298](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/ea9d2132-c46a-4267-8c79-1445aafe71a6)

![IMG_0299](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/536d5aca-cf12-421b-be2a-04447cf39003)

![IMG_69D7ED6E67BF-1](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/bea24efa-502e-4ccf-ba90-a783b3440cf8)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (83), iPad mini 5, iOS iPadOS 16.5.1
Build 0.9 (83), iPhone 11 PRO, iOS 16.5.1

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
@ChristianNoc : this looks like the font failed to download.  Not normal.  

Do you have a firewall or network filter on your router, or a software firewall like pihole?

**Comment by bradtchapman** [comment]
@ChristianNoc : did this happen more than once - i.e., if you kill the iPad app from the Task Switcher, and then relaunch, does the issue return?

**Comment by donshefer** [comment]
Ah, I see, not a missing font. @ChristianNoc, you have your font size increased in Settings.
I have fixed the issue for the "normal" font sized. The Accessibility sizes are another issue.
Updated in build 84.

**Comment by ChristianNoc** [comment]
@bradtchapman yes I have network filters everywhere ;-) 
@donshefer yes the font size is a little bit bigger than normal, I will test as soon it’s released…

![IMG_0301](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/8582b61f-6b32-46cd-8fae-d86b1df288bd)

**Comment by bradtchapman** [comment]
Ah... I see where you're at.  "Download Play History."

This is while looking at the play history of a downloaded block of music.

**Comment by bradtchapman** [comment]
I finally confirmed this on my own device.  Even bumping the text size up 1 above normal starts to cause the lines to feel cramped.  +2 to +3 oversize is ... not great.

**Comment by ChristianNoc** [comment]
The text is now fully visible and not cropped. However, somehow the playlist now looks compressed. The font is much smaller than in the online playlist. So again the uniformity is not given.

![IMG_0311](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/d3579464-3fdc-4bc3-9f1f-0fbeced191d2)

![IMG_0312](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/8dc8ddfa-e0f1-4e7d-ac58-9da404b07b74)

In my opinion, the font size or ratios should be at least similar for the online and offline playlist. I won’t close that issue. What do you say @RPNate1 ?

**Comment by ChristianNoc** [comment]
Oh and the play indicator button is not centered anymore.

![IMG_0313](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/9b9b43e0-6a15-4cec-8f03-8468251352f7)

**Comment by RPNate1** [comment]
I agree on the formatting of the List Modes. The native one needs to match the web view one much closer.

**Comment by donshefer** [comment]
@RPNate1 Once you hit play in landscape mode, we have to make room for the album cover and information. That doesn't leave room for the play button to be in the middle.
I moved it to the middle for the others and adjusted as necessary. Let me know what you think.
I also redesigned local song history to match web view, added ratings and histograms.
Updated in build 85

**Comment by ChristianNoc** [comment]
Retested
Build 0.9 (85), iPad mini 5, iOS iPadOS 16.5.1 
Build 0.9 (85), Oldtimer iPhone 6s, iOS 15.7.5 

@donshefer 
I like the offline view now. It’s very nice. Is there a reason that the portrait offline view shows the rating in contrast to the online playlist in portrait mode? But for me this is not so important.
The play button in portrait is now almost in the middle on iPad mini... a little bit is still missing or the text is not in the midddle...anyway it’s looks great…I would leave it as it is. Yes in landscape mode there is no space for the play button in the middle. For me it’s ok.

![IMG_0320](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/eea6024a-5896-41e8-a132-3d778565fb82)

![IMG_0319](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/c8c691b4-18c4-4836-b59e-c73b582b9619)

![IMG_0321](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/dc1d0c52-02ba-410a-a7ce-761b59f5b122)

![IMG_0730](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/cda8d4da-192f-42d9-b143-f1f0b373d042)
![IMG_0731](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/847404f3-03e3-45c8-b4c1-be7924cb610b)


For me the issue is now done and I would close it... @RPNate1 If you are of the same opinion please feel free to close as product owner…

@donshefer Thanks for fixing…

**Comment by RPNate1** [comment]
YAY! We will be moving some of the icons as we wrap up this round of testing.
closed b86
