### ISSUE TITLE
[Bug] Erroneous / impossible time format in Download Play History (List View)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#247]
## Brief description of the issue:
The 'Play History' when listening to a downloaded / cached station has the wrong time format.  It shows something like "19:46PM" which is not in accordance with ISO 8601.  Either 7:46 PM or 19:46.

### Steps to reproduce:
1. Download a block of music.
2. Start playing.
3. Tap the Kebab -> List View.
4. Observe the format of the displayed times.

### Expected result:
Time should probably be displayed in 24:00 format to be consistent with the rest of RP.

### Where did you see it? (App build version, device type and iOS version):
Build 83, iPhone 12 Pro, iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
updated to match web in build 84.

**Comment by RPNate1** [comment]
fixed b84
