### ISSUE TITLE
[Bug] In-app browser has been stuck "loading" for >24 hours.  Multiple devices.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#248]
## Brief description of the issue:
The headphones just animate endlessly while loading anything.  Comments, Blog, Home page, etc.

### Steps to reproduce:
1. Start the app and play music.
2. Load anything that is web based.

### Expected result:
Page should load.

### Actual result:
Page doesn't load (it used to!)

### Where did you see it? (App build version, device type and iOS version):
Build 83, iOS 16.5, iPhone 12 Pro and iPhone SE 1st gen

*(Where possible, please attach Please provide screenshots or error message text)*

![image](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/3b66e349-e979-4af7-8be2-559b89ea6948)

**Comment by bradtchapman** [comment]
Update: 

On my iPhone 12 Pro, I switched from Wi-Fi to cellular, then tried loading the pages.  That worked, so then I switched back to Wi-Fi.  Now everything is loading.

I can't do that on the iPhone SE because I don't have an active cellular plan.

Was there a change recently on the back end involving DNS?

**Comment by bradtchapman** [comment]
Edit: I see it now, thank you Charles Proxy.

Was there any server-side change to use HTTP/2.0 recently?  

From the iPhone SE that is malfunctioning, there are connections to the server using an unrecognized / unused connection type according to Charles Proxy.  The phone supports HTTP/2.0 just fine, so something else is going on that the phone doesn't understand.

From the iPhone 12 Pro, it is connecting to some services with HTTP/1.1 TLS1.2, and others with HTTP/2.0 TLS1.2.  

The only connection that works on the iPhone SE is 'api.radioparadise.com; every other service—img, audio-geo, matomo—fails for an unknown reason.  From the iPhone 12 Pro, *most* connections are going through as HTTP/2.0, but some are being dropped (IO: Stream cancelled by client)

**Comment by donshefer** [comment]
I am seeing a lot of intermittent load issue also.

**Comment by bradtchapman** [comment]
@jarro - any insights here?

**Comment by jarro** [comment]
There is a smidge of http2  being  tested.
At the moment  radioparadise.com  and img.radioparadie.com  are  responsive  for all  locales.
And if audio-geo was having issues it would show up in our bandwidth logs.  
 
Only thing that comes to mind is sometimes on my ipad,  individual apps will lose access to parts of the internet and need to be restarted.

**Comment by donshefer** [comment]
@jarro I was definitely seeing intermittent load issues on web view calls to "radioparadise.com". I switched to "testing.radioparadise.com" and they went away. No problems.
I was seeing the "question mark" graphic instead of the loading animation, if that helps.
API calls have been working as expected.

**Comment by jarro** [comment]
There was an issue like that with our Asia server.   You shouldn't be getting routed there.  But possible.
If it happens again,  see if you can get an ip.   
Anyway probably good to be back on testing.   Ran into some things we can try for the edit text issues.

**Comment by RPNate1** [comment]
Closing this one.
