### ISSUE TITLE
[Bug] Looping messages box “Update a available” website problem?

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#249]
## Brief description of the issue:
Looping messages box “Update a available” website problem?

### Steps to reproduce:
1. Just have the playlist view open
2. the update message box appears,
3. Klick on refresh, the box disappear but other things especially a reload is not visible
4. the update message box appears again (max. 50 sec after clicking on reload)
and so on…

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (84), iPad mini 5, iOS iPadOS 16.5.1

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0318](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/994a76bc-6658-446c-94c4-7ef5979255f9)

**Comment by RPNate1** [comment]
We switched bask to our testing site from the production website. You can simply refresh the page. Nothing to be concerned about. We are just dialing in margin and formatting issues.
