### ISSUE TITLE
Suggestion (b27): display a warning when anonymous listeners tap "new comment" button.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#25]
### Brief description of the issue:
The comments section has a "new comment" button that doesn't do anything for anonymous users.

### Steps to reproduce: 
1. Start listening to RP anonymously.
2. From any song, scroll to the comments.
3. Try to tap the new comment button.  Nothing happens.  ("Hmm, that's strange...")

### Where did you see it? 
Build 27, iPhone 12 Pro iOS 15.7.1.

**Comment by RPNate1** [comment]
This a good suggestion. Reuse the same prompt for login. @donshefer

**Comment by donshefer** [comment]
added targeting build 34

**Comment by bradtchapman** [comment]
CONFIRMED FIXED.  A warning is now displayed on screen.
