### ISSUE TITLE
[Bug] Comments always sort by 'Upvotes' instead of remembering my sort order preference.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#251]
## Brief description of the issue:
The comments always seem to load sorted by upvotes.  Are they supposed to remember my sort order preferences (newest, oldest, etc?)

### Steps to reproduce:
1. Load a song.
2. Load the comments.
3. Choose a different sort like oldest, downvotes, etc.
4. Tap the song info bar to switch back to Simple mode.
5. Load the comments again.
6. Observe that they are sorted by upvotes again.

### Expected result:
I expected the comments to remember my preferred sort order.

### Actual result:
Comments always revert to sorting by most upvoted.

### Where did you see it? (App build version, device type and iOS version):
Multiple builds, multiple devices.  Last checked in b86.

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
This is fine. We prefer that people see the best comments. It's easy enough to sort again if you want. 
Closed b86
