### ISSUE TITLE
[Bug] Pre-load only works after sync to current stream

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#253]
## Brief description of the issue:
I tried to pre-load a block while playing from Main Mix, but apparently it wasn't up to sync.  The pre-load button didn't work.

### Steps to reproduce:
Select "stream over wifi only" mode.  Get on a wifi network.
Play a mix (I used Main), in whatever way needed that you see "Sync current stream".
Open Download Manager and see a gray pre-load button; try to drag it to the right.

### Expected result:
The button drags, you get music in your pre-load.

### Actual result:
Nothing happens; you can't drag it until you sync to current stream.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 86, iPhone Xs running iOS 16.5.1

**Comment by RPNate1** [comment]
I opened up the app skipped five songs ahead and used the pre-load with no issue. Syncing isn't required.

I tried it a few more times. Still got it to work right. Try uninstalling your app and reinstall.

**Comment by bradtchapman** [comment]
Same.  Preload slider in build 87 worked fine.

**Comment by RPNate1** [comment]
fixed b87
