### ISSUE TITLE
[Bug] Preload blocks do not last across restarts

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#255]
## Brief description of the issue:
If I restart I lose my pre-load.
I'm not sure if you consider this a bug.

### Steps to reproduce:
Open Download Manager.
Pre-load some music and start playback from the stream.
Switch off wifi, go airplane mode, or have wifi drop while moving.
Exit the app and re-launch it.  The pre-load block is now missing.

### Expected result:
"RP Main Mix (preloaded)" should be an available stream.

### Actual result:
Available Streams show all of the regular mixes and my download cache blocks -- even though I'm offline, and the Main, Mellow, etc are actually not selectable.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 86, iPhone Xs running iOS 16.5.1

**Comment by RPNate1** [comment]
@donshefer Is it possible to keep that pre-load through a restart if the connection isn't present?
any other selection should give the network needed pop-up.

**Comment by donshefer** [comment]
@RPNate1 The preload *does* work across restarts. But it is having trouble starting again if there is no network during the app start, since there are no channels. I should be able to 
 fix that.

**Comment by bradtchapman** [comment]
In this case, how is 'preload' functionally different from 'cache' ?  Is it expected that RP should remember where you left off in the preload?  And when that block ends, it has to sync / catch up to main.

**Comment by RPNate1** [comment]
fixed b87
