### ISSUE TITLE
[Bug] Pre-load can't be re-loaded when it's done

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#256]
## Brief description of the issue:
I can't seem to pre-load again after a preload is exhausted.

### Steps to reproduce:
Select "stream over wifi only" mode.
Be on wifi and enter the Download Manager.
Drag the green dot to pre-load some songs.  In my case it was 55 minutes worth of Main Mix.
Play through the block until it ends (with network Warning message).
Enter the Download Manager again when the block is exhausted, and reenable wifi.
Adjust the slider to the left.
Go offline again (turn off Wifi).
Try to play Main Mix.

### Expected result:
DM should pre-load a new block and let me play the Main Mix from its pre-laod cache.

### Actual result:
"Warning: Please note playback is blocked because you have stream on wifi only set..."

I didn't see how I could coax the app to get a new smaller block.
If I load more I can listen some more, until that block is blown, then stuck again.
It seems impossible to reduce the pre-load block size without a restart and starting over.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 86, iPhone Xs running iOS 16.5.1

**Comment by RPNate1** [comment]
The pre-load slider should reset once the block is played through. That would allow you to set a new pre-load length. @donshefer

**Comment by bradtchapman** [comment]
@JohnADilley : working as designed.  Preload is only meant to be played once.  So are offline caches.  If you want more music, you have to download a new set.

**Comment by bradtchapman** [comment]
@JohnADilley : are you expecting "Preload" to just load more and more music from RP?  I don't know if it was designed that way... 

What is your use case for having RP preload 2 hours of music at a time, instead of the 5-6 songs it does normally?

**Comment by RPNate1** [comment]
fixed b87
