### ISSUE TITLE
[Feature Request] Update the preload time remaining while the download manager is open

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#257]
## Brief description of the issue:
Pre-load content amount (number of minutes in cache) does not update after playing some songs.

### Steps to reproduce:
Select "stream over wifi only" mode.
Pre-load RP.
Play some songs.
Look at the Download Manager.
Play for a while.  Look at DM again... and again...

### Expected result:
DM should say how many minutes are left in the pre-load cache.

### Actual result:
DM said "55 minutes preloaded" in my initial example -- I dragged the green dot to the middle of the window.

When I looked at the DM again it still said 55 minutes.  I played through the block, and it said that the whole time, even after the end of the block (when I got the network Warning message).

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 86, iPhone Xs running iOS 16.5.1

**Comment by RPNate1** [comment]
@don can we have it count down please?

**Comment by bradtchapman** [comment]
Confirmed.  The only way to refresh the time remaining is to close the DLM and reopen it.

**Comment by RPNate1** [comment]
Remaining time of preload is being implemented.

**Comment by donshefer** [comment]
This has been updated in build 89.

**Comment by RPNate1** [comment]
done in b89
