### ISSUE TITLE
[Bug] It seems like pre-load content amount is a lie

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#258]
## Brief description of the issue:
I requested five minutes of content but it's still playing many songs later ...

### Steps to reproduce:
Select "stream over wifi only" mode.  Get on a wifi network.
Open Download Manager and drag the green pre-load button to the right (this time I requested 5 minutes).
Exit DM, see "RP Main Mix (preloaded)" in the Available Streams box.  Play the preloaded stream.
Enter airplane mode or drop wifi.
Listen for a while or fast forward across songs.

### Expected result:
I requested five minutes; I thought I would get one or two songs and then the network message.

### Actual result:
It's still playing at least 20 minutes later.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 86, iPhone Xs running iOS 16.5.1

**Comment by RPNate1** [comment]
Can't replicate this one.

**Comment by bradtchapman** [comment]
Unable to replicate.  Preload got exactly 1 bumper and 1 song for me.

**Comment by bradtchapman** [comment]
@JohnADilley : we need you to open a new ticket with more info, please.  See if you can reproduce the issue, and document your steps.  Also, ensure you are running the latest build (87) when testing.  Thanks.
