### ISSUE TITLE
Network connection message repeats if wifi is busted

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#259]
## Brief description of the issue:
Repeated network connection warning appears when the wifi connection is broken.

This is low priority, also may not be a bug in your opinion.
It does not appear when in airplane mode or when wifi is just "off".

### Steps to reproduce:
Load a block, go to a network where the wifi is not working (no uplink/downlink).

### Expected result:
Cache block plays as intended.

### Actual result:
Warning message appears repeatedly when you open the app (see screenshot).
![IMG_5429](https://github.com/BillGoldsmith/iOS-bugfest/assets/33470056/fe662979-9984-4892-b191-cea74eb2ae2a)

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 86, iPhone Xs running iOS 16.5.1

**Comment by RPNate1** [comment]
I noticed this bug this morning while in a poor wifi area in my house. I think the sensitivity needs to be lessened a hair. Also, it shouldn't show when playing a DL block.

**Comment by donshefer** [comment]
Updated network warning alert login.
Updated in build 87.

**Comment by bradtchapman** [comment]
This approaches "feature request" territory... but I would strongly recommend using a **non-modal dialog** for this.  Some kind of on-screen visual that the network is busted that doesn't require the user to tap something.

**Comment by RPNate1** [comment]
@donshefer maybe we add unstable connection to the bottom status text...

**Comment by donshefer** [comment]
@RPNate1 It doesn't seem like a good idea to only ever show the network issue in the player status. There are times when we want to make sure the user knows there is an issue. Like when the the user is requesting something and it can't be completed.
I agree it is showing too much. I will remove the block in cases where there is no user action. Let's start with that and see how you feel about it.
Updated in build 90

**Comment by RPNate1** [comment]
I haven't had this issue in a couple builds. Keep an eye out. Closing b90
