### ISSUE TITLE
[Feature Request] Expose "Play Count," "Played Last 30 Days," and "Date Added to RP" from the API

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#260]
## Brief description of the issue:
The API contains information about the total play count, frequency in the last 30 days, and the date the track was added to Radio Paradise.  RPv1 shows some of this now.  It would be great for RPv2 to have this.  Maybe a hidden feature where the user taps the histogram / votes area, and it switches to show these numbers.

**Comment by RPNate1** [comment]
We decided to not include a lot of that when we revamped the website last year. The channel pages will have some of that in the future.
