### ISSUE TITLE
[Bug] Remaining time goes negative

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#262]
## Brief description of the issue:
After sync to channel, remaining time is miscalculated and runs into negative time before the track is over.

### Steps to reproduce:
1. Pause the music.
2. Wait for some time - might have to be until a new song is "current" in the chosen stream.
3. Choose "sync to channel"
4. Let the song play to near the end.
5. Time goes negative, initially 0:-3... 0:-4... 0:-5 and later -1:-44.... -1:-45... -1:-46...

### Expected result:
Time should could down to 0:00 at same moment as song finishes

### Actual result:
The app seems to think the song is shorter and runs out of runway...

### Where did you see it? (App build version, device type and iOS version):
Version 0.9, build 87, OSX 13.4, Mac M1 Max

*(Where possible, please attach Please provide screenshots or error message text)*
<img width="695" alt="Screenshot 2023-07-19 at 12 22 10 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/fdb54f41-4382-4332-a658-d4b360a2ac3c">
<img width="676" alt="Screenshot 2023-07-19 at 12 25 46 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/32d01ed1-f0c3-41ca-999d-cb802c887f4b">

**Comment by k00ka** [comment]
Additional info.
The track "Eddie" by The Red Hot Chill Peppers is 5:42.
I synced to channel while the song was playing. I believe the app knows the length is 5:42, and it apportions that time to elapsed/remaining time (so they total 5:42). The issue, it seems, is that the elapsed time is wrong (too high) and so the remaining time ends up being too low. Not sure if bitrates enter into this - I imagine it might be complicated to figure out where we're at in the song. Good luck.

<img width="704" alt="Screenshot 2023-07-19 at 3 02 13 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/d8c789c1-d9b7-4c7d-ad6c-517ba8da6a51">

The next song (and any after) appear to be tracked correctly. Further evidence it's the estimate of elapsed time that s the issue.

**Comment by bradtchapman** [comment]
@k00ka : please update to build 89 and see if you can reproduce this.  Thanks.

**Comment by RPNate1** [comment]
cannot replicate

**Comment by k00ka** [comment]
I just reproduced this now on build 90.
<img width="634" alt="Screenshot 2023-07-26 at 1 45 11 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/a36e1806-0a9b-40e0-b6e8-d628706975d5">

**Comment by k00ka** [comment]
To reproduce, you need to select Sync to Channel.
