### ISSUE TITLE
(sorry) Airplay button in app not working in Mac RP app

### ISSUE THREAD

**Issue by scryer999** [BillGoldsmith/iOS-bugfest#263]
## Brief description of the issue:
Mac app Airplay icon appears to not be working

### Steps to reproduce:
1 Connected Beats Fit Pro via Bluetooth to Mac
2 Fire up RP
3 RP does not show the Beats in the Airplay play list, just the MacBook Pro with a single checkmark.  No listing of other items.
<img width="495" alt="Screenshot 2023-07-21 at 1 32 38 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/134152552/6daf83cc-68b4-4a5f-a20b-23acc1b64e27">

4. Confirmed Airplay is working elsewhere at this time (via Mac controls panel):
<img width="331" alt="Screenshot 2023-07-21 at 1 35 23 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/134152552/966a32bd-ae92-4aa3-84bb-4e2c6291ae96">

Switching elsewhere to Beats Fit Pro (like in the control panel) works fine, but not in RP app.

### Expected result:
Full AirPlay menu consistency

### Actual result:
Missing items in RP AirPlay menu.  I don't have a sandwich either.

### Where did you see it? (App build version, device type and iOS version):
MacOS Ventura 13.4.1(c), Beats Fit Pro A2577, RP App 0.9 (87)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
I see all of the devices in the office. SO MANY choices...

**Comment by bradtchapman** [comment]
I do not believe this is supported. The manner in which your beats headphones connect to the Mac is not using airplay2.  The only options that will appear in the RP app are speakers that support airplay2 protocol. 

nota bene: AirPods will have the same behavior.

**Comment by scryer999** [comment]
I get the point, Beats Pro as with any wireless earbuds are connecting via Bluetooth and not Airplay… but when I pull up another music app (Apple Music) and hit Airplay, the Beats show up.  Shouldn't the RP app have the same behavior?  This does in fact happen in the iOS app.
Apple Music Airplay list, on Mac
<img width="441" alt="Screenshot 2023-07-24 at 5 57 43 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/134152552/0b3c0fb4-14b3-42eb-a054-d1180ac3d39d">

RP Airplay list, on Mac:
<img width="363" alt="Screenshot 2023-07-24 at 6 02 08 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/134152552/a536f80c-8878-4d74-b37c-a119dfe26720">

**Comment by bradtchapman** [comment]
if you can find another example of a music app that offers in-app audio routing to your Beats Pro, that is NOT the Apple Music app, the devs can investigate. 

As it stands, Apple may be using a private method in the Music app to show the list of devices that include both airplay2 speakers and headphones equipped with the H-series chips. 

This is a common theme in app development for macOS and iOS.  Apple has some special sauce it makes only for itself.
