### ISSUE TITLE
[Bug] Download manager only partially downloads requested block if app is backgrounded while downloading, but reports the full block anyway.  Offline blocks end prematurely.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#264]
## Brief description of the issue:
On a slower connection it's not unreasonable for someone to start downloading music and go do something else.  When I return to the app, it says the music was requested, then downloads the art and song info ... as if it was waiting to do this step.   

I think the backgrounding is killing the download in progress, but RP falsely reports that they finished.  Even the station list shows X hours, X minutes remaining.

### Steps to reproduce:
1. Put RP on a simulated slow connection if a real one isn't available.  
2. Start app and access the download manager. 
3. Start a long download (4 hours, high, ultra, or FLAC).  Time how long it actually takes to finish normally.  
4. Delete the block.
5. Repeat step 3.
6. Wait a few moments, then switch out of the app.
7. Do something else for at least the amount of time it took for step 3 to download. Open at least a few other apps and do something that makes the phone busy, like swiping through Instagram, surfing the web, reading news sites, etc.
8. Come back to RP after this delay.
9. If the DL manager is still running, observe the state of the block, and whether it has started downloading art and song info.  
10. Play the block.  
11. Slowly skip through 5-6 songs and note the duration of each one.  Add up the total play time.  
12. Mark the time where "end of block" is reached.

### Expected result:
RP should be able to maintain activity while backgrounded and finish the block. 

### Actual result:
RP is not finishing the music blocks but falsely stating that it has finished.  

### Where did you see it? (App build version, device type and iOS version):
Build 87, iPhone 12 Pro, iOS 16.5.1 (c)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
I tested the download function and it does appear to be working correctly when backgrounded. And it is doing the local notification when the download is complete.
But when the app is halted while it is in the background during a download, the incomplete download is corrupted.
This is pretty edge case, but what would you expect to happen at that point: 
Should the incomplete download be removed, or should it automatically try to redownload?

**Comment by bradtchapman** [comment]
Neither: the app needs to keep itself alive and insist that it not be backgrounded while the download is in progress.  These downloads were tested while the app was **not** playing music.  Please see if there are entitlements or methods you can use, like playing a silent track on loop with the media player frameworks and a "don't kill me" flag to keep the app from being put to idle sleep.  

In the unlikely event that the app dies when a background download is in progress, the item should be canceled and deleted.

**Comment by bradtchapman** [comment]
It's not so much an edge case when someone is on a slower cellular connection and they are planning to download >500 MB of music before they begin an activity that will have no cell service, like flying in an airplane or driving through the woods of Northern California.

**Comment by donshefer** [comment]
There is no "don't kill me" flag and there is no way to block the app from being backgrounded. When the app is backgrounded, the download does still continue unless the app is killed. That is about as much as we can do.
@RPNate1 If you feel it is necessary, we can add a message to the download manage screen that tells them not to close the app while it is downloading.

**Comment by RPNate1** [comment]
Sure. Add a line that says to keep the app open to finish the download.

**Comment by donshefer** [comment]
"Please leave app open during downloads for better performance."
Message added in build 1002

**Comment by RPNate1** [comment]
DOne. build 1002
