### ISSUE TITLE
[Bug] Apple Music widget (skipNext and Play) on Lock Screen does not work properly (at least on vintage phone 6s)

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#265]
## Brief description of the issue:
At least on an iPhone 6s, the Pause and SkipNext buttons on the Lock Screen do not work and are grayed out. See screenshot.
It works at least on: iPhone 11Pro, iPad mini 5 (see screenshots).

### Screenshot iphone 6s

![IMG_0750](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/f4be2306-0915-46eb-b6e4-96f567ddc20e)

### Screenshot iPhone 11 Pro + IPad mini5

![IMG_0021](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/dccfcb36-76fd-4365-a255-f8a942ae618e)

![IMG_0343](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6f685417-a545-4597-b6d2-a5b390fcf1e0)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (89), Oldtimer iPhone 6s, iOS 15.7.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
Question: if you force quit and re-launch the app, do the play controls work again? This is a rare bug, and I have seen it on other devices with no clear cause.

**Comment by ChristianNoc** [comment]
@bradtchapman 
I killed the app and relaunched it and now the play controls are here. I think it’s the first time that I see it on the 6s. I will do some test with the 6s, but I am shifting to an newer iPhone the next days…

**Comment by bradtchapman** [comment]
Good to know.  This has happened to me
less than 1 in a hundred times.  Extremely weird and hard to reproduce.

**Comment by bradtchapman** [comment]
closing as resolved.
