### ISSUE TITLE
[Bug] RP won't stop preloading.  Can't disable it now

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#266]
## Brief description of the issue:
At some point while testing the pre-load and caching features, I enable pre-loading, and now it is always preloading every time I switch stations or the current station's buffer is about to run out.  I cannot seem to turn it off. See attached screen recording.

### Steps to reproduce:
1. not certain, except that I enabled pre-loading at some point.
2. in the screen recording, I am skipping songs via Bluetooth car stereo. 
3. In the video, you may hear some songs repeat the beginning; this could be a separate bug altogether, but it does appear to be new behavior since the caching and pre-loading was adjusted in recent builds.

### Expected result:
I should be able to turn off pre-loading, or this feature needs to be better explained if this is a standard behavior.

### Actual result:
pre-loading happens constantly, and I cannot clear it.

### Where did you see it? (App build version, device type and iOS version):
build 89

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/4a8c8ff7-a70f-4cfe-8465-0e38d3e0248b

**Comment by donshefer** [comment]
@bradtchapman The preload function has changed the way it works. The live streams are always preloaded, meaning the songs are now being download to local files and then played from there. At increments, usually when the end of a song is reached, it will automatically download several songs ahead, up to a limit of about an hours.  The slider now allow you to bump up that cache all at once when you know you will be losing connectivity. So, there is really no way to turn preloading off. It is just the default way the live streaming works now.
You can watch the amount of preload time and see when it is downloading when you have the download manager screen open.

**Comment by bradtchapman** [comment]
The preload is a completely new function in the app that wasn't present in RPv1.  Good design should teach users about the tool without having to explain its use.  The slider may mislead users into thinking they can make constant adjustments to preload.  Lord knows I tried to decrease it and got frustrated.  

- What, practically, is the maximum amount of time a user can preload before the gapless server stops generating new music for a client?  2 hours? 12 hours?
- What **practical** limit do you want to set for the app so users don't waste device space, their data plan, or your bandwidth costs?
- How will you handle a user changing their mind, i.e.: cancelling a mistaken increase in the preload?
- Will you consider adding a warning about Ultra and FLAC that they consume a lot of bandwidth on cellular?
- To differentiate between preload and caching, is the offline function pulling random blocks of music from RP's backend on every request?

**Comment by RPNate1** [comment]
This function is a request of William. We are dialing in the behavior and
what is being shown to the user. Currently, you are seeing under the hood a
bit with the pre-load showing what is actually being cached on your phone
as the normal function of the app. Don and I discussed this today in a
meeting. We're sharing too much in this revision. The cache should be
invisible to the user, not shown in the pre-load. So we are devising the
best way to implement the slight redesign (in the backend) and have it make
sense to the user. Hold tight!
To answer your questions -
1. 2 hrs.
2. The current cache will hold about an hour without a request for more
3. That is something we are working on. The quick fix right now is to
change the channel. The cache then resets.
4. Yes, there will be more explanation of the feature. We'll dial it in
first and then work on how to advise users.

**Comment by RPNate1** [comment]
I missed the last question in my response earlier. Pre-load is the buffer for the live stream, the cached content comes from a block of music two weeks and 8 hours in the past.

**Comment by RPNate1** [comment]
working as intended. Dialing in the functions to match feature request from William.
