### ISSUE TITLE
[Bug] I heard the same song twice back-to-back

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#267]
## Brief description of the issue:
While listening to the Main Mix today, the app played a song, then it played the same song again. It then played the next song, and at the end of that song, it played that second song again.

### Steps to reproduce:
1. Start the app.
2. Choose "sync current channel". 

### Expected result:
Listen to RP Main Mix "synced to channel".

### Actual result:
I heard same song twice.

### Where did you see it? (App build version, device type and iOS version):
Build 90, MacBook Pro M1 Max, OSX Ventura 13.4

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by k00ka** [comment]
Might be difficult to reproduce. I will continue to try doing so to understand how it happened. Perhaps something to do with caching?

**Comment by RPNate1** [comment]
William saw this a couple of days ago. Please go to settings and send
feedback. Include the logs so we can see what happened.

**Comment by k00ka** [comment]
Sorry, app crashes when I choose Send Feedback. I believe I have sent the crash report a few times in the last few minutes. Let me know if you don't get it.

**Comment by k00ka** [comment]
Repeating song thing just happened again. I heard a song, then one other one, then back to the first. I didn't touch the controls during that sequence. If you can fix the Send Feedback for me, I'll capture the logs for you.

**Comment by RPNate1** [comment]
I heard it once today as well and sent logs to @donshefer

**Comment by donshefer** [comment]
Multiple updates to the player logic made to build 91.
Please retest, and if you do hear a repeat, please let me know the user actions the preceded it (if any).

**Comment by RPNate1** [comment]
we'll keep an ear out. closing b92
