### ISSUE TITLE
[FR] Feature Request especially for international listeners: It would be nice if the lyrics could be copied to the clipboard (especially for non-native English speakers who might want to use translation software).

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#269]
## Brief description of the issue:
It would be nice if the lyrics could be copied to the clipboard (especially for non-native English speakers who might want to use translation software).

For me there is no reasonable reason why the clipboard function is disabled in this lyrics window. Especially because it is not a big programming effort (in my opinion).

### Desired result:
It would be great to have a button within the song lyrics windows that puts the whole text into the clipboard. That could be located beside the closing “X”. So it would be easy to paste it to a translation tool.

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
Asked about this today. If it's not a huge deal, we'll implement. Good suggestion considering we have listeners in 135+ countries...

**Comment by donshefer** [comment]
feature added to build 1002

**Comment by ChristianNoc** [comment]
Cool! Thanks a lot. Every other (quality) streamingservice as Qobuz or tidal prevent users within the app to copy even simple text in the clipboard. That’s so ridiculous, because at the win desktop it’s all possible…

Radio Paradise is different :-). 

I will test it as soon it’s released…

**Comment by RPNate1** [comment]
done. Closed b1003

**Comment by ChristianNoc** [comment]
Works very nice!
