### ISSUE TITLE
Bug (b28): CarPlay: disconnecting while playing leaves app in uncertain play state, unable to resume

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#27]
### Brief Summary:

The RP app still has inconsistent play / pause state when using CarPlay, and a fatal condition after disconnecting USB.

### Steps to reproduce:

1. Start an RP stream.
2. Connect to CarPlay, music may continue.
3. Disconnect USB cable.
4. RP app still shows the "Pause" icon as if music was playing, but the stream is paused
5. Press "Pause" ; music does not resume.
6. Reconnect USB cable; music does not resume on CarPlay.
7. Tapping playback controls on car touchscreen has no effect.  8. 

### Expected behavior:

Music should resume fluidly, and the app should also show the grey "play" button if media is paused.

Please compare the behavior in the RP version one app. 

I wonder how much of this is tied to the MPPlayableContentManager vs. the other known playback issues.

**Comment by RPNate1** [comment]
Please check this on b30 @bradtchapman

**Comment by bradtchapman** [comment]
CarPlay behavior is improved.  OK to close this one.  Not perfect, though; I still have outstanding issue but it's a different bug.

**Comment by bradtchapman** [comment]
Yep, working as expected now.
