### ISSUE TITLE
[Bug] b90: Comments button is not right-aligned on some screens

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#270]
## Brief description of the issue:
Starting a couple of builds ago, the comments button shifted away from the right edge of the screen.  Compared to the iPad mini and iPhone SE 1st gen (tiny screen), the iPhone 12 Pro looks wrong.  The right edge of the icon should line up with the right edge of the time remaining; this is still within the safety margin.

### Steps to reproduce:
No steps to reproduce.  Please see attached screenshots.

### Where did you see it? (App build version, device type and iOS version):
Build 90, iPhone 12 Pro, iOS 16.5.1

*(Where possible, please attach Please provide screenshots or error message text)*

I'm also including screenshots from two other devices: iPad mini 6, and an iPhone SE 1st gen.

iPhone 12 Pro (wrong)
![IMG_6270](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9e240db3-5437-4b6c-99a7-0fd9e4abdfad)

iPhone SE 1st gen (OK)

![IMG_0106](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/1c4abbb4-92e7-4759-a3f6-30a2f5e7c1d1)

iPad mini 6:

![IMG_0154](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9e301abe-c9a6-407d-913f-f03efc860eeb)

![IMG_0153](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/38791bc9-4cba-4da7-ad10-b96471290c68)

**Comment by bradtchapman** [comment]
Just noticed that the iPad mini 6 landscape view is slightly off.  Not egregious enough that I noticed it, though.  The MacOS version of RPv2 has similar presentation to the iPad mini.

**Comment by donshefer** [comment]
fixed in build 1002

**Comment by bradtchapman** [comment]
1002?  Did you mean build 93?  Or are you changing the number scheme for betas?

**Comment by donshefer** [comment]
@bradtchapman We have renumbered the builds in preparation of deploying to the app store. Stay tuned and we will push out the new build shortly.

**Comment by RPNate1** [comment]
fixed on my iPhone 11 pro in build 1002. Also looks good in the MacOS version. As well as on my iPad Air on b92.
