### ISSUE TITLE
[Bug] Instructional aides in DL Manager are inconsistently sized, difficult to read on most devices

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#271]
## Brief description of the issue:
The text in the download manager that explains the preload feature is far too small to read on the iPhone SE 1st gen, and fairly small on the iPhone 12 Pro.  It's definitely below Apple's recommended minimum size.  This text on the iPad looks fine.

### Steps to reproduce:
1. No steps to reproduce; text is contained in the DL manager.

### Expected result:
I think it might be simpler to hide the explanation under an info button ( i ) and when the user taps it, a popover explains the whole thing.  

### Where did you see it? (App build version, device type and iOS version):
Build 92 — but this has been happening for many versions now.  I've just decided to file a bug for it.

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0105](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/7a98d3bb-c4b3-4dfc-8187-ea0daa4d2d19)

![IMG_6272](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9eb2d581-cf65-4b77-8fe2-c4b1d27aadb6)

![IMG_0152](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/4bd078ff-d42a-4de1-bcdb-6f2d2017c395)

![IMG_0151](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/88e78f64-159e-4d4e-84f3-3541364b7669)

**Comment by donshefer** [comment]
I tightened up the download manager screen and fixed an issue with SE screen. Should be better now.
Updated in build 1002

**Comment by RPNate1** [comment]
fixed b1002
