### ISSUE TITLE
[Bug] Under certain circumstances the comment button has no function (only from the artist info screen). Possibly a timing problem.

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#272]
## Brief description of the issue:
Under certain circumstances the comment button has no function. Possibly a timing problem. Easy workaround available, see video.

### Steps to reproduce:
1. Play song
2. Go straight to artist info
3. In approximately 5% to 10% the comment button has no function from artist info screen

## Additional information:
I can’t or won’t judge if it's worth to fix it, because the testing effort is also extremely high. I have tested it during a 2 hour listening session to be able to create the videos. 

In my opinion it is some timing problem with the backend server (running in a timeout maybe). In any case it is definitely not a one time occurrence.
@RPNate1 your turn ;-)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (92), iPhone 11 Pro , iOS 16.6

Argh file limit of 10 MB on GitHub for a video. How ridiculous is this?! Videos will follow…

[](https://e.pcloud.link/publink/show?code=kZuBWBZI20cuxBE9t8l7TLMr2qWQzoF0WCV)

https://e.pcloud.link/publink/show?code=kZuBWBZI20cuxBE9t8l7TLMr2qWQzoF0WCV

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
I'm pretty sure I managed to fix this. I can't seem to replicate anymore.
Updated in build 1002.

**Comment by RPNate1** [comment]
seems fixed in b1002
