### ISSUE TITLE
[Bug] Sign In/Create option in popup doesn't work

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#274]
**_Please note, I am reporting here as "Send Feedback" does not work for me._**

## Brief description of the issue:
Nothing happens when "Sign In/Create" is chosen from the popup.

### Steps to reproduce:
1. Log out.
2. Listen to a stream.
3. Try to rate a song.
4. Choose "Sign In/Create" from the popup.

### Expected result:
I would expect to see the login form.

### Actual result:
Nothing happens.

### Where did you see it? (App build version, device type and iOS version):
Build 1003, Version 8.0.0, MacBook Pro M1 Max, Ventura 13.4 (22F66)

*(Where possible, please attach Please provide screenshots or error message text)*
<img width="644" alt="Screenshot 2023-08-03 at 1 17 41 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/05b14606-cb8f-44b5-8766-cad5b1d9ab1b">

**Comment by k00ka** [comment]
Please note: I *am* able to see the login block if I choose Sign In/Create from the profile menu.

**Comment by bradtchapman** [comment]
I just reproduced this in 8.0.0 (1003) and reported it via TestFlight.

**Comment by RPNate1** [comment]
Confirmed!

**Comment by donshefer** [comment]
Fixed in iOS build 1004

**Comment by RPNate1** [comment]
I tried to use it and the login page dismissed before I could use it to login. @donshefer

**Comment by donshefer** [comment]
Fixed in build 1005

**Comment by RPNate1** [comment]
fixed b1005
