### ISSUE TITLE
[FR] Enhancement: load web content off screen and delay rendering until it's done.  Track page load progress with WKNavigationDelegate.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#275]
### Brief description of the suggestion:
Loading comments and other pages from the site can take several seconds, depending on the user's device speed, network connectivity, whether it's hot or cold, already busy doing other things, etc.  This results in a black screen even before the headphones start to animate.  Also, the app appears to be tearing down the WKWebView session every time it loads a new page, instead of keeping it off screen somewhere.

With so much time on a black screen before the headphones load, users will think something is wrong with the app, tap other things out of frustration, and probably take to complaining about it on your forums or flood your email.  In Swift, WebKit has a way to tell your app that it's loading or completed so you can delay on-screen rendering until it's ready to show.  While you track the progress of the page, you can display something else, like a spinner or animating icon, instead of depending on the webpage itself to do that.

https://developer.apple.com/documentation/webkit/wknavigationdelegate

Check out these two properties in particular:

- [`func webView(WKWebView, didCommit: WKNavigation!)`](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455635-webview)
- [`func webView(WKWebView, didFinish: WKNavigation!)`](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455629-webview)

### Steps to reproduce:
1. Pick the slowest / oldest device you have.
2. Connect to a cellular network or wireless network that yields performance of <10 Mbps and >100ms latency.   (The Apple developer tools have "network conditioner" tools in Xcode that can help with this).
4. Start playing one of the stations.
5. Tap any item in the app that would load a web view, like comments, or one of the menu items that leads to the web page or the blog.
6. Go back to Simple Mode.
7. Repeat step 5 with something else, or the same thing.

### Where did you see it? (App build version, device type and iOS version):
Pretty much every build of this app.

I'd suggest a way to minimize the delay *ASAP* before you get out of the TestFlight program with your 100+ testers.

**Comment by ChristianNoc** [comment]
@bradtchapman 
In my opinion it’s a very good idea. The app is very functional now but for normal users it can be very confusing to see just a black screen for seconds… even the animated headphone logo appears sometimes very delayed… I can't estimate how much effort that suggested improvement would be.

**Comment by RPNate1** [comment]
We may look at implementing this in a test version after launch and see if it makes a difference. Will leave open but ignored for now ;)
