### ISSUE TITLE
[Bug] My Favorites doesn't show up in channel list after logging in

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#276]
## My Favorites doesn't show up
After logging in, the channel lust doesn't refresh so My Favorites doesn't show up in the channel selector.

### Steps to reproduce:
1. Open app and login.
2. click on channel selector and look for My Favorites.
3. It isn't there.
4. Close app.
5. Reopen and My Favorites has now appeared in channels.

### Expected result:
Channels would update after login, showing My Favorites

### Actual result:
Had to restart the app to refresh channel list to get My Favorites to show.

### Where did you see it? 
b1001, several different devices from testers

**Comment by donshefer** [comment]
fixed in build 1004

**Comment by RPNate1** [comment]
fixed. b1004
