### ISSUE TITLE
[Bug] Fries navigation/webview navigation doesn't always work

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#277]
## Brief description of the issue:
Trying to navigate between web view pages in the fries navigation or profile pages doesn't reliably work

### Steps to reproduce:
1. Open any page on website in fries navigation 
2. try to navigate to another page on the website through fries or profile pages
3. can't access any other pages through navigation.
4. return to Main player screen and select fries navigation again
5. navigation works

### Expected result:
navigation should work between any web view pages through fries navigation or profile every time

### Actual result:
Sometimes navigation doesn't work at all requiring a return to main player screen to then navigate to another web view page.

### Where did you see it?
b1001, my 11pro, and reported from Greg Lawler, Corina Wolfer, Duane Constantinoff, and Andrew  Blunsden
there are a couple logs sent to examine

**Comment by donshefer** [comment]
I believe this is fixed in build 1005

**Comment by RPNate1** [comment]
fixed 1005
