### ISSUE TITLE
[Bug] The time delay between pressing the play button and the graphic display of the orange pause sign is too long (up to 3 sec.). The status text display "playing" does not have this delay. 

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#278]
## Brief description of the issue:
The time delay between pressing the play button and the graphic display of the orange pause sign is too long (up to 3 sec.). The text display "playing" does not have this delay and is displayed with the start of the playback.

### Expected result:
With the start of the playback the Button control should be updated immediately as the change of the text status. 3 sec later is not acceptable.

### Where did you see it? (App build version, device type and iOS version):
1005, iPhone 11 Pro, iOS 16.6

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/2a30937c-6ca5-427b-9c2d-497af8dd9dd1

**Comment by RPNate1** [comment]
Changing.

**Comment by donshefer** [comment]
Updated in build 1007

**Comment by ChristianNoc** [comment]
@donshefer Thanks! Works perfect now. Just tested on one device iphone11 pro but that should be not depending on the device.

**Comment by ChristianNoc** [comment]
Fixed.
