### ISSUE TITLE
[FR] Activating the standard iOS context Menu within the lyrics window

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#279]
## Brief description of the issue:
Especially for international listeners the new copy all button within the lyrics text window is a cool thing. It would be really helpful if the iOS standard context menu would be also working within the lyrics windows: When you tapp longer on a text item normally the standard context menue appears with the translate feature (as working on the artist info view): And there it’s easy to translate just one word or a sentence without switching to an other translation app. I know that such a feature will be very helpful and appreciated for international non English native listeners (beside the copy all button).

@RPNate1 I have also sent you an email about this additional feature.

![image0](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/53b9dcef-c355-4371-a77f-33030f6687ed)

### Where did you see it? (App build version, device type and iOS version):
Build 123, iPhone 13 Pro Max Ultra+, iOS 16.X.X

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
I'm gonna have to put this on the back burner for now. The app is going o get launched and we are out of budget! However this is a great idea... we'll include it in a future updat.

**Comment by ChristianNoc** [comment]
Back burner sounds great, I like that. For me the app is now in perfect shape and is fully packed with real cool smart features with great RP design. No commercial music apps (at least as I know) has such features. The app reflects now the RP quality and signature. I know that especially new listeners will see and will love that…
