### ISSUE TITLE
Bug (b28): CarPlay: after tapping a mix, the screen slides to now playing screen, then immediately jumps back to the station list. 

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#28]
I am in my car, so dictated notes will have to suffice for this ticket.

### steps to reproduce:

One. Connect device to car.

Two. Launch Radio Paradise app and start playing a stream.

Three. Tap any one of the mixes from the station list.

Four. Observed that the screen slides to the NowPlaying view, then immediately snaps back to the station list.

five. Repeat steps three through four ad nauseam.

**Comment by bradtchapman** [comment]
@donshefer @RPNate1 : this has been open for 3 builds and 5 days with no action.  Any chance you can look at it?

**Comment by RPNate1** [comment]
Don and I had a meeting last week where we discussed CarPlay and the need to update the implementation. We will make sure that the CarPlay issues are sussed out. It sounds like updating will solve a lot of the known issues.

**Comment by donshefer** [comment]
CarPlay has been reimplemented with modern frameworks.
Targeting build 36

**Comment by bradtchapman** [comment]
Yes, this is fixed in build 36.  It also shows the album art blurred in the background, too, which is pretty cool.  I went back and forth to different channels as a test.  Totally smooth.  

Thanks @RPNate1 and @donshefer !
