### ISSUE TITLE
[FR] A Last Feature Request to make it round

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#280]
## Brief description of the issue:
The new help screen of the download manager is really really helpful (for new users) because even for me it took me a lot of time to use that feature in a good way.
A psychology teacher told me that when a seminar he gave (for me a project or what ever) ends his feeling must be round. Like a bell that should sounds nice when it’s ready. And for me a little thing is missing within the app to make it perfect round. Sorry @RPNate1 for another FR ;-).
Since the download manager has now a help screen the main interface needs a short help screen with the icon legend and hints like swipe down to close and of course the text copy feature for translation of the lyrics. That all must be explained for new users within the app. It’s important for the users to see all of that features immediately when they start to use the new app. Not all have so much or are willing to take so much time to explore all features. And some feature are really unique and haven’t seen in commercial music apps. Maybe it will be enough as a web view pointing to the website but it needs a menu point within the app. As simple as possible.

### Where did you see it? (App build version, device type and iOS version):
Build 123, iPhone 13 Pro Max Ultra+, iOS 16.X.X

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
We'll get a legend page done...

**Comment by ChristianNoc** [comment]
Cool 😎

**Comment by RPNate1** [comment]
making closed 1008
