### ISSUE TITLE
[Bug] Build 1007: song info bar disappears when visiting any web content, including Comments; user cannot tap to go back to simple mode as before build 1007.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#282]
## Brief description of the issue:
Build 1007 unexpectedly removes the song info bar when visiting any content that loads a WebKit view, such as the blog or the song comments.  

### Steps to reproduce:
1. Start any stream.
2. Tap Comments.
3. Song info bar disappears.

### Expected result:
Song info bar was present in build 1005 and earlier.  This is new for 1007.

### Workarounds:
These are unintuitive, but they do work without interrupting music playback:
1. Tap the station list, then tap the current station.
2. Tap kebab menu, click (i) info button.

### Where did you see it? (App build version, device type and iOS version):
Build 1007, iPhone 12 Pro, iOS 16.5.1 (c).

**Comment by bradtchapman** [comment]
![IMG_6425](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/99a8fe8f-c180-48e3-b0b2-605cfa84cf56)

**Comment by bradtchapman** [comment]
Updated "Workarounds" comment to indicate two workarounds that don't interrupt music playback.

**Comment by bradtchapman** [comment]
Nevertheless, this is an unexpected change and freaked me the heck out!

**Comment by RPNate1** [comment]
This is a bug. No bueno. @donshefer

**Comment by donshefer** [comment]
Oops. =)
Fixed in 1008

**Comment by bradtchapman** [comment]
OK.  Waiting for 1008 to hit TestFlight...

**Comment by ChristianNoc** [comment]
Tested with iPadmini 5 and iPhone 11 Pro: 
Fixed with 1008

**Comment by RPNate1** [comment]
closed 1008
