### ISSUE TITLE
[Bug] back link not working (cosmetic issue webview)

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#283]
## Brief description of the issue:
There is an option to display the website within the player app. In my opinion not necessary and make it just complicated. When I want to visit the website I prefer it to open it in safari or be redirected to safari and not in the app. But anyway, the link for back is not working. For me not really important… see video… klicking on the back link makes it just disappear 🫠 and nothing more. I would fix it with redirecting to safari… 

https://e.pcloud.link/publink/show?code=XZrYvBZ382woaHqqJ8eXcFzjuoXbHO90p3k

### Where did you see it? (App build version, device type and iOS version):
Build 1007, iPad mini 5, iOS 16.6

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
William wanted the whole website available. We will fix that bug...

**Comment by ChristianNoc** [comment]
Ok I am fine with it, good to know because then I will test it haven’t tested it yet. 
The funny thing is that sometimes there is no back link at all… and when it’s there it’s not working properly…

**Comment by donshefer** [comment]
The back button should only appear when you have clicked on a link in the
web view.
There is a bug, which I’m working on, that shows a back button even though
the page back is the same page you are on.

**Comment by ChristianNoc** [comment]
Ah I thought it’s a kind of a breadcrumb navigation… back to the last player view that would be useful for me…

**Comment by donshefer** [comment]
updated in build 1008

**Comment by ChristianNoc** [comment]
@donshefer 
It looks like it’s working except on one page, the channel page because you have the navigation element at the top of the page, the channel selector and you don’t need that back button there. But I don’t know if you can turn it off for individual pages.

![IMG_0582](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/1a996a09-49e8-4927-8d72-0ddc591eab9c)

When u use the back button you came at the end to the „main mix“. The technical function is 100% ok but in my opinion the back button makes no sense there. But that’s exactly why I don’t like and won’t use the webview for normal pages when listening.

@RPNate1 
Please check because I can’t judge if that is what it should be for that particular page. The technical function is 100% ok now in my opinion. To make exceptions for single pages makes it quite complicated and I wouldn’t do that. I would close that issue. Your decision what to do, I can’t.

**Comment by RPNate1** [comment]
This works. Closed 1008

**Comment by ChristianNoc** [comment]
@RPNate1 
I just want to say that I changed my mind after playing around with the integrated web view. It's not so bad that it's integrated into the player. I'm surprised myself at my change of mind. I just wanted to let you know.
