### ISSUE TITLE
[FR] Build 8.0.0/1007: Kebab may not be necessary on Mac app anymore due to adequate space.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#285]
## Brief description of the feature request:
Due to changes in the app layout for macOS, it doesn't seem necessary to hide two icons under the kebab menu.  Maybe it's time to move the "Sleep Timer" and "Downloads" onto the bottom right corner, and remove the kebab?  I evaluated this in both tall and wide views and produced a mockup (see below).

### Where did you see it? (App build version, device type and iOS version):
Build 1007, macOS 13.4.1 (c)

*(Where possible, please attach Please provide screenshots or error message text)*

![RP-1007-nokebab-tall](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/0aace959-68b3-4dd8-82cf-2d7f828cfa7a)

![RP-1007-nokebab-wide](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/a4a11309-fc25-4aca-85ab-0eb0b8b36cd6)

**Comment by RPNate1** [comment]
We're gonna leave the kebab and functions there. It'll give us expansion room.

**Comment by bradtchapman** [comment]
Understood.
