### ISSUE TITLE
[Bug] Cannot access complete song info page (web view) of current song from Play History—or from any app button, for that matter.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#286]
## Brief description of the issue:
In List View, I can select **previously-played songs** and view the extended song info... but I cannot do this for the **current** song at the top of the list.  Tapping the album art for the first song in the list always goes back to **Simple Mode**.  

What should someone do if they want to have the experience of viewing the extended song info like they can on the website?  Currently you have to take 3 different routes to get the lyrics, comments, and artist info from wikipedia.

This affects ALL platforms (iOS, iPadOS, macOS).

### Steps to reproduce:
1. Load any station, any song.
2. Tap Kebab > Play History.
3. Tap the current song at the top of the list.
4. App switches back to Simple Mode.
5. Tap Kebab > Play History.
6. Tap any other song in the list.
7. App loads the extended song info, and now shows a history breadcrumb to go back to the history view.

### Expected result:
I would love a way to access the extended info for any song, even the Curren tone.  By the same token... if Extended Song Info because the default choice when tapping a song from History View, how would a user go back to Simple Mode?  

### Workarounds:
Currently, there are two ways to get back to Simple Mode: 
1. Tap the RP headphones at the top of the screen.
2. Tap the Song Info bar.

Currently there is one way to load the requested song info: skip the current song, then go back to Play History and tap the song you wanted to read about.

### Where did you see it? (App build version, device type and iOS version):
Build 1008, iOS 16.5.1, iPhone 12 Pro
Build 1008, MacOS 13.5

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
There isn't a way to do this. We did have the extended info available in one scrollable webview page (song page) but this broke the app during network issues or offline. That is why we implemented the simple view. Allowing us to display the album image and lyrics at the least, and then let the user know they can't see comments or artist info without a connection. This make it work better for the DL blocks as well. It's a compromise.

**Comment by bradtchapman** [comment]
To clarify: the long scrollable web view is reachable for other songs, just not the current one.  

If I recall, there were a lot of times when the page would jump back and forth while listening to the song.  It was connected to the "locked" and "unlocked" state of the list, which wasn't ordinarily visible on an iPhone that can only show one pane instead of 2-3 like the iPad or a computer.  Is this why the view was scrapped for the current song?

**Comment by RPNate1** [comment]
Yep They are. But...not offline. The offline playback with some info
available was the goal. It's easy to tell a user they can't see songs from
history, comments, and artist info while offline. It's no good to tell them
they can't see anything when offline. Making it act consistent (for the
most part) no matter what the network state was key.
