### ISSUE TITLE
[Bug] The download manager is not listed in the new app legend...

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#289]
## Brief description of the issue:
The download manager is not listed in the app legend...but it should be because it’s a USP or in less business Blabla it’s a killer feature. 

Suggestion:

„Download Manager: various ways to listen offline when you are on the go“

### Where did you see it? (App build version, device type and iOS version):
Build 1011, * , iOS 16.6

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by donshefer** [comment]
The Download Manager wasn't listed because it doesn't have an icon.
@RPNate1 Do you have a suggestion?

**Comment by ChristianNoc** [comment]
@donshefer 
Oh at least in the app it has an icon, dont know where it comes from. I spent so much time with testing that the app even appears hunting me in my dreams *lol*, I really will be happy when its released because otherwise it will not stopp...

![IMG_1188](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/9f19222e-74d1-470e-8482-83238891660e)

**Comment by donshefer** [comment]
@ChristianNoc You are totally right, I forgot about that one. I will add it.
Thank you.

**Comment by donshefer** [comment]
updated in build 1012

**Comment by ChristianNoc** [comment]
Fixed now. Thanks!
@donshefer 
What means "removed bang from download button", I have no idea what this should be? Anyway I close that issue.
