### ISSUE TITLE
Bug (b28): CarPlay: station icons randomly disappear and reappear

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#29]
I am driving, so this dictated notes will have to suffice for now.

### StepsToReproduce

I think the title says it all. Just stay on the station list, and tap stations randomly, waiting until the music loads before selecting another one. 

The custom icon, the Radio Paradise headphones, randomly disappear and reappear next to the station names.

**Comment by RPNate1** [comment]
Curious about this one. Have you checked on the newest builds? @bradtchapman 
Don is going to update the CarPlay implementation, so if they're not fixed now, hopefully, they will be then.

**Comment by donshefer** [comment]
CarPlay has been reimplemented with modern frameworks.
Targeting build 36

**Comment by bradtchapman** [comment]
Yep, this is also looking great in the new CarPlay interface.  Thanks @RPNate1 and @donshefer !  The animated frequency bars are also showing when music is playing. 

I see four icons, one for each mix:

- Main: headphones
- Mellow: close up of a person in a red shirt strumming a guitar
- Rock: an electric blue stylized rendering of a guitar, oriented sideways
- Global: close up of a man playing a percussion instrument, possibly a djembe

**Comment by RPNate1** [comment]
We need to update the icons for the channels. There are new tiles. I'll get them to Don.
