### ISSUE TITLE
[Improvement] BuildInHelpScreen: "choose your RPexperience" should be linked to the channels webview to attract new users and show them the music menu

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#290]
## Brief description of the issue:
I have learned that William @BillGoldsmith wants more listeners and I think my suggestion could be a little helpful especially for new listeners and users of the app. I think its important to use all options to attract them and lead them to the RP.Experience directly from the app build in help screen.

1. The Channel is the connection to the radio paradise experience, visualized with the color (that is connected with the headphones). Ok thats not new.
2. The Sentence (at least **"YOUR RP musical experience"**) in the Legend (means built in help screen) has to be visual connected with this means the color have to be gold. In business language I would say its a call to action and motivate the users to do something with that colored item in the next step 3. 
3. The Sentence (**choose your RP musical experience**) has also to be connected with a link to the web view of the Channel Screen. New listeners are hopefully attracted by the content and thats important. Especially with the new upcoming channels.

### Slide Show
![IMG_1186](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/d086178d-220a-4cfe-a49e-e8f86793d454)

![IMG_1185](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/32d7a475-f5ce-474f-9ae9-31f988e92010)

![IMG_1187](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/6b94c536-ab08-4d85-b16d-46b73bb1d385)

### Expected result:
@donshefer Hi Don, in my opinion this is technical just a simple change, paint some text in gold and add a link. Am I right? More time consuming could be to make the decisions with the team. @RPNate1 No worry I have not much suggestions left at the moment ;-). I will be happy as soon as the app is released. It's quite perfect now.

### Where did you see it? (App build version, device type and iOS version):
Build 1011, * , iOS 16.6

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
I like it, but it didn't make the cut.
