### ISSUE TITLE
[Bug] API: missing album year is displayed differently in simple mode vs. history / extended song view on web.  Just use "Release Date" ?

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#291]
## Brief description of the issue:
There were two songs in a row on the Main Mix that had empty / missing album year.  However, the "release date" was populated.  There must be two different fields in the database for release date.  Can't this be derived from the release date and only show YYYY ?

See attached screenshots.  The two songs were showing "Album Name ()" in Simple Mode, but 

### Expected result:
Album year sent via the playback API to the app should derive the year from the Release Date that already appears to be in the database.  Don't duplicate your data if you don't have to.

### Actual result:
In Simple Mode, the album year is missing () but in History view, it shows (0). 

### Where did you see it? (App build version, device type and iOS version):
Build 1011, iPhone 12 Pro
Build 1008, MacOS

This is not an app issue, but an API / database issue.

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
These screenshots are taken from the Mac, but the issue looks the same on iOS.  Since this affects multiple builds, it's probably not specific to the app.  However, the issue *could* be rectified quickly in the app if it were given the Release Date from the API, and the app transformed the received date into YYYY format in the album field.

<img width="359" alt="Screenshot 2023-08-21 at 10 30 41 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/77ed14fd-0dda-4ff8-8baf-1b4ebc593d07">

<img width="319" alt="Screenshot 2023-08-21 at 10 30 57 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/d96b9941-61b1-46de-b6a7-c5f1d370d7cc">

<img width="234" alt="Screenshot 2023-08-21 at 10 31 16 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/8d331179-6bae-49af-aa1f-078dfbecb4c1">

<img width="230" alt="Screenshot 2023-08-21 at 10 31 03 AM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9668d249-80c0-4000-b3c8-e11a73a22be0">

**Comment by ChristianNoc** [comment]
Yes I have seen that (0) too, but thought there is an database error somewhere…

**Comment by ChristianNoc** [comment]
…or the app should not show a string like this (0) because than it’s oblivious that’s an error. *lol* that would be my solution…

**Comment by donshefer** [comment]
I updated the main display and local play history to hide the "()" when there is no song year.
One of the included screen shots is of the play history webview. That will have to be changed on the server.
Update in build 1014.

**Comment by ChristianNoc** [comment]
@donshefer 
Don’t know how to test this issue…
