### ISSUE TITLE
Download manager.

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#292]
Just some minor things from listener emails.

- Download manager doesn't retain your bitrate setting.
- The download length slider is too short.  Should be 10 hours.  Especially since the download manager is single threaded.  Downloading a few days of music is very tedious.

**Comment by RPNate1** [comment]
@donshefer  in the next big revision let's extend the slider to the 10 hours. We should probably have a warning pop-up to keep the app open for anything over the 2 hour mark as backgrounding the app seems to bork some downloads.

**Comment by donshefer** [comment]
updated in v8.1.0 build 1021

**Comment by RPNate1** [comment]
fixed 8.1
