### ISSUE TITLE
accessibility 

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#296]
I'm a long-time RP listener and supporter. Congrats on the new app which downloaded to my iPhone and iPad Saturday night. 

 

I am blind, so I use Apple's built-in screen reader VoiceOver. Several years ago, you fixed a problem which prevented me from deleting blocks of audio from the download manager, for which I'm very grateful, as I frequently listen off-line. Now I'm having problems navigating the new app because many of the buttons, on the main screen and elsewhere, are labeled incorrectly or not at all. These aren't show-stoppers, but they do make the app frustrating to use. A few examples:

 

The button to access listen, music, about, swag, etc. is labeled "fries".

 

The menu containing timer, download, carplay etc. is labeled "Kebab-80".

 

The button to skip to the next song is labeled "Go To Start".

 

The button to bring up the play history is labeled "list-mode-80".

 

Also, in account settings, when choosing listening bitrate (low, high, ultra) VoiceOver is not reporting which choice is checked. Fortunately, these check boxes are working properly in the download manager.

 

Hopefully, these issues can be addressed as time permits. I'm happy to assist with testing any new builds.

 

Best regards.

 

Steve Bauer

[stevebauer@samobile.net](mailto:stevebauer@samobile.net)

**Comment by donshefer** [comment]
This is an important addition. I am working on it.

**Comment by ChristianNoc** [comment]
@donshefer 
That’s really an important issue. I have not tested that during our tests because I do not know where I can see that internal labels. I know from webprojects and SEO that additional labels are very import for accessibility. Where can I see that alternative text labels? It would be important for me to know where I can see and check this.

**Comment by donshefer** [comment]
@ChristianNoc You can test using VoiceOver.
https://www.youtube.com/watch?v=qDm7GiKra28
v8.0.3 build 1019 will have the accessibility buildout.

**Comment by RPNate1** [comment]
Thanks, @donshefer

**Comment by donshefer** [comment]
updated in v8.1.0 build 1021

**Comment by RPNate1** [comment]
fixed 8.1
