### ISSUE TITLE
apple watch

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#297]
Getting some complaints about this no longer appearing.

**Comment by jarro** [comment]
I've had the radioparadise app on my apple watch for several years. Suddenly  2 days ago it disappeared, and while I have the RP app loaded on my iphone, radio paradise no longer comes up as an app listed on the available apps to install on my watch app.  Any suggestions?

**Comment by jarro** [comment]
Watch support removed from latest (v 8.0) IOS app?  I'm hoping it comes back, I used it everyday.

**Comment by donshefer** [comment]
The watchOS work is done and being tested.

**Comment by k00ka** [comment]
Happy to give it a trial run once ready.

**Comment by RPNate1** [comment]
Notes on how to use the RP watch app.

* Make sure you have a version of the app that includes the Watch code,  Only v8.1.0 and above include the watch app
* You need to make sure the app is loaded  onto your watch. You do that through the Watch app.
* On the phone, download a block of music in the Download Manager
* If you have your watch all set up and nearby, you should see a watch icon appear next to the download in the download manager.
* Click on that to initiate a transfer of the data to the watch.
* It is best to have the watch near and the Radio Paradise app open on the watch. It does work in the background, but seems less reliable.
* Once the transfer is complete, the download removes itself from the phone.
* You should now be able to play the songs on the watch without the phone.

**Comment by k00ka** [comment]
I don't see the app in my watch app. 
Perhaps watchOS 6 is required for this to work? My watch won't update past watchOS 4.3.2 (currently).

**Comment by donshefer** [comment]
The RP watch app requires WatchOS version 9.0 and is compatible with any watch going back to Series 4, which was released 2018. They have made a lot of updates since then to WatchOS and we are using a lot of API released in WatchKit in 6.0 and 9.0.

**Comment by k00ka** [comment]
Yes, so my watch is no good. Then I could only do testing with the watchOS simulator.

**Comment by RPNate1** [comment]
Everyone who has a watch needs to give this a solid testing.

**Comment by donshefer** [comment]
WatchOS app is now available in v8.1.0 build 1020

**Comment by RPNate1** [comment]
fixed 8.1
