### ISSUE TITLE
lock screen controls

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#298]
The lock screen controls FF/pause/play and volume are no longer active.

**Comment by donshefer** [comment]
I'm going to need a little more detail than that. 
Screen controls seem to be working for me in all configurations.

**Comment by ChristianNoc** [comment]
@donshefer 
I cannot confirm the behavior. It works perfectly on all my devices.

**Comment by donshefer** [comment]
Yep, I have not been able to replicate this issue either.

**Comment by RPNate1** [comment]
Fixed
