### ISSUE TITLE
CarPlay: mystery ellipses in upper right corner when "Bold Text" is enabled in iOS

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#3]
When a user has "Bold Text" enabled in Display / Brightness settings, some apps will truncate text labels to ellipses.

One such example is in the CarPlay interface for RPv2, top right corner.   See attached screenshot.

![unnamed](https://user-images.githubusercontent.com/32527656/214672725-9c7fe702-ee37-469e-80a9-47c7bda27b71.jpg)

**Comment by donshefer** [comment]
This issue also exists in the current iOS app's CarPlay implementation. I have to admit, I have tried and I have not found a solution to this. I will keep digging.

**Comment by RPNate1** [comment]
maybe updating the Carplay implementation will fix this. I'll close and let's see if it reappears when it's updated.
