### ISSUE TITLE
Bug (b28): Song info view shows full page, resulting in duplicate controls and info band

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#30]
### Description

On launch after idle, the info viewer is still intermittently loading the full control set so that I see two sets of playback controls and an info bar on screen.

### Steps to reproduce

1. Launch RP and play a stream.
2. Pause it by starting music in another app.
3. Wait a while until RP has been put to sleep by the OS.
4. Relaunch RP.
5. Press Play to continue the existing stream.

### Workaround

Tap the info band in the RP app.  This induces a refresh in the info viewer and the expected embedded view appears.

See attached screenshot.  

![CCC0B173-2B36-407E-BFA0-E1693A94BDA7](https://user-images.githubusercontent.com/32527656/216354030-f13678b4-5394-4c56-a543-c897f57b0d9c.png)

**Comment by donshefer** [comment]
I tried and and i have not been able to replicate.
@bradtchapman How long did you leave the app in the background? Are there any other steps?

**Comment by RPNate1** [comment]
I've tried recreating this bug. No luck in b31. Closing
