### ISSUE TITLE
[Bug] Sync is inconsistent

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#300]
## Brief description of the issue:
I was attempting to sync to the current channel, but each time I do I end up in a different song

### Steps to reproduce:
0. Sorry to keep harping on this one!
1. Start app
2. Choose sync to channel
3. Choose sync to channel again

### Expected result:
Same song would continue within a few seconds of where it was when sync was chosen

### Actual result:
Random jumping around, sometimes to the next song or two (earlier it worked like "jump to next" for 5 or 6 songs before returning to the first).

### Where did you see it? (App build version, device type and iOS version):
Build 1015, iMac Pro M1 Max, OSX Ventura 13.4

*(Where possible, please attach Please provide screenshots or error message text)*
I captured a movie.

https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/d9787542-c92e-4ea8-a410-8acb86c63df7

**Comment by k00ka** [comment]
Near the end of Wilco is where the video starts. This is the correct location.
I choose another channel, then go back.
I land in the centre of a song (it turns out, it was to be the song 2 songs later in the mix) by King Crimson.
I resync the song and it correctly lands near the end of Wilco and the moves on to the next song in the mix (Martyn Bennett).
After that song, King Crimson played.

**Comment by donshefer** [comment]
Yeah, I confirmed this is happening when jumping around quickly between stations. When jumping to a new channel while still loading, it gets off the sync.
I will try to mitigate.

**Comment by RPNate1** [comment]
Great. Glad we know what’s going on.

**Comment by donshefer** [comment]
updated in v8.1.0 build 1021

**Comment by RPNate1** [comment]
fixed 8.1
