### ISSUE TITLE
[Bug] Loud pop when quitting the app

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#301]
## Brief description of the issue:
When quitting the app, a loud pop is heard.

### Steps to reproduce:
1. Start the app
2. Quit the app

### Expected result:
A quiet ending.

### Actual result:
A loud "pop!"

### Where did you see it? (App build version, device type and iOS version):
Build 1015, MacBook Pro M1 Max, OSX Ventura 13.4

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by k00ka** [comment]
This is maybe more of a nice-to-have.

**Comment by RPNate1** [comment]
I have never experienced this...

**Comment by donshefer** [comment]
Yeah, I've never heard this happen either. I'm not sure we can do anything about it.

**Comment by k00ka** [comment]
It doesn't happen often. I'm supposing the way the app is torn down might cause a less graceful exit from the audio driver. It might not happen if the stream is paused before teardown. It may not be worth the effort.

**Comment by ChristianNoc** [comment]
@RPNate1 
I've never experienced this with the RP.App (only tested on mobile devices and - this may be crucial - without cable connection only bluetooth), but I'm not really surprised that it can happen: After all, there are some technical rules, and they apply to any audio output devices. In the past, of course, you did not turn off any audio device with the power plug, that also gave nice effects (sometimes), or no one would think of wiring boxes with the amplifier on (Well at least once it works :-)). OK we are talking about software here but in the end the audio signal looks the same.

@donshefer 
Do you have the possibility to execute a "Music Stop" followed by a little delay as the very last things before the app is killed by the Task Switcher, is there such a trigger? That would be at least from the RP.APP a clean technical solution. But still no guarantee that this will help....
