### ISSUE TITLE
[FR] Enhancement Download Manager: Adding blocks by swipe right

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#302]
## Brief description of the issue:
I am not 100% satisfied with the download manager and the auto-fill function.
It looks like the refill starts when only 20% of the blocks are left. The auto-refill function is nice, but for me it seems inflexible.

I have an additional idea:
**Now I can delete downloaded blocks by simply swiping left. I would like to have a function to manually add blocks with a swipe to the right. Then a simplified add blocks screen would open with only the time setting and auto-refill switch or maybe better just add 3 hours with the previous settings of the block.**

The purpose is to allow me to easily add blocks as needed if I know in advance how long my trip will take. The auto-refill feature is nice, but it seems inflexible to me.

So I could create the channels I want once as a kind of template in the quality I prefer and then just add blocks. Everyone will probably prefer a quality for the favourite channels, and that would make it easier to use.

### Where did you see it? (App build version, device type and iOS version):
Build 123, iPhone 13 Pro Max Ultra+, iOS 16.X.X

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
This is not a terrible idea

**Comment by ChristianNoc** [comment]
@RPNate1 
What a nice understatement, Im know sometimes my ideas are really brilliant *lol*.

The iOS system stands for me for great usability (at least many apps are designed in this way) and for me it would be logical to add blocks in this way.

**Comment by ChristianNoc** [comment]
@RPNate1 
I changed my mind. Even though my idea is not bad it’s also not necessary. It’s perfect how it is.
