### ISSUE TITLE
[Cosmetic?] Turning on button shapes shows menu entries underlined

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#303]
## Brief description of the issue:

When you enable the button shapes, the menu items are underlined. I don't know if this works as it should. To me, the underlined menu items don't make sense. But that's not really an issue when you use app-specific settings with button shapes disabled…

![IMG_1328](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/00bc5091-f268-4713-a0e2-9c48f8c85b08)

![IMG_1329](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a052482f-b399-41ca-a36d-cf876dd72fbe)

### Where did you see it? (App build version, device type and iOS version):
Build 1022, iPhone 11 Pro, iOS 16.7

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
This is far more desirable than the shapes that messed the format/display up

**Comment by RPNate1** [comment]
closing

**Comment by ChristianNoc** [comment]
Yes definitely! It’s even nicer with a specific rule for the radio paradise app without shapes.
