### ISSUE TITLE
[Bug] Download Manager: After the requested download is completed, the screen will stay on forever until the battery runs out.

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#305]
## Brief description of the issue:
In order for the download to complete successfully, it is necessary and recommended to keep the Download Manager open. So far so good. However, once the download is complete, it is not necessary and counterproductive for the Download Manager screen to remain fully active. That’s just annoying.

### Where did you see it? (App build version, device type and iOS version):
V8.1.0(1025), iPhone, iOS 16.7

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment]
@RPNate1 : confirmed with an iPhone on "Low Power" mode, which should always put the display to sleep after 30 seconds.  It doesn't do that on the Download Manager. 

@donshefer appears to have added a "sleep assertion" to keep the display awake on the download manager screen.  This assertion should ONLY be activated when there is an active download, and the assertion should be released as soon as the download is completed.
