### ISSUE TITLE
Feedback / Unexpected (b28): Song Info view not updating when next song plays

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#31]
### Description

The info viewer is stuck on the last song and not updating like RPv1.

### Question

1. Is this expected behavior, like avoiding an accidental refresh while people might be interacting with comments or other info?

2. Do you have a plan for a user to choose a more "passive" listening experience, where the info viewer only ever shows the song info and album art and updates itself automatically?

**Comment by donshefer** [comment]
@bradtchapman  Yeah, this is a known issue. Jarred made some changes and I am still implementing them on my side. Please check build 29 for updates on this.

**Comment by bradtchapman** [comment]
My only concern is about what happens when someone is reading comments from the previous song and the RP app suddenly refreshes as the song changes. 



—Sent from my iPhone

**Comment by RPNate1** [comment]
If you are scrolled, it will not refresh.

**Comment by RPNate1** [comment]
To follow up on this one. #2 specifically. If a user isn't interacting with the player, ie scrolling/scrolled, the content will always auto-update.
