### ISSUE TITLE
[Bug] Radio2050: Back Button not working properly

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#312]
## Unusual behaviour of the back button - not working as expected

EVERY playback device I know with electronically controlled buttons (sorry for the awkward expression, I mean ALL playback devices from cassette players to CD, Blu-ray players and software players) have a standardized operating concept for the Next and Back buttons. The back button jumps to the beginning of the current track when pressed once and to the previous track when pressed twice. This makes sense and everyone will know and expect this behavior.
In the current app version, the back button only jumps to the beginning of the current track. There is no double-click function.

For me, this is a clear malfunction and there is no reason why the button should not have the usual functionality here: Single touch -> beginning of current track, double touch -> previous track.

Just my opinion.

### Where did you see it? (App build version, device type and iOS version):
iOS v8.2.0 build 1044

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0616](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/5138d02b-e853-420e-86c3-1e5ccc79bc6c)

**Comment by RPNate1** [comment]
I agree that this is the expected behavior.  Replaying is a tricky thing when dealing with the licensing agreements which is why I believe this choice was dictated.

**Comment by RPNate1** [comment]
Closing as this is the designed behavior
