### ISSUE TITLE
[Bug] Radio2050: Episodes not in order: Navigation with skip next is difficult

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#313]
## Brief description of the issue:
Radio2050: Episodes not in order: Navigation with skip next is difficult because after episode 1 comes not 2 as expected. If you need more information pls send me a message…

### Where did you see it? (App build version, device type and iOS version):
1044

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
There appears to be a misnumbering in the API. This will get fixed and then they should play in order.
