### ISSUE TITLE
[Bug] Radio2050: Episode counter shows different values in Download Manager and Information Screen…

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#315]
## Brief description of the issue:
Episode counter is different in Download Manager and Information Screen… 
Let’s work it out is in DM numbered with 11; in Information screen with 6… that’s a nogo.

### Slideshow
![IMG_2348](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/a9b0ba83-5a0f-4932-bdec-8456823fd87a)

![IMG_2347](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/8520120e-6095-4ccd-b308-6b0142b0a5c5)

### Where did you see it? (App build version, device type and iOS version):
1044

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
We are sussing out where this is pulling the episode number for downloads. It will match.
