### ISSUE TITLE
Suggestion: limit "ultra" and "flac" to signed in users only.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#33]
This is a business decision that affects app development.  

I think that the "ultra" and "flac" quality settings should be restricted to signed-in users only.  

Solution: gray them out in the app settings, and display a message when tapped that those bandwidths are available by creating a free account on RP.

It's about building a listener base so you can ask for donations.  High bandwidth streams cost more money.

Be sure to disclose occasional marketing on the T&C's when signing up.

**Comment by RPNate1** [comment]
William won't go for this at all. We won't force anyone to signup, regardless of the reasoning.
