### ISSUE TITLE
Suggestion: consider scrapping "info mode dark theme" or...

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#34]
...or plan to reskin the whole app in light mode.  It looks odd to have one section of the viewer and the app in light mode while everything else is dark.

I'd suggest either eliminating that option (all users get dark mode) or consider a "global" light mode used by the app, controls, and website.

**Comment by RPNate1** [comment]
Light mode is only where there are large blocks of text. This was for older users who complained about the readability. Works as expected.
