### ISSUE TITLE
Suggestion (b29): "Stream on cellular", reverse the logic, and provide a data diet

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#35]
Change the setting "Stream on Wifi only" to "Stream over cellular" and adjust the switch logic accordingly. 

Cellular should have to be consciously switched on - not a default. 

I would also suggest a (?) button next to celllular with a pop up that gives avg data consumed per hour on each quality setting.  

Display an additional warning for ultra / flac when cellular is enabled. 

This is needed to prevent accidental data overages and surcharges.

**Comment by RPNate1** [comment]
Ran past management. Keeping wifi setting as is.
