### ISSUE TITLE
Bug (b29): History view has time discrepancies for resumed song and tracks around it

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#36]
See screenshot.  The timestamps are out of order in a way that doesn't make sense, even though the actual play order is correct. 

When I connected RP to the car, "Truth is a Beautiful Thing" was playing.  Then Bill's bumper about 2017 being "five years ago" played, followed by "Keep in Mind."

### Steps to Reproduce:  

1. Start some music.
2. Pause RP for at least 10 minutes (~2 songs).
3. Resume playback.
4. Wait until the NEXT song loads.
5. Check the history view.
6. Read the song times very carefully.

**Comment by bradtchapman** [comment]
![9F5A883C-A0E9-42C8-9DB1-31DAC9030D4A](https://user-images.githubusercontent.com/32527656/216472491-82108d5e-62b9-41de-af5c-463bb4b62bb8.png)

**Comment by bradtchapman** [comment]
We're starting to blur the boundaries of what are app issues vs. website issues.

**Comment by donshefer** [comment]
I have seen this issue in the past, but I am not able to replicate in the current build (29).

**Comment by RPNate1** [comment]
There have been issues with this on the website. Jarred should be dialing this in.

**Comment by bradtchapman** [comment]
Is this really ready for QA?  It is still happening today. @RPNate1 

see attached screenshots from iPad OS.  Observed on all four stations.

![26AB3B6C-8294-4ECB-9A79-91EBE92E953C](https://user-images.githubusercontent.com/32527656/216846261-5ae64330-1235-49f1-b459-6d93a6c1afb4.png)

![60DC97BD-6D7B-49C5-81A5-519C72104504](https://user-images.githubusercontent.com/32527656/216846262-552df7a2-1619-4dcc-b565-9683bc218534.png)

![8046D2EB-2DB5-4F8A-A979-05896E0A061D](https://user-images.githubusercontent.com/32527656/216846258-057e8f88-8d42-4272-9d6a-d1fcae6fadb6.png)

![BACC51EB-8B3F-468B-862A-835CF59CEE7C](https://user-images.githubusercontent.com/32527656/216846250-3601b029-c76d-4a2b-a2f5-586e65ab48f2.png)
