### ISSUE TITLE
Suggestion: add a tip jar with in-app purchases

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#37]
https://developer.apple.com/in-app-purchase/

Listeners can send a "consumable" any time they want to show RP some microtransactional love.  I've seen it done in other apps and it works great.  

Apple does take their cut, but in exchange you get a low-friction donation platform with zero extra website code.

**Comment by RPNate1** [comment]
Vetoed. We are trying something new for fundraising. coming soon. Closing.
