### ISSUE TITLE
UI suggestion for smallest screens in History view

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#39]
Would you consider using a responsive CSS style for very small screens that makes the date/time a lot smaller?  The time of day is really massive right now and I think your margins / padding could be tighter. 

![7388CB7A-9E23-4686-AE3B-FB8A5BE25AD8](https://user-images.githubusercontent.com/32527656/216758830-e0b06198-e747-4632-bcca-d7d62455d8ff.png)

**Comment by RPNate1** [comment]
I agree this could be a good fix. Will get Jarred on this.

**Comment by RPNate1** [comment]
@jarro can we make this happen for the List Mode?

**Comment by jarro** [comment]
looks  a lot like 320  when comparing how many letters are visible in song names.
Which we've never tried to support.   Most pages will have much worse issues.

Can tweak that one.   But am curious  what the pool of devices are in the wild that will run into this.

**Comment by RPNate1** [comment]
I'll take that answer about not trying to support that in the past and close this one Thanks! @jarro
