### ISSUE TITLE
CarPlay: the "rating" icon should be greyed out when listening anonymously

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#4]
The icon used to rate songs is currently tappable when a user is listening anonymously.  The choices displayed are "Like" or "Never Play Again," which correspond to an 8 or 3 on the 10 point scale.  

See attached screenshots.

Voting should not be possible for anonymous users.  Please grey it out.

![unnamed](https://user-images.githubusercontent.com/32527656/214674003-3f74814c-47f1-4787-8050-1b6339369bf0.jpg)

![unnamed-3](https://user-images.githubusercontent.com/32527656/214674027-707a651e-30c8-4e2a-a2b6-f49359113004.jpg)

**Comment by RPNate1** [comment]
it's now gone!

**Comment by RPNate1** [comment]
This ticket should be closed! How the hell do I do that?? Not intuitive at all. Dammit Github.
