### ISSUE TITLE
Bug (b29): car view is not colorized

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#41]
### description:

Colorized Car View would change the background color from gray to a heavily blurred version of the album art.  This hasn’t happened on RPv2 AFAICT.

### Expectation: enabling this setting should mirror behavior from
RPv1.

![2678C5EE-08B7-4202-9B14-5CDD3F7C0615](https://user-images.githubusercontent.com/32527656/216759692-cf7e9f83-6cdb-41d1-b7df-d0e2a457fb55.png)
![EA8FF8A5-5D9B-4155-8530-898AEC7575E6](https://user-images.githubusercontent.com/32527656/216759697-a07750b1-af38-4827-bd89-580aee16f6a9.png)
![BCFBAE3E-294B-4F3A-9E64-D9573D7977BD](https://user-images.githubusercontent.com/32527656/216759699-df769c07-9678-4d02-9c15-fc476d53cb26.png)

**Comment by RPNate1** [comment]
This works for me.

**Comment by bradtchapman** [comment]
Can you share your hardware and software configuration please?

**Comment by RPNate1** [comment]
11 pro running 16.1.2, b30

**Comment by bradtchapman** [comment]
I tested this on my three devices:

- iPhone SE, 15.7.3: no blurred album artwork
- iPhone 12 Pro, 15.7.3: no blurred album artwork
- iPad mini 6, 16.2: blurred artwork

Perhaps something changed in iOS 16?  IDK if you have the source code of RPv1, where this action works fine on iOS 15 and 16.

**Comment by bradtchapman** [comment]
Reproduced 100% with the following steps:

1. Start a stream.
2. Enable car mode (steering wheel).
3. No blurred artwork appears in the background. 
4. Press skip (PSD).
5. Artwork now appears.  
6. Close Car mode.
7. Reopen Car mode.
8. Artwork is gone.
9. Press Skip (PSD).
10. Artwork loads on next track.

So it appears that the car mode only loads artwork on track start, but if a track is already in progress, it doesn't show the artwork.

This tells me that there are two separate calls to load album artwork: once in the web view, and once in car mode.  

This wastes data.

**Comment by RPNate1** [comment]
@bradtchapman still seeing this?

**Comment by RPNate1** [comment]
@bradtchapman This appears to be fixed. You?

**Comment by bradtchapman** [comment]
CONFIRMED FIXED.
