### ISSUE TITLE
Bug (b29): loading history view while stopped, unexpectedly starts playback

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#42]
See screen recording.  

### Steps to reproduce

1. Start RPv2 and play something 
2. Switch to a different music app and play.
3. Switch back to RPv24. 

4. Tap the menu, then History.
5. history loads but music has unexpectedly started.   

Uploading IMG_0016.MOV…

**Comment by RPNate1** [comment]
Yep. This should happen. Clicking any of the modes /info/, /slideshow/, or /list/ mode should start playback, just like the website. All three of those are considered playback modes.
