### ISSUE TITLE
Bug (b29): Info view still displaying incorrect / previous song

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#44]
### Description of issue

I'm starting to think the app is sending a cached / stale song ID when fetching the info view, instead of the currently playing song ID, which is displayed on the song info bar.

### Steps to reproduce

1. Load RP and start playing a song. 
2. Load the history view. 
3. Lock device. 
4. Wait until next song starts (not a bumper/promo).
5. Unlock device. 
6. Check what song is top most in history viewer.  If it is still the previous song, go to step 7.
7. Load the Info view by tapping the menu and tapping (i).  
8. You should see the previous track.
9. Now tap the song info bar at bottom.  
10. The currently playing song will load.
11. Tap the menu, then History view
12. Previous song will still be the most recent track.
13. Repeat steps 7-12 to confirm.

### Expectation

RPv2 should show the current song of the user intends to check the current track. 

### NOTE

I think this might only be happening for the first song AFTER the one currently playing if the device was locked.  The issue seems to resolve itself once TWO songs have gone by.

See attached screen recording. 

https://user-images.githubusercontent.com/32527656/216792960-f9543e3c-b71b-4e95-8541-9e4fa1c7923f.MOV

**Comment by RPNate1** [comment]
This appears to be fixed as of b32
