### ISSUE TITLE
Bug (b29): After scrolling, info view always unexpectedly reverts to first song played since changing stations 

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#45]
See **linked** video recordings taken from an iPad.  I've described this in previous bug reports but now I can show it happening on TWO different devices at the same time.  

I took great pains to ensure these three were in sync: iPhone 12 Pro, iPhone SE, Google Pixel 4a.  Not testing the Pixel.

**Comment by bradtchapman** [comment]
Example 1: https://www.dropbox.com/s/kkzgnvcus1lhik7/Video%20Feb%2004%202023%2C%204%2025%2026%20PM.mov?dl=0

Example 2: https://www.dropbox.com/s/yveylwhekuwcy67/Video%20Feb%2004%202023%2C%204%2032%2008%20PM.mov?dl=0


In both cases, RP's info viewer keeps showing Jeff Beck's "Goodbye Pork Pie Hat," which was the first song that started playing when I switched back to the Global Mix.

**Comment by RPNate1** [comment]
I cannot recreate this. Tried multiple times in b31. closing.

**Comment by bradtchapman** [comment]
Beta 31 is not in TestFlight yet.  How am I supposed to validate?

**Comment by RPNate1** [comment]
Weird. I got it this morning...

**Comment by bradtchapman** [comment]
Am I an "internal" or "external" tester?

Apps published to Testflight don't go through review for internal testers.  They do get reviewed for external testers.  Apple says it takes "less than 24 hours" for "90%" of apps.  That's optimistic.  I've had beta builds of other apps take days.  Older threads on Apple Developer Forum say that it took several days during COVID.  I'm hoping that has improved.  

https://www.instabug.com/blog/testflight-beta-testing-setting-effective-tests

https://developer.apple.com/app-store/review/

https://stackoverflow.com/questions/71996955/ios-tetsflight-manual-distribution-to-testers-groups

**Comment by donshefer** [comment]
Sorry, my fault. Build 31 has now been submitted for testing.

- Don
