### ISSUE TITLE
Bug (b29): iPadOS song list wont display most recent song, despite being selected and active.  Must wait until after song change to reproduce.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#48]
### Description of issue

On the main website, if I scroll somewhere on a song, the song list “unlocks” (is allowed to go out of sync) and the info pane will not change when the next song plays.  This is to facilitate discovery of the music and allow users to participate in the comments.  

On iPadOS, the app has a similar layout as the website, with a two column view.  

When I tap a song, sometimes it does not display that song’s info in the info pane, even though it shows as selected in the list  

### Steps to Reproduce
1. Load a station.
2. Scroll the info view for the current song.
3. Confirm that you see an open padlock.
4. Wait for the song to change.
5. Pick a previous song.
6. Pick the current song.

### Expected behavior 
I expect to be able to view the info for the current song.

See attached screen recording.  Watch for the second half of the video, maybe the last 20 seconds.  I recorded one video to report two issues.  I tried using the ‘microphone’ on it but it mixed the music at the same level so you might struggle to hear me, hence the explanation here.

### Configuration
iPad Mini, iPad OS 16.1.1, RP 0.9 build 29

**Comment by bradtchapman** [comment]
https://www.dropbox.com/s/ry7p5e32uwfo22l/Video%20Feb%2004%202023%2C%207%2017%2004%20PM.mov?dl=0

**Comment by RPNate1** [comment]
I just recreated this issue in b34 on my iPad (8th gen OS 16.3). In fact, when I click the current playing song at the top of the right column, it shows me the song info for the track that was playing when I opened my iPad. Even after letting the song change it still only shows me that track's info. I can select any other song and see the info. It's only the current playing song that is affected.

**Comment by bradtchapman** [comment]
SWEET.  I'M NOT GOING INSANE!

**Comment by RPNate1** [comment]
fixed at some point. Tested on b49
