### ISSUE TITLE
CarPlay: suggestion: change the "Rating" icon from "filter" to something else (like a heart?)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#5]
See attached screenshot for suggestions.

The **[SF Symbols](https://developer.apple.com/sf-symbols/)** library contains a massive collection of icons and symbols that Apple has designed for all app developers to use freely.  They are housed within the SF Pro font (included on iOS), which itself has 9 font weights, from Ultralight to **Black**.  

Newer versions of SF Symbols can handle multiple custom colors, automatic color hierarchy, shading and partial transparency, etc, but for maximum compatibility and legibility on a car display, you'll probably want to stick to the monochrome icons.

In CarPlay, the current symbol for the "rating" function is "line.3.horizontal.decrease.circle" — a circle containing three stacked horizontal lines, each decreasing in width downward.  In other apps on iOS, this is the "Filter" icon (i.e.: filtering messages in Apple Mail).  So in the context of RP, it doesn't make a lot of sense as an idea.

Meanwhile, the RP app and website have long employed a "Heart" icon for rating songs.  Lots of other apps use variations on hearts or thumbs up / down.  

[SF Symbols](https://developer.apple.com/sf-symbols/) contains several variations on thumbs up / down, plus a lot of hearts.

Keep in mind that SF Symbols has an **availability matrix.**  Some symbols are only available in later versions of iOS.

- SF Symbols 1.0 (2019): iOS 13, tvOS 13, watchOS 6
- SF Symbols 2.0 (2020): iOS 14, tvOS 14, watchOS 7, macOS 11
- SF Symbols 3.0 (2021): iOS 15, tvOS 15, watchOS 8, macOS 12
- SF Symbols 4.0 (2022): iOS 16, tvOS 16, watchOS 9, macOS 13

If you use a symbol from v3.0 and try to compile the app for iOS 13, Xcode should throw an error.

![Screen Shot 2023-01-26 at 11 48 42 AM](https://user-images.githubusercontent.com/32527656/214935654-f22695af-6eeb-4e8a-8d62-b2b086407105.png)

![Screen Shot 2023-01-26 at 11 47 58 AM](https://user-images.githubusercontent.com/32527656/214935663-cbe9db58-f045-4b4e-b500-937d7edfe04e.png)

**Comment by RPNate1** [comment]
The answer is a heart.

**Comment by bradtchapman** [comment]
And I heart this answer.

**Comment by RPNate1** [comment]
Unfortunately, that icon is not customizable. UGH

**Comment by bradtchapman** [comment]
Are you sure about that?  Apple shows a button with a heart on this user interface, in a WWDC 2016 session introducing CarPlay.

Session Link: https://developer.apple.com/wwdc16/722

(example is at the 3 minute mark)

![CC5CCF5C-C5F2-4A92-96B2-E85BB73AA305](https://user-images.githubusercontent.com/32527656/215234245-2351ea9b-f21b-44c8-8db8-6097296aa533.jpeg)

**Comment by donshefer** [comment]
Our current CarPlay implementation uses the older MPPlayableContentManager classes. It has not been updated with the newer CarPlay framework templates. When we update these to use the templates, we will have a lot more flexibility and can customize it further.

**Comment by RPNate1** [comment]
> Our current CarPlay implementation uses the older MPPlayableContentManager classes. It has not been updated with the newer CarPlay framework templates. When we update these to use the templates, we will have a lot more flexibility and can customize it further.

William has okayed the time to update the CarPlay implementation as you have time or make time. "We got to keep up with that stuff!"

Let's get that heart!

**Comment by RPNate1** [comment]
Closing since we'll get this handled.

**Comment by bradtchapman** [comment]
❤️🧡💛💚💙💜🖤🤍

**Comment by bradtchapman** [comment]
FYI @RPNate1 : this would be an excellent use for a tag called "CarPlay" since there are many issues like it.

**Comment by bradtchapman** [comment]
Yes. The new icons are there.  Tapping them does update the scores immediately on the main device screen.  This is great.  

I plan to file a separate minor bug about their behavior on the CarPlay interface.
