### ISSUE TITLE
Bug (b29): improperly sized album art caused text shift in info bar

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#50]
### Description of issue

One album appeared to have the wrong aspect ratio or dimensions, causing the text to shift.  I took screenshots of four album art thumbnails for comparison.

The one that looked incorrect was:

Cloud Cult: When Water Comes to Life

### Expected behavior

I recognize that the album covers of CD releases are rectangular compared to their vinyl ancestors.  This was especially true of jewel cases, and less so with DigiPaks.

The expectation, nonetheless, is that all album art and thumbnails across the app, no matter what context, must be square.  Crop, fill, whatever it takes.  I certainly don’t expect RP to retroactively edit the artwork; this can all be “fixed in post,” as we say here in Hollywood.

Four cropped screenshots are attached.  Put a ruler on the Screen and you’ll see the difference.  The rectangular one is the first greenish one at the top.

![3F98A305-1004-4188-8FCB-BE4398E14828](https://user-images.githubusercontent.com/32527656/216809527-e7734df4-8958-477d-8b26-d4e7c9e3d570.jpeg)
![DADFD575-1274-47EC-85D1-F8CE6BD63286](https://user-images.githubusercontent.com/32527656/216809528-03f02290-929e-47f7-bfe5-13804fa52220.jpeg)
![6976793E-9BE2-46B4-9A50-61A5501A5355](https://user-images.githubusercontent.com/32527656/216809529-e6b99336-5b75-4310-8207-aad514a80924.jpeg)
![F1FF535E-B7A1-45AC-A6C3-D92BA942DF1D](https://user-images.githubusercontent.com/32527656/216809530-2f7f4026-3d83-4d77-9dce-5ae3ae3a4f81.jpeg)

**Comment by bradtchapman** [comment]
😃 🎥 

I work for a media/entertainment company and got a degree in digital media arts + audio engineering!  This is why your project is so much fun and super important to me!

**Comment by donshefer** [comment]
updated targeting build 33
