### ISSUE TITLE
Bug (website?): info pane cropped on left and right side (CSS needs tweaking)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#51]
Not much explanation needed here.  The style sheet does not account for the iPhone SE, resulting in cropped content along the left and right edges.

See screenshots below.

![9A13DB78-E516-4D8C-BFF0-6129DED93CE4](https://user-images.githubusercontent.com/32527656/216809942-3b08504c-3a0b-471a-b403-cac8204b765e.png)
![643BC0DD-E337-423E-87A8-582E3324D60B](https://user-images.githubusercontent.com/32527656/216809945-a0d94e96-1f35-4d31-89d3-9063186f9333.png)

**Comment by bradtchapman** [comment]
UPDATE: 

This is 100% reproducible by navigating to the HISTORY view of the album.  It is not occurring on the main info viewer.  

In comparing this to a larger screen like an iPhone 12 Pro, I see the root cause.  

The album art and other DIVs on the page are sized differently in the history vs the info view.

See attached screen recording. 


https://user-images.githubusercontent.com/32527656/216843160-6183c57f-c1f4-4205-8aaa-d922c0cdf16d.MOV

**Comment by bradtchapman** [comment]
There are a number of inconsistencies between info and history view: album art size, font size, font weight, div size, margins, padding, etc...

@RPNate1 @BillGoldsmith - this is clearly Jarred's domain to fix, but I can't tag him on Github. 


![ECD3CCFB-7A41-44E7-8457-4A816A868A4D](https://user-images.githubusercontent.com/32527656/216843323-9594a180-b96f-4725-b25b-b713deeafcf6.png)

![F655EFD0-0238-4A09-83CE-587B68BF196D](https://user-images.githubusercontent.com/32527656/216843328-0e9d59ff-f334-4b45-a9ab-82c829be72e1.png)

**Comment by RPNate1** [comment]
The pages that are having the issue with div size differences are the "song" pages. When you click on a song title in Info mode or List mode, you are redirected to a Song page. There are also Artist and Album pages that share the formatting as Song. Just making sure we use the same language, so it's clear what needs fixing.

**Comment by bradtchapman** [comment]
YES.  Thank you.

The /info/ view of the album art has the correct art size because it is contained within `div.slideshowreplacement-cover.ng-star-inserted` that has a **12 pixel margin.**

On the /song/ page, the album art is contained within `div.cover.ng-star-inserted`, so the art fills the window width.

**Comment by bradtchapman** [comment]
Can I just say that I slightly prefer the text presentation on /song/ ?

**Comment by bradtchapman** [comment]
Also, one more thing: in order to reproduce this issue, you must use the **Web Inspector** and **Responsive Design** tools in **Safari** on the Mac.  The one in Chrome handles the sizing differently so you won't see the effect.

**Comment by RPNate1** [comment]
haven't been able to reproduce in b31.

**Comment by RPNate1** [comment]
@bradtchapman what gen SE is this that you are using?

**Comment by bradtchapman** [comment]
SE - 2015 with the 4" screen.

Not the iPhone SE 2020 version.  

—Sent from my iPhone

**Comment by jarro** [comment]
This looks like the same  320 width issue.

**Comment by bradtchapman** [comment]
@jarro : You must have changed something recently on the web side, because it seems a lot better lately.  No issues reading content on the 320 pixel screen.
