### ISSUE TITLE
Bug (b29): Unnecessary refresh of album art in "Now Playing" view

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#52]
### Description of issue

The album art refreshes needlessly in the "Now Playing" view when pausing and resuming music.  This wastes bandwidth and takes additional time and introduces more points of failure for the album art and metadata to load incorrectly.  

### Desired behavior

Check that the album art has not changed since last time (are we playing the same song?) and don't refresh until it actually changes.  

### Steps to reproduce:

1. Load any station.  
2. Lock the device.
3. Access notification center, control center, or lock and wake device to show the "Now Playing" container, and ensure album art is visible.
4. Press play / pause a few times.
5. Observe album art blacking out and refreshing. 

This will have knock-on effects on CarPlay presentation.  

https://user-images.githubusercontent.com/32527656/216844616-955e64a3-8485-4fc8-a798-eb345750b7f9.MOV

**Comment by bradtchapman** [comment]
Also, related to issue #50, the album
art here is not cropped square.  You can see the box and headphones shift slightly as the art reloads.

**Comment by donshefer** [comment]
Agreed. Fixed targeting build 30.

**Comment by bradtchapman** [comment]
@donshefer : did you figure out the square aspect ratio thing here too?  Sorry I kinda put two issues in one at the last second.  I think I mentioned it in another ticket.

**Comment by donshefer** [comment]
@bradtchapman No, I didn't. I will take a look.

**Comment by bradtchapman** [comment]
NP.  The aspect ratio issue is related to a different ticket.  The size of the box containing the album art should never take its dimensions from the artwork.  It should always be a rounded square (or squircle?), and the album art should "fill" to the box dimensions so there is no empty space.

**Comment by bradtchapman** [comment]
confirmed fixed in beta 30.
