### ISSUE TITLE
Bug (b29) all platforms: Settings menu does not block out app interactions

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#53]
### Description of issue:

When the app settings menu is open, I can interact with other parts of the app like tapping song info, playback controls, etc.

### Expectation

There should be a clear darkening or dimming of the interface below the settings menu to indicate that the rest of the app is not available, and there needs to be a “shield” layer placed under the settings menu that prevents any tapping through it…. EXCEPT … consider this as a suggestion: if someone taps outside the settings menu, this is an intent to leave the settings menu. So if they tap out of bounds, don’t imprison them; just close it. 

Leaving this open will cause end user confusion. 

### Reproducibility

100% on ALL DEVICES.  On iOS, the settings menu covers up most of the screen so I did not notice this at first.

**Comment by bradtchapman** [comment]
See recorded demo from iPadOS.

https://user-images.githubusercontent.com/32527656/216845633-289b7c1c-97d9-459f-aac2-2d7cc8189f0a.MOV

**Comment by bradtchapman** [comment]
Edit: I think we discussed this in an email some weeks ago.  I suggested creating a "folder tab" to point back to the Settings icon, and you agreed with the idea.

The purpose of this issue is to show how it is happening on all devices, and that it can lead to greater confusion on iPadOS since more of the screen is visible.

**Comment by donshefer** [comment]
I agree.

**Comment by donshefer** [comment]
Done. Targeting build 30.

**Comment by bradtchapman** [comment]
It works... but I think it could be a *little* bit darker / more opaque.  It's not quite strong enough.  Also, there needs to be enough color differential between the dark gray popup, and the dark gray background 'dead zone.'  

Either make it darker, or add a **slight** Gaussian Blur effect to the underlay.

**Comment by RPNate1** [comment]
fixed.
