### ISSUE TITLE
Feature Request: iPadOS: support rotation to landscape view

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#54]
I would like to see the RP app for iPadOS support landscape mode someday. That is all.

**Comment by RPNate1** [comment]
I'd be ok with iPads getting auto-rotate. They have enough real estate to properly display the columns. When we were concentrating on the phones, I wanted to lock, but in looking at the iPad, it makes sense.

**Comment by RPNate1** [comment]
Closing this after adding to future feature discussion
