### ISSUE TITLE
UI Suggestion (website): use icons or emojis to represent song, artist, album, release, and length

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#56]
I made inline modifications to the webpage using the web inspector and got the following result (see enclosed screenshot).

Using a symbol to represent the words is far more legible at any size, and allows you to line up the text neatly.  RP could find some nice black & white icons or export something from the SF Symbols Mac app — this is permissible for most icons.

<img width="410" alt="Screen Shot 2023-02-06 at 10 45 54 AM" src="https://user-images.githubusercontent.com/32527656/217058425-0a655939-f776-48f7-bcca-6f5f3565ffdb.png">

Song:
<img width="100" alt="Screen Shot 2023-02-06 at 10 57 41 AM" src="https://user-images.githubusercontent.com/32527656/217061694-f7fe257e-9cd2-4da2-8535-5b88d504b587.png">

Artist:
<img width="100" alt="Screen Shot 2023-02-06 at 10 58 10 AM" src="https://user-images.githubusercontent.com/32527656/217061741-08ee6abb-130a-42b7-8068-63524825d08c.png">

Album:
<img width="100" alt="Screen Shot 2023-02-06 at 10 58 01 AM" src="https://user-images.githubusercontent.com/32527656/217061915-e31a3b6a-49c0-41ce-aab7-793b2f9bf038.png">

Release:
<img width="100" alt="Screen Shot 2023-02-06 at 11 01 48 AM" src="https://user-images.githubusercontent.com/32527656/217062005-b1a01f8b-6dd8-49e2-a5a4-5007e3fe3397.png"> <img width="100" alt="Screen Shot 2023-02-06 at 11 03 22 AM" src="https://user-images.githubusercontent.com/32527656/217062046-ca008cc3-7b38-467f-84c4-0f529d052e14.png"> <img width="100" alt="Screen Shot 2023-02-06 at 11 03 03 AM" src="https://user-images.githubusercontent.com/32527656/217062028-ea10be55-cd44-4f58-b4eb-e9e453ab660a.png">

Length:
<img width="100" alt="Screen Shot 2023-02-06 at 10 59 03 AM" src="https://user-images.githubusercontent.com/32527656/217062133-ddfcc302-4117-44b9-9799-b4db60582eeb.png"> <img width="100" alt="Screen Shot 2023-02-06 at 10 59 13 AM" src="https://user-images.githubusercontent.com/32527656/217062148-c6b2277a-9950-4369-80b1-04fd0c6a39c7.png">

**Comment by bradtchapman** [comment]
I was overthinking the "release" symbol. A Calendar is probably best, since it stands to represent a date.

**Comment by RPNate1** [comment]
William detests these. Won't happen. lol

**Comment by bradtchapman** [comment]
![8CE865D2-846F-4AA0-B35B-95A4D71502B5](https://user-images.githubusercontent.com/32527656/217116335-6b89616b-88f3-4bfb-8f61-f35d24418597.jpeg)

I send this with all the love in the world.
