### ISSUE TITLE
Feature Request (b30+): Bring back the in-app playback progress bar!

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#57]
I loved having the playback progress bar in RPv1.  I would love to see that it gets introduced in RPv2!  The app already 'knows' how long each track is, because it appears in the Now Playing view.  

Knowing how much time I have left to enjoy a song helps me plan my activities around it: whether preparing to leave the house, going to the store, sitting in the car until a song is done...

**Comment by RPNate1** [comment]
Will discuss again...

**Comment by RPNate1** [comment]
added to the new simple mode and player controls. As this isn't a bug and just feature request that we are now addressing, I'm gonna close this.
