### ISSUE TITLE
Bug (b30): Info Bar: text too small, no visual difference between it and the rest of the UI

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#58]
![2195EC4D-7905-4A52-BFE9-6759540C9428](https://user-images.githubusercontent.com/32527656/217069444-a921c3ec-3ad2-4f88-8f9c-c5fa78e55c2d.jpeg)

Is this an eye test?  LOL...

To help distinguish it from the rest of the UI, put a thin light-gray line above it, or make it a different shade of gray.  If you need some choices, there's a book by E. L. James that has fifty different grays to choose from.

**Comment by RPNate1** [comment]
We were just making adjustments to the website with the addition of a gray line to differentiate the player from content above , as well.  Tiny thin gray line approved.

**Comment by bradtchapman** [comment]
The text that I was indicating there is inside the app, not on the website. This is Don's domain.

**Comment by RPNate1** [comment]
I meant we saw the same thing on the site and decided to make that change there and we should do that here.

**Comment by RPNate1** [comment]
changed to black. Clear delineation. Done.

**Comment by bradtchapman** [comment]
Slated for build 31?

**Comment by bradtchapman** [comment]
@RPNate1 : think this bug report fell off the wagon.  There's a clear color difference now between the app (black) and the website (dark grey) on the song info band. 

Did @donshefer indicate that he finished working on this?

**Comment by RPNate1** [comment]
Yeah, this was fixed a few builds ago.
