### ISSUE TITLE
Bug (b30): Repeatedly pausing & playing causes progress bar to advance too quickly.  Bar reaches -0:00, but the music continues.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#59]
### Description of issue 

While using ~~AirPlay~~ **ANY AUDIO DESTINATION**, repeatedly pausing and resuming the music will cause the playback progress bar to advance forward in time until it reaches the end, even though the song has not yet finished.  

I believe ~~AirPlay~~ iOS winds any playing media back a few clicks due to the inherent buffering built into playback transport.  My guess is that they want to ensure no part of the song is missed.  

### Expected behavior:
The progress bar in RP needs to check in to see how much time is left on the media so it's at least reasonably accurate.

### Configuration
- iPhone 12 Pro, 15.7.3, RPv2 0.9 b30.
- iPad mini 6th gen, iOS 16.1.1, RPv2 0.9 b30.

Obviously this was an extreme for demonstration purposes, but it will have a noticeable effect if someone uses other functions on their phone that repeatedly pause audio: for instance, dictation.  

See below linked video recording of a demonstration.

https://www.dropbox.com/s/jersrkfisqe9cm7/PXL_20230206_202911316.mp4?dl=0

**Comment by bradtchapman** [comment]
UPDATE: this happens with ANY PLAYBACK transport:

* built-in speaker
* AirPods
* AirPlay

**Comment by bradtchapman** [comment]
Attached screen recording from an iPhone using only built-in speaker.  This will be just as annoying for you to watch as it was for me to make!  I promise you that!


https://user-images.githubusercontent.com/32527656/217081839-46cb7366-2bda-47ac-a7c7-627f156e0e1b.mp4

**Comment by RPNate1** [comment]
The lock screen progress bar isn't us. That is an iOS thing. @donshefer anything you can do with that? It seems like an extreme edge case.

**Comment by bradtchapman** [comment]
@donshefer @RPNate1 :

I just filed #62 for an unrelated issue, but this issue was made grossly apparently in testing the other bug.

**Comment by donshefer** [comment]
fixed targeting build 34

**Comment by RPNate1** [comment]
I'm not sure this is fixed. I tried multiple pause/plays and still saw weird jumping around (jumping backward by 2 seconds) and when I paused and restarted the playback, it jumped ahead like it was tracking the live stream, instead of holding the pause state.

**Comment by bradtchapman** [comment]
Confirmed.   The progress bar is still jumping around a bit in the Now Playing interface.

**Comment by bradtchapman** [comment]
Pausing makes the progress bar jump backwards slightly, then forwards, then holds. When I resume the music after, say, 30 seconds... the music resumes from the same spot but the playback progress indicator jumps forward 60 seconds.

**Comment by bradtchapman** [comment]
Pausing makes the progress bar jump backwards slightly, then forwards, then holds. When I resume the music after, say, 30 seconds... the music resumes from the same spot but the playback progress indicator jumps forward 30 seconds.

**Comment by donshefer** [comment]
Heres what I see happening: The "Now Playing" controls are keeping their own count of where it thinks the song is. But it is getting out of sync. So I added code that will update the time to the correct place every time you press play/pause. So the jumping around you are seeing is our code correcting the time. It ends up with the correct time now (which is wasn't before). But I have not been able to stop the OS getting it wrong and it jumping around. I will see what I can do.

**Comment by donshefer** [comment]
@RPNate1 I wasn't able to stop it entirely, but I minimized it as much as I could. Now it just jumps by a few seconds when you press play. Much better.
Fix targeting build 35

**Comment by bradtchapman** [comment]
I'm sort of curious why it jumps at all, if the app is just playing an .m4a file under the hood.  Can you give me a little deeper understanding of the media transport method(s)?  Why is it different for RPv2, or why does it need to be different vs RPv1 where It was stable?

Do you think this is worth using one of your 2 paid technical support cases with Apple Worldwide Developer Support to figure out ?
