### ISSUE TITLE
Bug with resuming playback after idle — when music block ends, another one does not start.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#6]
(repeated from a previous email)

On any given day, I will start playing a block of music on RP (e.g. Main Mix), then put the app away for a while or play another form of media that pauses RP.  When I come back the next day, RP continues playing exactly where I left off ... until the end of the music block is reached.  Then it fails to load the next block.

I tried the Skip button, Play/Pause button, tapping the metadata bar, and even selecting the same station from the drop down. 

Workarounds:

1) Select another station (e.g.: Mellow), then select the previous station (e.g. Main).

2) Quit / relaunch the app.

RPv2 doesn't have a 'debug' or 'send logs' function like RPv1, so I can't help you diagnose this further.

**Comment by RPNate1** [comment]
The app needs to call the API after every pause/play and on restart. The API timeout should be handling this.

**Comment by RPNate1** [comment]
### Brief description of the issue: Playback paused by Spotify app, RP would not restart play/buttons disabled

### Steps to reproduce: Open and play track in spotify, while RP is running in the background. Return to RP to unpause/play.

### Expected result: RP would take over audio again

### Actual result:  it would not play and pause/skip buttons did nothing. I could change the channel and the song info changed on the player but it did not update the Info mode to the new track info or start playing. I closed out spotify and still no luck. had to restart RP

### Where did you see it? (App build version, device type and iOS version): build 27, Iphone 11 pro, iOS 16.1.2

**Comment by donshefer** [comment]
Yep, this is the one I'm working on. 👍🏻

**Comment by bradtchapman** [comment]
Will wait for build 28 and later to re-test this.

**Comment by donshefer** [comment]
Fixed targeting build 28

**Comment by donshefer** [comment]
@RPNate1 I added logic to clear the song queue if the pause has been longer than 45 min. I believe the existing app was doing something similar.

**Comment by RPNate1** [comment]
Works!
