### ISSUE TITLE
🔎 (b30): UI: Regression: playback controls are impossibly small now that “play/playing” have been restored

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#60]
What is this?  A radio app for ants ??

![8C478212-F301-482F-8DD2-D521DCFDC926](https://user-images.githubusercontent.com/32527656/217122148-c9265fef-7bb9-4b9b-b173-0a36c365390c.png)

This is on an iPhone SE.

**Comment by bradtchapman** [comment]
What purpose does the word serve if the playback icon tells that story?  Was this a William override ?

**Comment by RPNate1** [comment]
William wants the label. The icons appear normal on my phone. 11pro/16.1.2/b30

**Comment by bradtchapman** [comment]
@donshefer : second opinion, please?

**Comment by bradtchapman** [comment]
@mtnbrit Chime in please.  Thanks.

**Comment by RPNate1** [comment]
Curious if b31 fixed this @bradtchapman

**Comment by bradtchapman** [comment]
No, not fixed in beta 31.  I believe I checked beta 32 on the SE yesterday, and in **Info View** the controls are too small.  Aside from the simplified UI quirks in its debut build, the simplified viewer is sufficiently comfortable for every day use on the smallest screen.

**Comment by bradtchapman** [comment]
![44C01386-69DD-4BF2-82AF-0E2EEB509F6A](https://user-images.githubusercontent.com/32527656/219300339-7909bc0f-4653-46f5-84f8-3505770159fd.jpeg)

**Comment by bradtchapman** [comment]
![E2C51B5D-4A63-4533-BF10-2232F599BA4B](https://user-images.githubusercontent.com/32527656/219300556-a8aad728-eefa-4ebe-8245-ea2042945b9c.png)


This is the **simple** player on an iPhone SE 1st gen.  No general issue with usability.  It’s only the song view that has the tiny controls.

**Comment by donshefer** [comment]
Damn, I thought I tested on SE, but probably the latest one. @bradtchapman which SE are you using (there are 3 generations) and what iOS version is it on?

**Comment by bradtchapman** [comment]
The first gen SE.  2015.  

iOS 15 is the latest that device supports.  

—Sent from my iPhone

**Comment by RPNate1** [comment]
That phone is dead, unfortunately. We need to consider that when dialing in
usability and screen size.

**Comment by RPNate1** [comment]
@jarro This on your end?

**Comment by RPNate1** [comment]
Did this end up being fixed for you @bradtchapman

**Comment by bradtchapman** [comment]
No, @RPNate1 .  Still too small in b36.

 Does @donshefer test with an **iPhone SE 1st Gen** in the Xcode simulator running iOS 15?  This device would not be visible in iOS 16 mode, and the similarly named iPhone SE’s from 2020 and newer have larger screens. 
 
 see attached screen recording. 

https://user-images.githubusercontent.com/32527656/221018370-94531ac6-b876-45c8-afc2-5374547959e5.MOV

**Comment by RPNate1** [comment]
@bradtchapman fixed?

**Comment by bradtchapman** [comment]
Nope.  iPhone SE 1st gen (320-pixels wide).

![570E8FB5-3185-431C-AC40-0291252CEFBF](https://user-images.githubusercontent.com/32527656/226460836-46373232-ea47-4147-960c-8faa6f601895.jpeg)

**Comment by RPNate1** [comment]
@bradtchapman fixed?

**Comment by RPNate1** [comment]
I saw the jump in build numbers as well. 

You tell me,  did the change make it in? @bradtchapman  ;)

**Comment by donshefer** [comment]
Yes, although in the next build it was completely removed for everyone.
