### ISSUE TITLE
Bug (b31): MAJOR — Intermittent — Music Playback.  Resuming paused playback sometimes doesn't work if the music has been paused for more than 10 seconds, and RP was in the background

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#62]
### Description of issue

If RP's music has been paused for 11 seconds or more — I tested various pause lengths to determine the minimum duration that will induce repeated failures — the music will not resume if RP was also running in the background at the time.

This behavior does not always occur, but once it does, it can be triggered from the "Now Playing" widget in the Notification Center, and also from the stalks of AirPods Pro (you squeeze them to pause / resume playback).

While reproducing this bug, I am observing a more extreme instance of the issues first seen in #59, where the playback progress bar jumps WAY ahead, then jumps back.  It's like RP has a different internal timer of the track's position and the progress bar in "Now Playing" is showing an elapsed time as if the song had still been playing.  The elapsed time does not appear until the music is playing.  You can also see it briefly if you're watching the screen when the pause-play-pause behavior is occurring: the elapsed time will jump ahead, then jump back to an earlier point in time.  

This bug is easier to observe if you leave the music paused for several minutes, but I must stress that it is **_intermittent_** and happening about 50% of the time I've tried to test it.

The key is to leave the music paused at least 11 seconds before trying to resume.

### Steps to Reproduce.

1. Launch RP.
2. Ensure Autostart is disabled (to match my config).
3. Play a station.
4. Switch apps a few times and do something else on your phone.
5. Pause RP via AirPods Pro stalk, or via the Now Playing widget on the Lock Screen / Notification Center.
6. Wait at least 11 seconds.
7. Resume RP via AirPods Pro stalk, or the Now Playing widget.
8. You may see the music resume right away, or it may stay paused.
9. Observe closely the elapsed time as it flashes on screen.

### Additional Notes

1. If you induce a failure (pause-play-pause), then try resuming the music within 10 seconds, it will resume.  The elapsed time will still be wrong, however.

2. You do not need any Bluetooth speakers or headphones connected for this to fail.  I observed it with the phone sitting out by itself.

**Comment by RPNate1** [comment]
I successfully recreated this. it's really weird.

**Comment by bradtchapman** [comment]
I like big bugs, and I cannot lie!
You other coders can't deny!
So when the software ships
with an itty bitty glitch,
and becomes a major bitch
you GIT - HUB!
Yeah the code needs love
'Cause you know that bug is tough.
Deep in the code it's buried,
At the screen I just keep starin'.
Oh, baby!  I gotta compile ya,
Analyze and file ya,
My Xcode tried to warn me,
but your functions make me (ERROR: 40)

(With apologies to Sir Mix-A-Lot)

**Comment by bradtchapman** [comment]
@RPNate1 : Sort of.  You've cut off one of the hydra's head but another has grown in its place. 

The player doesn't hiccup and pause like it used to, but now it takes about 3-4 seconds to resume whereas before it was responding instantaneously to button presses.  The extra long delay may lead users to think something is wrong and press it again and again.

**Comment by bradtchapman** [comment]
Note: you must pause at least 11 seconds to reproduce this.  Watch a clock; don't count "one mississippi, two mississippi..."
