### ISSUE TITLE
Bug (b31): Moderate: After closing the minimalist “car mode,” the info page refreshes and comes up blank

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#63]
### Description of issue

After minimizing the car mode display, the info page refreshes but it is completely empty.

### Steps to reproduce

1. Start a station.
2. Open the car mode view.
3. Close it.
4. Observe the contents are empty.
5. Tap song info bar to refresh.

### Workaround

Tap the song info bar to reload the contents.  

### Affected devices  

iPhone 12 Pro, 15.7.1, RP build 31
iPad mini 6, 16.1.1, RP build 31

### Notes

the iPad has two columns in the info view.  On refreshing using the above workaround,  only the song info loads. The history pane remains empty.

see attached screen recordings for demonstration.

**Comment by bradtchapman** [comment]
iPad 

https://user-images.githubusercontent.com/32527656/218280745-fa052e13-4029-4aab-819f-616123df2278.MOV

**Comment by bradtchapman** [comment]
iPhone:


https://user-images.githubusercontent.com/32527656/218280782-6ae3259a-5275-42d1-8a32-b6927826c75c.MOV

**Comment by bradtchapman** [comment]
iPad


https://user-images.githubusercontent.com/32527656/218280806-51777ebc-cf14-41a3-8d2b-8d3a4bc1a5b1.MOV

**Comment by donshefer** [comment]
I think this should be fixed in build 32.

**Comment by bradtchapman** [comment]
Confirmed fixed; however, it's not awesome that the entire page has to be reloaded.  There's black for several seconds, and it could be much longer if someone is on a slow data connection or intermittent offline
