### ISSUE TITLE
UI (b31): Confusing use of three-horizontal-stripe icon in two places

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#65]
See screenshot.  

Now that the app includes a proper menu—thank you for that!—there could be confusion about what the "history" item does, and why it also has three horizontal stripes to represent a list.  It'd be best to eliminate any ambiguity.

Please consider changing the history icon.  I've previously suggested a suitable replacement from the SF Symbols library.

![78BEA165-8DFD-4592-880A-FDE36889FBB0](https://user-images.githubusercontent.com/32527656/218337673-e64bd158-825a-47a8-b624-3339a1a6a3e5.jpeg)

![7EED471E-FF83-4317-ABA7-17FCB15E74C2](https://user-images.githubusercontent.com/32527656/218337917-c5400a55-1fe0-46af-8c2a-fb09dc34e800.jpeg)

**Comment by RPNate1** [comment]
The three lines for List Mode (not history) is implemented everywhere and won't be replaced. However, we can change the navigation  icon to be slightly different. I like the "fries" icon. (so many foods to choose from!)
<img width="63" alt="Screen Shot 2023-02-15 at 12 00 19 PM" src="https://user-images.githubusercontent.com/123519331/219140579-fd54575a-fe27-4ed1-a25e-7f4f14d2ae8e.png">

**Comment by RPNate1** [comment]
@donshefer put the Fries in Trello for you

**Comment by RPNate1** [comment]
fixed with a side of fries

**Comment by bradtchapman** [comment]
@RPNate1 : I'll have a coke with that, please.  To go.
