### ISSUE TITLE
UI (b31): Menu button and logo shift unexpectedly when opened

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#66]
### Description of issue

The new menu must be closed by moving one's finger to a different part of the screen.  This may cause frustration, and also causes the logo to move unexpectedly...

Consider keeping the icon in the same location.

See attached screenshot for example.

![rp-menu-close](https://user-images.githubusercontent.com/32527656/218342382-f3eb694a-af93-4fc8-8d1f-38ce9c6e0f66.png)

**Comment by RPNate1** [comment]
@donshefer let's do this.

**Comment by donshefer** [comment]
Updated targeting build 33

**Comment by bradtchapman** [comment]
"X marks the spot!"  Looks good.  

(One can still see the logo change sizes slightly as the menu is open/closed.  It breaks the illusion.  Just checking from my iPhone 12 Pro right now.  I will need to see how this looks on the other devices when I am home).
