### ISSUE TITLE
Bug (b31): Now Playing widget: the "Rating" option lags behind state of user login, requires app restart to resolve

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#67]
### Description of issue

The "Rating" button in the Now Playing widget is not updating in a timely manner when users log in or log out.  

When listening anonymously, the left most button is a greyed out (<<).  When a user is logged in, it appears as an active, tappable (≡) symbol so they can rate / vote on a song.  

The problem is that the button stays in the inactive state (<<) after logging in, and does not refresh or update **until the app is relaunched**.  By the same token, if someone logs out, widget retains the active rating button (≡), and voting does does nothing.  Relaunching the app also resolves this discrepancy.

### Workaround

After changing account state, quit & relaunch the app and check the Now Playing widget.

### Steps to reproduce

1. Launch RP.
2. If signed in, sign out and relaunch the app.
3. Start listening anonymously.
5. Check the Now Playing widget and confirm you see (<<) is grayed out.
6. Tap the settings or profile button and sign into your account.
8. Resume playing music.
9. Check the Now Playing widgets again and see that the icon is still a grayed out (<<) that prohibits interaction.
10. Kill the RP app.
11. Relaunch the RP app and play some music.
12. Check the Now Playing widget.  You will see the (≡) button and can cast votes.
13. Sign out of RP.
14. Resume playback and check the Now Playing widget; it will still be an active (≡) button.  

I do not know if it is actively casting votes in this state, but I can't check it on the backend either.

### Notes

This does not affect the existing Heart widget for rating songs.  But when a user is walking about or driving in their car, they might want to quickly vote on a song instead of unlocking their phone and interacting with the app.  The inconsistent state adds confusion and friction to that experience.

**Comment by bradtchapman** [comment]
See attached video for demonstration.

https://user-images.githubusercontent.com/32527656/218345058-4c101312-3319-4979-b3a5-197dd9942086.mp4

**Comment by RPNate1** [comment]
I never get that option to give a simple play more like this or play less like this. I tried a few ways to get that to pop up. 

It doesn't actually cast a vote to my knowledge.
