### ISSUE TITLE
Bug (b31): Some items in the new menu are unexpectedly not tappable.  They need full-width tap zones.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#68]
### Description of Issue

Menu items that only contain text are not tappable across the entire width of the menu line that contains them.  This an unexpected behavior, since the items that have sub-items and disclosure triangles are tappable across the full width.

The **top-level** menu items that need full-width tap zones are:

- Home
- Swag
- Blog
- Login
- Support RP

Additionally, any sub-item within the main menu items needs to be tappable across the entire bar.

**Comment by RPNate1** [comment]
agreed

**Comment by donshefer** [comment]
updated targeting build 33

**Comment by bradtchapman** [comment]
The behavior is fixed and build 33. However, it would help to have a brief highlight on that menu item just as the finger taps it. This is a small but important bit of user feedback that helps someone know which item they just tapped. The highlight should appear just the same as tapping one of the menu items with a sub menu.

—Sent from my iPhone

**Comment by RPNate1** [comment]
I'll close this issue and add the request of a highlight to the Trello board.

**Comment by bradtchapman** [comment]
Thank you!
