### ISSUE TITLE
Bug (b31): After closing the slideshow, the song info area is black.  The yellow loading ring is seen briefly. 

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#69]
This issue appears related to #63.  Please review the screen recording to observe the behavior.  

In addition to forgetting the previous view, the app is loading content again that was already on the device. 

Please consider creating a new view that sits on top of the main window.  This will keep user data usage down, and Bill's server costs as well (unless he is using Amazon S3 with CloudFront or similar caching).

**Comment by donshefer** [comment]
I believe this is fixed in build 32.

**Comment by bradtchapman** [comment]
Confirmed, fixed.
