### ISSUE TITLE
Unexpected / missing: album year not shown on main playback / info views, but only visible in History view.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#7]
The album's release year is not shown in the RPv2 interface (screenshot 1), neither on the web view (where the album art is displayed) nor in the metadata bar below it.

Workaround: 

The album year is visible in the History view (screenshot 2).

In RPv1 (not shown here), the album release year is displayed not on the main playback screen, but on the "Info" slider when the album art is tapped and also in the History view.

![image0](https://user-images.githubusercontent.com/32527656/214937196-3d0c9237-4b88-45eb-9039-7ba2005a944b.jpeg)

![image1](https://user-images.githubusercontent.com/32527656/214937201-65c5b02b-2cb7-4489-94e2-db5b2e0250e4.jpeg)

**Comment by RPNate1** [comment]
This is on Jarred. I have him putting the release year in parentheses for the single column display, which appears to be the only place this comes into play.

**Comment by bradtchapman** [comment]
Later today, I started seeing this:

Song Title
Artist Name
Album Title **(undefined)**

Early tests of implementing this request?

**Comment by RPNate1** [comment]
Yeah, I assume that's what is going on.

**Comment by RPNate1** [comment]
Fixed

**Comment by bradtchapman** [comment]
CONFIRMED.  It is now showing in the app with no new build, so this was server-side.
