### ISSUE TITLE
Bug (b31): Slideshow images are not updating when new song loads

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#70]
### Description of issue:

The slideshows are a collection of images loosely tied to the song's title or lyrical content.  Sometimes they're tongue-in-cheek, other times they are quite strange; but they all have Bill's fingerprints on them.  The play JSON file for each song delivers a list of IDs, about 20-30 images, which should last more than the length of the song.

What I observed tonight, while listening to Stevie Wonder's "Don't You Worry 'Bout A Thing," was that the slideshow contained stock images of women looking worried.  

The next song was Jack Johnson's "One Step Ahead."  However, the women continued to pan and cross fade across my screen for a while.  

It wasn't until I closed the slideshow and reopened it that I saw a new set of images, with various kinds of "steps" in them.  

The slideshow view needs to refresh its list of images at the same time as the next song loads.

I have a screen recording of this but it's 5 minutes long.  I suspect you can reproduce this easily, though.  Let me know otherwise.

**Comment by RPNate1** [comment]
I noticed the same.

**Comment by donshefer** [comment]
Fixed targeting build 33

**Comment by bradtchapman** [comment]
CONFIRMED.  FIXED.  Thank you!
