### ISSUE TITLE
Feature Request: auto-rotate iPhones to start Slideshow (a la RP on Android)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#71]
### Feature Request

I have a Pixel 5 tester phone and the Android version of RP supports a gesture that when the phone is rotated to landscape, the slideshow automatically begins.  The play controls are visible for about 10 seconds. then slowly fade out.  A simple tap restores them temporarily until they fade away in a dream like state.  When the phone is rotated to portrait, the simple player view is restored.  

It's a delightful experience. 

Is this on your feature roadmap for the iOS version?

**Comment by RPNate1** [comment]
Please send me feature requests in emails. I promise to bring them up to the team. I want to make sure this bugfest stays bug-centric, as we will be adding a couple of dozen testers and I do not want this space polluted with a couple of dozen people requesting features here.
