### ISSUE TITLE
Bug (b32): UI: Album art needs a placeholder while loading (or fails to load).

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#72]
I realize that build 32 is essentially beta 1 of the new simplified UI.  This one is pretty glaring. The UI needs a **placeholder** for empty or failed album artwork to ensure that all the other UI elements remain in the same position.

See attached screenshot. 

![667CE225-6BB3-4139-8459-EA461ACC7B66](https://user-images.githubusercontent.com/32527656/218906416-2410dc69-1f16-4dee-9c18-85c381728383.png)

**Comment by RPNate1** [comment]
yep.

**Comment by donshefer** [comment]
fixed targeting build 33

**Comment by bradtchapman** [comment]
Suggestion for testing: use the "Network Link Conditioner" to simulate a very slow connection, so you can keep the artwork from loading too quickly.

**Comment by RPNate1** [comment]
fixed
