### ISSUE TITLE
🐞b32: UI: upon returning from full info view to simple view, the album artwork disappears, and does not load until the next song.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#75]
This bug report serves to document something I have observed in this build, but I suspect you might be trying to fix it elsewhere in the application.  

I am re-using the same video that I recorded for #74 because the bug is apparent in that recording.

adding a placeholder as described in issue #72 72 should help as well.

https://user-images.githubusercontent.com/32527656/219157792-2ca817d4-b23b-4fd9-8491-4a74dfebac73.MOV

**Comment by donshefer** [comment]
Should be fixed in build 33

**Comment by RPNate1** [comment]
It loads now, but there doesn't appear to be a placeholder because the text bounces as the art loads.

**Comment by bradtchapman** [comment]
CONFIRMED.  FIXED.
