### ISSUE TITLE
🔎(b32): UI: Menu dimensions are not uniform across devices.  Reachability, issues, awkward presentation

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#76]
### Description of issue:

There is a 'Goldilocks and The Three Bears' problem when it comes to the size of the main menu on different device form factors which is making it awkward to use, and looks weird on larger screens.

- On the iPad mini, the is **too large** : lots of extra black space at the bottom, and its width exaggerates the problems called out in the following issues:
  - #66 
  - #68 
  - #72 
- On an iPhone SE, it is **too small** : cramped in width, and cropped in height requiring scrolling to view all items.

- On a moderately sized iPhone screen, the menu feels **just right**.

A forensic analysis of screenshots in Photoshop (using the ruler & guides) shows that the menu dimensions appear to be set **uniformly at approx. 70% of the screen width and height**.  This does not take reachability or usability into account, and it just looks weird on any iPad.

As a user, I expect the menu to be **consistently sized** across **all** screen sizes, so my eyes don't have to scan so far to read everything.  

For the menu width, I would suggest using "2.5 human fingers" as a guide, and ensure that the menu is tall enough to accommodate all items.  Even the smallest screen — iPhone SE (2015) — has enough room to fit the menu as presently designed.

See attached photo and screen shots.

![PXL_20230216_010921348](https://user-images.githubusercontent.com/32527656/219256920-c3bf1e87-90f8-44de-b9c9-335d0893103d.jpg)

<img width="388" alt="Screen Shot 2023-02-15 at 7 08 06 PM" src="https://user-images.githubusercontent.com/32527656/219262381-92ceeb21-5614-4873-8c85-787878a4889c.png">

<img width="320" alt="Screen Shot 2023-02-15 at 6 57 33 PM" src="https://user-images.githubusercontent.com/32527656/219262390-af0670cd-fc5d-4774-9c28-90804ea67572.png">

<img width="345" alt="Screen Shot 2023-02-15 at 6 57 10 PM" src="https://user-images.githubusercontent.com/32527656/219262395-1b9226af-59f8-4109-8da5-cc3ca65dd87e.png">

**Comment by bradtchapman** [comment]
Somewhat related to #66 : placing the logo in a consistent location — left-aligned, next to the "fries" / "close" icon — that will solve the other alignment issue present in these screenshots.

**Comment by bradtchapman** [comment]
As for the 'fries' / 'close' menu icon, I am referring to [your comment](https://github.com/BillGoldsmith/iOS-bugfest/issues/65#issuecomment-1431956221) in issue #65

**Comment by RPNate1** [comment]
I like the uniformity. @donshefer

**Comment by donshefer** [comment]
Yes, the menu width is currently set to 70% of the screen size.
@RPNate1 Sorry, does that mean I should change it for iPad only? 
If so, how? Just let me know what you want.

**Comment by RPNate1** [comment]
I'll be addressing this with some mockups next week, now that we have mostly everything working properly (usually).

**Comment by RPNate1** [comment]
Gonna close this as some of this has been slowly chipped away at and the iPad/MacOS/TV are going to be gone over for UI issues next
