### ISSUE TITLE
🐞b33: closing slideshow always returns to song info view, instead of simple player

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#77]
### Description of issue

When a User decides to close the slideshow viewer, they expect the app to return them to the previously selected interface, whether it is the Simple player, song info view, or list view.  

in build 33, if a user starts in Simple player, then opens the slideshow view, then closes the slideshow view, the app will return them to the song info view. This is unexpected behavior.

meanwhile, switching from list view to slideshow view, then closing the slideshow, will return the user to the list view as expected.

### Workaround

The only way to return to the Simple player is for user to click the options menu, then click the info button.

### Demo

see attached video recording.

https://user-images.githubusercontent.com/32527656/219484857-225b6281-8b27-432e-9cd4-5992dcedd66a.MOV

**Comment by RPNate1** [comment]
Confirmed. Should revert to previous interface.

**Comment by donshefer** [comment]
I believe this is a duplicate ticket.
Should be fixed in build 39.

**Comment by RPNate1** [comment]
fixed in b39
