### ISSUE TITLE
🐞Web: the notification icon is blank.  Once the notification count badge is gone, it becomes essentially invisible.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#79]
### Description of issue

The notification button seems to be blank.  I noticed this while testing for #78. 

See attached screenshot.  

I'm guessing there is supposed to be something there in the red circled space ?  It's blank now, but it had a "(2)" before when I had two unread replies to check.

![F5205020-92AC-4693-883F-DE5DC5BA64B3](https://user-images.githubusercontent.com/32527656/219496242-02027446-d41b-4608-858d-33b2757ab9d8.jpeg)

**Comment by bradtchapman** [comment]
@jarro : This Bug's For You!

"Real men of genius...." 🎶

**Comment by RPNate1** [comment]
AGain this is stupid hyvor. Closing wsince it's a tiny issue we can't fix here
