### ISSUE TITLE
Bug: the Play/Pause button does not match the current state if app was backgrounded / paused

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#8]
The state of the Play/Pause button is not consistent with the actual state of the music.  

If RP playback was paused by another media source stealing focus, the "Pause" button ( II ) is shown when switching back to RP.  This is confusing because it should be showing the "Play" ( > ) button, to indicate that when tapped the music would resume.  

Tapping the green pause button causes music to resume, with no visible change in the icon.  

Tapping it again pauses the music, changing the button back to the light gray "Play" as expected.

No screenshot needed.

**Comment by RPNate1** [comment]
Just confirmed this bug.

**Comment by donshefer** [comment]
Fixed targeting build 28

**Comment by bradtchapman** [comment]
This is working correctly in build 29.
