### ISSUE TITLE
Can't open profile in Simple Mode

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#80]
open app
click play
Simple mode starts
try to click the profile icon
nothing happens

expected to be able to access the profile webview

**Comment by bradtchapman** [comment]
Confirmed — was able to reproduce this bug.

I would love for @BillGoldsmith to shed some light about when & how the user database schema changed, especially as it pertains to user IDs and avatars.

There's a **major** break in the format between old accounts and new accounts that seems to have occurred several years ago.  My profile ID is just 5 digits, created in 2006, but most newer profiles are 10 digits.  I scanned for "newer" old profiles and found some between 123570 - 123580 that were created on July 18, 2012.  

The JSON for an older user profile returns something like this:

```
uid: REDACTED
{"status":"ok","data":{"profile":{"user_id":"REDACTED","username":"REDACTED","avatar":"blank.gif","avatar2":"","location":null,"join_date":"Jul 18, 2012","occupation":null,"social_facebook":null,"social_instagram":"","fav_song":"","fav_band":"","fav_album":"","first_concert":"","ratings_num":"4","ratings_dist":[0,0,0,0,0,0,1,1,0,2]}}} 
```

What's interesting is that the value for `avatar` is `blank.gif` ... but on the webpage itself, that same profile shows `profile.jpg` as the avatar, not "blank.gif" .  Is there some code on the backend that loads "profile.jpg" as a substitute when the artwork is missing?  Could this explain why the app can't display anything?

Contrast that with a brand new account: the value for `avatar` is simply `null`.  See below...

```
uid: REDACTED
{"status":"ok","data":{"profile":{"user_id":"REDACTED","username":"REDACTED","avatar":null,"avatar2":"","location":"","join_date":"Feb 19, 2023","occupation":null,"social_facebook":null,"social_instagram":"","fav_song":"","fav_band":"","fav_album":"","first_concert":"","ratings_num":"0","ratings_dist":[0,0,0,0,0,0,0,0,0,0]}}} 
```

My brand new account created today shows the "anonymous" icon in the app as expected.

This is a data quality issue that @jarro needs to help address.  It affects everything the app does.

**Comment by jarro** [comment]
This is just some legacy quirks.   Not too complex though.

avatar2 takes precedence if  not an empty string.   And is 200x200

avatar  is  80x80 images.
but  ( blank.gif,  null,  empty string)  can be treated as no avatar set.  
And you can use your preferred placeholder image.

**Comment by donshefer** [comment]
fixed targeting build 35
