### ISSUE TITLE
No Channel history loading on Ipad(left column)

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#81]
Open info view
blank right column where channel play history should be

**Comment by RPNate1** [comment]
Update- the history shows after a song transition.

**Comment by bradtchapman** [comment]
This is different from #47 and #48 , right @RPNate1 ?

**Comment by RPNate1** [comment]
Yes, different.

**Comment by RPNate1** [comment]
I just haven't been prioritizing checking the iPad versions. Thanks!
