### ISSUE TITLE
🐞(b34): Menu flickering and auto-collapsing constantly

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#82]
### Issue Description

There appears to be a glitch in the menu that causes submenus to close every second, making it impossible to navigate and explore.  I can also see the word "Listen" flickering briefly at the top.

See attached recording. 

https://user-images.githubusercontent.com/32527656/219813713-ac9a5cc3-5f5c-4828-9a65-a9c9ff2198bc.MOV

**Comment by bradtchapman** [comment]
On further testing... I think I can reproduce it...

### Steps to reproduce

1. Sign out of any account if signed in.
2. Open the menu, then open a submenu.
3. If no observed issues, proceed to next step.
4. Sign into an account.
5. Repeat step 2-3.  If no issues, proceed to next step.
6. Force the app to quit.
7. Reopen the app — you should now be signed in.
8. Repeat step 2-3.  The menu should be flickering at this point.

I was able to get the menu to flicker after signing out, then signing in, then force-quit / relaunching the app.  Under normal use, this will start to occur for users when they pause the app for a while and come back to it, perhaps the next day.

**Comment by bradtchapman** [comment]
edit: this is stupid easy to reproduce.  Just start playing music and check the menu.  

100% reproducible on all devices.

**Comment by donshefer** [comment]
Fixed targeting build 35
