### ISSUE TITLE
👆Reopen (#23): when signed in, profile icon is invisible, not tappable, and does not show avatars/profile.jpg 

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#84]
### Description of issue

When logged in, the profile icon is completely empty and cannot be tapped at all.

### Workaround
None available from the app.  Must go to the RP website.  
I would have to sign out to restore the "silhouette" icon.

I think you are all **_overestimating_** the number of people with profile icons.  And if you want them to think about putting one, they need to be able to tap it! :) 

The icon needs to show **profile.jpg** if there is no icon.  Default to making an outline circle with a gray background, then **mask** any available icon with the circle (a mask is a kind of crop created by a non-square image).

**Comment by bradtchapman** [comment]
https://github.com/BillGoldsmith/iOS-bugfest/issues/80#issuecomment-1435925855

I believe the data quality mentioned in #80 applies to this issue, which was originally issue #23.

**Comment by RPNate1** [comment]
Still happening in build 37? @bradtchapman

**Comment by bradtchapman** [comment]
@RPNate1 

Yep, still happening.  

When the app launches (I'm still signed in) you can briefly see the silhouette until it tries to load my profile icon.  Then it displays nothing. 

On the plus side, the nothingnes IS tappable.  But with nothing visible to tap, the vast army of OG users with a blank profile icon (like me) will wonder why there is a gap at all.  I think i pointed this out in another comment: it's because the user profile JSON references artwork that no longer exists, but the website is substituting the generic profile icon.  The app is not.  

See below screen recording.  

https://user-images.githubusercontent.com/32527656/222008690-e842453b-c40b-4fb7-ad28-0ad9e34c4a05.MOV

**Comment by RPNate1** [comment]
The icon isn't showing up for Jon, as well (the area is clickable though). His is an older account like Brad's. The silhouette icon needs to be implemented for anyone that doesn't have an image.

**Comment by donshefer** [comment]
added a blind fix for this is build 46.
Someone who is seeing the issue needs to test. @bradtchapman

**Comment by bradtchapman** [comment]
Could @jarro manipulate the database and directly assign you the invalid profile icon?

**Comment by bradtchapman** [comment]
YES.  On build 46, it now shows the anonymous silhouette for my profile.
