### ISSUE TITLE
🐞(b34): UI: Progress bar is too wide, causes times to be truncated to ellipses.  

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#85]
### Description of Issue:

The new playback progress bar is too wide **_on all devices_** and the elapsed and remaining times are truncated to ellipses.  

- This is made worse if a user has **Dynamic Text Size** set to anything larger than the default.  
- This is a problem for most songs less than 10 minutes, and will be exacerbated by longer songs by Pink Floyd, Iron Butterfly, Dream Theater... 
- The numbers keep moving around because they are using **proportional width** instead of fixed width.  
- The built-in "Now Playing" widget uses **fixed-width** numerals. 

### Recommended Fix:

1. Use **fixed-width numerals** in the SF Pro font so the numbers don't move around
2. Reduce the width of the progress bar to make more room.
3. The progress bar should adapt to the space consumed by the numbers at any text size.
4. Plan to size everything for a hypothetical song of 58:58 elapsed, -58:58 remaining 
5. Double check everything with Dynamic Text Size set to each larger size above the default.
6. Optionally check the plus sizes available via Accessibility.

Using Fixed Width numerals: 
https://developer.apple.com/documentation/uikit/uifont/1619022-monospaceddigitsystemfontofsize

The Apple Human Interface Guideline **strongly advises** developers to leave a safety margin along the edge.  See: https://developer.apple.com/design/human-interface-guidelines/foundations/layout/

See attached screenshot.
![IMG_0063](https://user-images.githubusercontent.com/32527656/219908064-502e2790-5a68-469d-a0e7-d92530ff6577.PNG)

**Comment by bradtchapman** [comment]
Videos demonstrating issue on iPad with truncated numbers disappearing and reappearing due to proportional width instead of fixed width

https://user-images.githubusercontent.com/32527656/219908493-eb66a578-750d-4554-bcd7-8e0cf60fc706.mp4

**Comment by bradtchapman** [comment]
demonstration of issue on iPhone with dynamic text size changes.  Even **one click** above default causes truncation.  

Your **core** user base for RP skews older, definitely 35 and up.  A fair amount of them are going to have dynamic text size adjusted to compensate for failing eyesight, even if they're not going to admit it.  Far-sighted users need this more than near-sighted users.  

Recent data from the American Optometric Association shows that **60% of Americans are far-sighted and 30% are nearsighted.**

**Comment by bradtchapman** [comment]
https://user-images.githubusercontent.com/32527656/219910152-777826e0-f2c0-4c03-8de8-35c556466bd3.MOV

**Comment by donshefer** [comment]
Fixed targeting build 35
I tested this on the larger text sizes which works fine. But to support the very large text sizes for full accessibility is going to require some UI changes and trade offs.

**Comment by bradtchapman** [comment]
Yeah I don't expect the app to accommodate the **extreme** sizes, just the normal range. Thank you!  Awaiting build 35....

**Comment by bradtchapman** [comment]
@donshefer : thanks, this is a more comfortable progress bar now.

I would still ask you to consider using **fixed width numerals** in SF Pro.  The numbers won't dance around like they do now.

**Comment by RPNate1** [comment]
Noticed this last week at the end of Friday, but hadn't had time to report. Thanks for fixing.
