### ISSUE TITLE
🎵(b35): API: /api/gapless sometimes returns songs that are not found (404).  Legacy /api/play for same event id is OK.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#86]
### Description of issue

In build 34, I am still seeing the issue that was originally discussed in #55.  

Now that I've started monitoring RP's application activity in **Charles Proxy**, I can see a lot more detail about what's happening, with hard evidence of the app loading album art... but not playing any music.

### Analysis

It looks like the application does a GET from `/api/gapless` just fine, and the server returns `current_event_id` of 2399993.  Logically, this should trigger the retrieval of `/audio/gapless/0/2/2399993.m4a` and the next few files thereafter.  

The next request, however, is where we are seeing the problem:

`GET api.radioparadise.com /api/update_history?player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&chan=0&event=2399809.0&song_id=0&time=1676911280.719687&country_code=US&source=7 HTTP/1.1`

This request to `/api/update_history` with an `event` value of `2399809` is **rejected** by the server (HTTP 400 Bad Request), but then the application insists on using these event IDs to request a few songs anyway: 2399809, 2399810, 2399811, 2399812.   These are NOT found.

So where is the application getting these old event IDs?  

They were the songs I was playing from my previous session.  Why is it hanging on to them?

### Data

https://www.dropbox.com/s/uxn4prclg901id0/rp-app-stall-002.chls?dl=0

You will need to install Charles Proxy for Windows or Mac to read this file.

This contains a "packet trace" of queries and responses for the beta app and the production app.  The recording starts at 8:40:54 AM.  Playback attempts in beta are between 8:41:20 - 8:42:09.  Then at 8:42:30 I switch to the legacy / production RP app and load the main mix.  The audio loads immediately using the **same event id** of 2399993.

**Comment by bradtchapman** [comment]
Timestamped video recording for demonstration, to be reviewed alongside the Charles proxy file.

https://user-images.githubusercontent.com/32527656/220169012-b790dd09-8c47-47de-9db6-3a5ad1e18067.mp4

**Comment by bradtchapman** [comment]
Another example of what happens when the app is asleep for a long time.  I paused the "Mellow Mix" about 8 hours ago, then opened the app and pressed "Play."  It continued playing "Mirrorball" by Elbow.  It also sent updates to the API on the /pause/ and /update_history endpoints.  When Mirrorball was done, the app attempted to load a couple more songs: `/audio/gapless/1/2/783428.m4a`, and `/audio/gapless/1/2/783427.m4a`, which, of course, don't exist.

**Comment by bradtchapman** [comment]
```
Wed Feb 22 00:16:30 PST 2023	https://api.radioparadise.com/api/pause?chan=1&source=7&pause=168270.039969&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&event=783426.0	200	HTTP/1.1	application/json	192.168.2.4	GET	api.radioparadise.com	/api/pause?chan=1&source=7&pause=168270.039969&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&event=783426.0	170	43	24506	Complete	
Wed Feb 22 00:16:30 PST 2023	https://api.radioparadise.com/api/pause?source=7&pause=168270.039969&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&chan=1&event=783426.0	200	HTTP/1.1	application/json	192.168.2.4	GET	api.radioparadise.com	/api/pause?source=7&pause=168270.039969&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&chan=1&event=783426.0	100	3	2104	Complete	
Wed Feb 22 00:16:31 PST 2023	https://api.radioparadise.com/api/update_history?chan=1&time=1677053471.2919178&source=7&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&country_code=US&song_id=40998&event=783426.0	200	HTTP/1.1	application/json	192.168.2.4	GET	api.radioparadise.com	/api/update_history?chan=1&time=1677053471.2919178&source=7&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3&country_code=US&song_id=40998&event=783426.0	106	3	1795	Complete	
Wed Feb 22 00:19:19 PST 2023	https://audio-geo.radioparadise.com/audio/gapless/1/2/783428.m4a	404	HTTP/1.1	text/html	192.168.2.4	GET	audio-geo.radioparadise.com	/audio/gapless/1/2/783428.m4a	251	55	31143	Complete	
Wed Feb 22 00:19:19 PST 2023	https://audio-geo.radioparadise.com/audio/gapless/1/2/783427.m4a	404	HTTP/1.1	text/html	192.168.2.4	GET	audio-geo.radioparadise.com	/audio/gapless/1/2/783427.m4a	245	57	31153	Complete	
```

The response from /api/pause, in both cases, was this:

```
<head>
<title>Nothing. No thing. Nada. Zip. Null. Void. etc.</title>
</head>
<body>
<div style="font-face:courier;font-weight:bold;font-size:24px;line-height:100px;text-align:center;margin:0;color:#999;height:100%;width:100%;" >
<br />
Nothing to see here.
<br />
Nothing. No thing. Nada. Zip. Null. Void. etc.
<br />
Move along now...
</div>
```

**Comment by bradtchapman** [comment]
The app looks like this:

- Progress bar has returned to 0:00
- Play symbol shows green "pause" as if music was still active
- pressing PSD does nothing (it tries to load song id's 783429, 783430
- pressing PSD several more times causes the app to request the same songs from /api/gapless

The app should be more stateful about when music actually runs out, and respond to "404 Not Found" by refreshing the playlist and getting new music.

**Comment by bradtchapman** [comment]
Finally, pressing Pause/Play results in the following request:

```
Wed Feb 22 00:32:41 PST 2023 | https://api.radioparadise.com/api/gapless?C_user_id=1027019984&source=7&event=0.0&bitrate=2&numSongs=5&chan=1&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3 | 200 | HTTP/1.1 | application/json | 192.168.2.4 | GET | api.radioparadise.com | /api/gapless?C_user_id=1027019984&source=7&event=0.0&bitrate=2&numSongs=5&chan=1&player_id=D8EC7CD0-1791-449E-B703-9950810B44C3 | 134 | 7 | 8574 | Complete |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

and the following response with current_event_id 783565, which is the current set of songs playing right now on Mellow.

```
{
	"channel": {
		"chan": "1",
		"title": "RP Mellow Mix",
		"stream_name": "mellow"
	},
	"bitrate_title": "128k aac",
	"extension": "m4a",
	"imgage_base": "\/\/img.radioparadise.com\/",
	"current_event_id": 783565,
	"max_gapless_event_id": 783595,
	"slideshow_path": "slideshow\/720\/",
	"songs": [{
		"song_id": "382",
		"artist": "Big Head Todd and the Monsters",
		"title": "It's Alright",
		"year": "1993",
		"duration": 225500,
		"album": "Sister Sweetly",
		"user_rating": 0,
		"rating": 6.9,
		"cover_art": "covers\/l\/B000002L12.jpg",
		"event_id": 783427,
		"gapless_url": "https:\/\/audio-geo.radioparadise.com\/audio\/gapless\/1\/2\/783427.m4a",
		"slideshow": [
			"25193",
			"38383",
			"37954",
			"13513",
			"64467",
			"45230",
			"36668",
			"66126",
			"44889",
			"42663",
			"13986",
			"27545",
			"39381",
			"46163",
			"26872",
			"18404",
			"43754",
			"36409",
			"49729",
			"60703",
			"43159",
			"45720",
			"30376",
			"36125",
			"26971"],
		"cue": 85000,
		"type": "M",
		"ratings_num": 943,
		"ratings_dist": [
		17,
		17,
		28,
		35,
		61,
		110,
		286,
		237,
		99,
		52]
	}, {
		"song_id": "38709",
		"artist": "Jack Johnson",
		"title": "Upside Down",
		"year": "2006",
		"duration": 205800,
		"album": "Curious George Soundtrack",
		"user_rating": 0,
		"rating": 6.6,
		"cover_art": "covers\/l\/B000CR7RDE.jpg",
		"event_id": 783428,
		"gapless_url": "https:\/\/audio-geo.radioparadise.com\/audio\/gapless\/1\/2\/783428.m4a",
		"slideshow": [
			"24052",
			"66328",
			"64457",
			"64937",
			"45869",
			"40776",
			"23325",
			"58558",
			"26751",
			"18293",
			"55042",
			"48893",
			"24847",
			"41352",
			"28463",
			"33289",
			"54320",
			"24060",
			"41086",
			"71204",
			"17152",
			"39933"],
		"cue": 0,
		"type": "M",
		"ratings_num": 514,
		"ratings_dist": [
		14,
		19,
		34,
		23,
		24,
		65,
		156,
		105,
		44,
		29]
	}, {
		"song_id": "39263",
		"artist": "The Decemberists",
		"title": "Summersong",
		"year": "2006",
		"duration": 202000,
		"album": "The Crane Wife",
		"user_rating": 0,
		"rating": 6.7,
		"cover_art": "covers\/l\/B000HKDEEW.jpg",
		"event_id": 783429,
		"gapless_url": "https:\/\/audio-geo.radioparadise.com\/audio\/gapless\/1\/2\/783429.m4a",
		"slideshow": [
			"37976",
			"18783",
			"52368",
			"6740",
			"39422",
			"33538",
			"63472",
			"43627",
			"60492",
			"17760",
			"38711",
			"46527",
			"34320",
			"17758",
			"53415",
			"33317",
			"32185",
			"47448",
			"18202",
			"48479",
			"53697",
			"24751"],
		"cue": 0,
		"type": "M",
		"ratings_num": 1131,
		"ratings_dist": [
		27,
		24,
		44,
		34,
		73,
		141,
		409,
		268,
		87,
		24]
	}, {
		"song_id": "0",
		"artist": "Commercial-free",
		"title": "Listener-supported",
		"year": "",
		"duration": 5131,
		"album": "",
		"user_rating": 0,
		"rating": 0,
		"cover_art": "covers\/l\/105.jpg",
		"event_id": 783430,
		"gapless_url": "https:\/\/audio-geo.radioparadise.com\/audio\/gapless\/1\/2\/783430.m4a",
		"slideshow": [
			"22593",
			"23835",
			"10962",
			"23886",
			"13466"],
		"cue": 0,
		"type": "P",
		"ratings_num": 0,
		"ratings_dist": [
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0]
	}, {
		"song_id": "3011",
		"artist": "Bruce Springsteen",
		"title": "I'm On Fire",
		"year": "1984",
		"duration": 141761,
		"album": "Born In The U.S.A.",
		"user_rating": 0,
		"rating": 7.8,
		"cover_art": "covers\/l\/B0000025UW.jpg",
		"event_id": 783431,
		"gapless_url": "https:\/\/audio-geo.radioparadise.com\/audio\/gapless\/1\/2\/783431.m4a",
		"slideshow": [
			"50600",
			"24064",
			"33670",
			"44651",
			"17724",
			"49620",
			"48268",
			"52607",
			"69580",
			"48705",
			"59759",
			"17295",
			"42545",
			"2272",
			"71969",
			"15358"],
		"cue": 0,
		"type": "M",
		"ratings_num": 2381,
		"ratings_dist": [
		56,
		24,
		49,
		38,
		60,
		133,
		386,
		778,
		554,
		303]
	}]
}
```

Why is the gapless API sending `event_id` values that are not on `audio-geo` anymore?

**Comment by RPNate1** [comment]
@mtnbrit Take a look at this. We need to sort this out.

**Comment by bradtchapman** [comment]
@jarro @mtnbrit @donshefer @RPNate1 

More information: when this does occur, it takes about 30-45 minutes of checking the same station before the app retrieves new music.  

I have to listen to another station in the meantime, but I'm switching back and forth to the stalled station every few minutes to see if it recovers.

**Comment by jarro** [comment]
@bradtchapman   This should be fixed now.  If you run into it again let me know.

**Comment by bradtchapman** [comment]
@jarro : 

No, I literally just triggered it again here at 3AM.  A Nick Drake song had been playing on RP Main before I went to sleep.  I woke up, opened the app, hit Play, and the song concluded.  I then heard a "Thanks for Listening" bumper, and then the music stopped even though the app looks like it's playing. 

I'm not in front of the Mac or connected to Charles Proxy to inspect the traffic.  

It's raining cats and dogs here in Los Angeles.

**Comment by bradtchapman** [comment]
@jarro : update: the app did finally appear to "stop."  I pressed Play, and it picked up Chris Isaak's Round 'n' Round, which is what is currently playing on RP Main.

So now, I guess I should ask: @donshefer @RPNate1 : what is the app's responsibility when it encounters this situation?

**Comment by bradtchapman** [comment]
@RPNate1 :

As an end user I'd like it to keep playing new music automatically after the previous set of gapless expires or runs out and the server says "it's time to load some new stuff."

If the app needs a minute to load something, it should play a standard 10-15 second bumper/promo to cover the condition while it loads the next bit of music.  This bumper would ideally be something built into the app that is only used in case of a rate technical difficulty.  This is a really common thing done in professional radio.  Even William would agree that "dead air" is a huge sin, and you do everything possible to avoid it.  

IF and ONLY if the app truly runs out of music and can't do anything else (like a network error), THEN inform the user with a message on screen ("Unable to contact RP.").

**Comment by jarro** [comment]
There are new fields added for managing this issue.  
 Before attempting to play a file.  
The app needs to use  sched_time_millis  and timeout_millis  to check if the current position has timed out.    The timeout is currently 45 minutes and some songs are in that range,  so you do need to use the seek position in the file as part of the calculation.

**Comment by bradtchapman** [comment]
And since tracks eventually must expire from audio-geo, how far **ahead** is gapless preparing tracks for audio-geo when someone (ab)uses the PSD / skip button?  24 hours?

**Comment by donshefer** [comment]
We've implemented a new server based song timeout which should (hopefully) address this issue.
Please retest in build 39.

**Comment by RPNate1** [comment]
Test in b39  @bradtchapman
