### ISSUE TITLE
👆(b35): Settings pane does not scroll; cannot access "Log Out" or "Log In" at the bottom.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#87]
### Description of issue

The settings pane is not a scrollable view; therefore, the items at the bottom can no longer be reached.  The way this impacts iPhone users on smaller screens (4.0 - 4.7") is that once someone logs in, they would not easily be able to log out again because the "Log Out" item is totally or partially obscured.

It would solve the immediate problem for the iPhone SE, and make it easier to add more stuff to Settings in the future, if this pane were simply made scrollable.

See attached screenshots for the Logged in vs. Logged Out view.  In both cases, the control is partially or totally cropped off screen.

**Comment by bradtchapman** [comment]
Logged in: 

![IMG_0047](https://user-images.githubusercontent.com/32527656/220187259-eb345ae7-1393-4604-8bde-ed7c5ae87e42.PNG)


Logged out:

![IMG_0048](https://user-images.githubusercontent.com/32527656/220187440-0db7af45-2e0c-489d-9c5c-b52673f9f3ff.PNG)

**Comment by RPNate1** [comment]
@bradtchapman now?

**Comment by donshefer** [comment]
@bradtchapman I need to know the configuration of this device for these screenshots. 
Model, iOS version, and what accessibility features are on, like the text and screen size so I can replicate the issue.

**Comment by RPNate1** [comment]
I assume this is fixed now?
