### ISSUE TITLE
🔎(b35) Regression: icons on top menu are no longer blocked when Settings or "Kebab" is open

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#88]
### Description of Issue
The "no tap zone" of dark grey seems to have changed in build 35 so that icons across the top of the screen are clickable when Settings or the Kebab is open.  Was this because of work done to showcase the support pill, or just an accidental trim somewhere?

### Acceptable Builds
This was working fine in b30 - b34.

See attached video.

https://user-images.githubusercontent.com/32527656/220188437-69152793-7b92-4999-833a-c7a98cae92d9.MP4

**Comment by donshefer** [comment]
fixed in build 42
