### ISSUE TITLE
🔎(b35): UI: Support meter is not filled in accurately (only showing 70% full)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#89]
### Description of issue:

I recognize that b34 had a placeholder / FPO support meter.  Now that the meter is being drawn dynamically, it also needs to be accurate.  Currently it looks like the meter is 70% full (colors 1-7 are filled in).

This is happening on iPhone and iPad.

See attached screenshot.  

![support-pill-drawing](https://user-images.githubusercontent.com/32527656/220189011-29955bb0-484f-4b3c-aa5d-5ad4e9c3e4c5.jpg)

**Comment by RPNate1** [comment]
It's my understanding it's not fully implemented yet. Currently in progress.
