### ISSUE TITLE
Bug: History: pausing the app for a short while results in a large, persistent gap in History.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#9]
_(These are notes from my previous email dated January 20, 2023)._

1. If playback is stopped on a channel at any point in time, whether intentionally or because media was playing elsewhere on the device, the history view is now stuck in time and does not update.

2. On resuming playback for the same channel, the history adds the most recent track but there's a huge gap in time.

3. Switching to a different station with the history view open shows the complete play history for those stations as expected, no gaps in time.

4. Switching *back* to the previous channel still shows the history with a missing gap.  It's not loading the list from the website in the expected manner.

5. While playing the 'resumed' song, the history view shows that song on top with its starting timestamp.

The following screenshots show the history tab for the RP Rock Mix, and the RP Mellow Mix, after RP was paused for an hour on the Rock Mix station (between 3:00 - 4:00 PM).

![IMG_9965](https://user-images.githubusercontent.com/32527656/214940267-1b49dbe9-c77c-472e-8f17-6006be83ef9d.PNG)

![IMG_9964](https://user-images.githubusercontent.com/32527656/214940252-5ef92a6b-3458-4b00-a067-15eab2182519.PNG)

**Comment by RPNate1** [comment]
This should always just display the play history of the channel. Not the client play history.

**Comment by donshefer** [comment]
@bradtchapman Can you please retest this? I believe this was fixed with updates to the player logic.
