### ISSUE TITLE
🔎(b35): UI: Menu "mask" changed in b35, now misaligned (different for each device)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#90]
### Description of issue

The mask ("no-tap" zone) created by the app menu is not blocking the same content across all devices.  Additionally, it is misaligned so as to create unsightly bright lines when the menu is open. 

See attached shots of iPhone SE and iPad mini 6.

![IMG_0051](https://user-images.githubusercontent.com/32527656/220189783-aa7098ef-d2f1-4599-80ea-f6d23647116e.PNG)

![IMG_0068](https://user-images.githubusercontent.com/32527656/220189794-9d8bc1cc-42f3-4ab7-9b1a-be5206f355d8.PNG)

**Comment by donshefer** [comment]
fixed in build 42
