### ISSUE TITLE
🔎(b35): UI detail: the profile icon is now cropped at the screen edge (low priority)

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#91]
### Description of issue:

The profile icon has shifted in a recent build so that it is cropped slightly at the edge of the screen.

### Expected behavior
The icon just needs to be moved over a bit to keep it away from the edge of the screen.  Please keep the 'safe areas' in mind, per Apple's layout guidance.

https://developer.apple.com/design/human-interface-guidelines/foundations/layout/

See attached screenshot.

Thanks!

![IMG_0046](https://user-images.githubusercontent.com/32527656/220190209-edefd611-252a-430d-abc5-31e70dd95f32.jpg)

**Comment by donshefer** [comment]
@bradtchapman For all tickets, but especially ones with UI spacing issues, we would appreciate if you would please indicate the Apple device model and iOS version in the ticket.
Thank you. =)
I have been trying to find a gen1 SE simulator, but not found one yet.

**Comment by bradtchapman** [comment]
> I have been trying to find a gen1 SE simulator, but not found one yet.

It's not shown in Xcode by default, but you can add it under the Devices & Simulators list as demonstrated below...


https://user-images.githubusercontent.com/32527656/221278103-9d2f7593-f059-42e1-aa52-4edd6cba6eeb.mp4

**Comment by bradtchapman** [comment]
fyi @RPNate1: this issue appears to be fixed in b37, so it was just a slight adjustment.

@donshefer : were you able to find the iPhone SE 1st gen simulator as illustrated above?
