### ISSUE TITLE
🐞(b35): Unexpected: Info mode shows slideshow instead of album art, even if setting had been off.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#92]
### Description of issue

After upgrading from b34 to b35, the info mode unexpectedly showed me the slideshow instead of the album art even though the setting had been OFF.

### Workaround

1. Go to Settings.
2. Turn 'info mode slideshow' on
3. Turn 'info mode slideshow' off.

### Reproducibility
This happened one time on iPad mini 6 and iPhone SE (haven't checked iPhone 12 Pro yet).  Unfortunately I was only able to observe this one time.  Once I've changed it, it seems to remember it permanently.  So I don't know where this setting is stored. 

I also tried rolling back to b34, then upgrading to b35, but no luck.  

### Expected behavior. 

I assumed the app would always dictate the experience that I chose for the info view: either slideshow or album art.  

### Initial Theories
1. A setting like `info_view_slideshow == true` was accidentally baked into b35 as a default, temporarily overriding any previous user preference.
2. The website default behavior was changed to show the slideshow, regardless of user preference in the RP app, and the app doesn't know which state the website will send.

#### Network (Charles Proxy)
1. Setting the preference either way does not send any information to the server about this choice.
2. The app makes a request from `api/nowplaying_list_v2022` to retrieve the album art and slideshow images.  
3. There is no meaningful difference between the request when the setting is turned on vs. off. 

#### Web Browser (on computer)
1. RP's main website has a toggle for info view slideshow.
2. While recording the browser interactions, I found references in the **Timeline** to the JavaScript **`main.js`** ; specifically, a call to this function: "clickOptionShowMiniSlideshow(i)" on **Line 22381.**
3. Therefore, I assume the app triggers a JavaScript call to show this setting.

Based on the JavaScript and what I know so far, I'd like to ask @jarro if there was a change to default behavior on testing.radioparadise.com recently.

### Suggestion
Do you think it's wise to have the app just send the current user preference when the info view is loaded?  Either show slideshow or show album art.

See attached screen recordings for demonstration of behavior.

iPhone SE, then iPad mini 6...

**Comment by bradtchapman** [comment]
Demonstration of unexpected behavior on iPhone SE :

https://user-images.githubusercontent.com/32527656/220197659-461b449c-7576-473a-be7f-5ff055a03e3a.mp4

**Comment by bradtchapman** [comment]
Demonstration of unexpected behavior on iPad mini 6:

https://user-images.githubusercontent.com/32527656/220197693-774dbae5-1832-4855-af07-96f91b480de9.mp4

**Comment by donshefer** [comment]
After some testing I found this happening when the app was removed and reinstalled.
Fixes targeting build 39.

**Comment by RPNate1** [comment]
fixed apparently in b39
