### ISSUE TITLE
📡API:  Refreshing a feed unexpectedly loaded 3 different songs for 2 different values of current_event_id.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#94]
### Description of Issue:

While switching stations for bug testing, I noticed that sometimes the RP app would load **different** songs on the **same** station, if I quickly switched back and forth.  I suspect this is more common near the boundary of a song change.

Now that I am scrutinizing RP's communication with Charles Proxy, I think I have an explanation for the unexpected behavior.  I don't have a root cause, obviously, since I can't see anything server side.  That's where @jarro comes in!  :-) 

### Demonstration and Breakdown

Attached is a screen recording of the raw JSON being loaded and refreshed in a web browser at a rapid rate.  The content doesn't change on every refresh, but it does change frequently.  

The page being shown is the metadata for the **RP Global Mix** (chan 3; "main" is chan 0).  You will see a `current_event_id` of 632503, then it changes to 632505.  But during these 20 seconds, you will see three different tracks appear:

#### song_id 38091
Artist:  Amadou & Mariam
Title: M' Bife Balafon
Year: 2004
Album: Dimanche à Bamako

#### song_id 39483
Artist:  Alpha Yaya Diallo
Title: N'Dare
Year: 2001
Album: The Journey

#### song_id 40453
Artist: Vieux Farka Touré
Title: Bullet the Blue Sky
Year: 2008
Album: In the Name of Love - Africa Celebrates U2

The following transcript indicates the **timestamps** when the song ID's **changed**, even though I was refreshing the page multiple times per second.

> 0:00 — current_event_id: 632503, song_id 38091, event_id 632505
> 0:02 — current_event_id: 632505, song_id 39483, event_id 632503
> 0:03 — current_event_id: 632505, song_id 38091, event_id 632505
> 0:05 — current_event_id: 632505, song_id 39483, event_id 632503
> 0:07 — current_event_id: 632505, song_id 40453, event_id 632506
> 0:08 — current_event_id: 632505, song_id 39483, event_id 632503
> 0:09 — current_event_id: 632505, song_id 38091, event_id 632505
> 0:10 — current_event_id: 632505, song_id 39483, event_id 632503
> 0:11 — current_event_id: 632505, song_id 40453, event_id 632506
> 0:13 — current_event_id: 632505, song_id 38091, event_id 632505
> 0:15 — current_event_id: 632505, song_id 39483, event_id 632503
> 0:17 — current_event_id: 632505, song_id 38091, event_id 632505
> 0:18 — current_event_id: 632505, song_id 40453, event_id 632506
> 0:20 —current_event_id: 632505, song_id 38091, event_id 632505 

https://user-images.githubusercontent.com/32527656/220200418-51c78be1-5671-4a63-a85d-ff37f0df2b92.mp4

**Comment by bradtchapman** [comment]
Is this a **_normal_** and **_expected_** part of the "randomization" built into the music APIs to prevent all users from downloading the same songs at the same time?  Or something entirely different?

**Comment by jarro** [comment]
Yeah, what you are seeing is the randomization.   
If you have played a channel/song though,  it shouldn't return to anything before that played song.    Relies on multiple api calls though so if done fast might be able to get a random response when you shouldn't.

**Comment by RPNate1** [comment]
@jarro @donshefer

**Comment by RPNate1** [comment]
I totally missed that reply. thanks!
