### ISSUE TITLE
🔬(b36): Honey, I shrunk the login window!

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#95]
For some reason the login window shrank to half its size in build 36!  This screenshot was taken on my iPhone 12 Pro.  I was able to interact with it normally.

Was Don inspired by "Ant-Man: Quantumania?"

![28E57B59-1011-447B-B817-99552E14204B](https://user-images.githubusercontent.com/32527656/220988517-e999458f-3d35-406b-bc99-cc27f23fe778.png)

**Comment by bradtchapman** [comment]
also happening on iPhone SE 1st gen, so I have to assume this was an accident. 

See attached.

![2D6A22DC-9192-4483-980E-27F7899D87F7](https://user-images.githubusercontent.com/32527656/221019660-f1c59d84-5413-46fc-a2a9-80b57917965f.png)

**Comment by donshefer** [comment]
fixed targeting build 37
