### ISSUE TITLE
⏳(b37): the app pauses for 1 second when returning from slideshow or "car mode" before loading song info view

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#97]
### Description of issue

This has been going on for many versions but I've narrowed it down to the most egregious conditions.  

While navigating around the app, if I go into Slideshow or Car Mode (not CarPlay), upon exiting either of these modes, the screen is black for approximately one second before it loads the song info content from the site.

Can you please verify that there is no artificial delay at these transitions?

### Workaround

None.  Baked into the app.

### Expected Behavior

It would be great if the car mode and slideshows sat on top of the main view so that when a user closes either of them, the app goes right back to where they had been without forgetting all the content that was already loaded on screen and having to load it again.  Fresh calls for data burn extra CPU cycles, they waste data, and make the user think the app is "slower" than it ought to be.

Users should be able to navigate instantly between these views with no delay and no refresh:

- Simple Mode > Car Mode > (exit) > Simple Mode
- Song Info > Car Mode > (exit) > Song Info mode
- Simple Mode > Slideshow > (exit) > Simple Mode
- Song Info > Slideshow > (exit) > Song Info mode

The simple mode or song info view should be loading content in the background while the car or slideshows are on screen.

**Comment by RPNate1** [comment]
@donshefer let's make the expected behavior above happen. We can discuss it when you're back.

**Comment by RPNate1** [comment]
The delay is normal in refresh. Nothing to be done. The returning to previous mode appears to work.
