### ISSUE TITLE
🔎(b37): UI: menu grows too long to be easily navigated

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#98]

**Comment by bradtchapman** [comment]
### Descripton of issue: 

The menu leaves all the sections expanded after opening, which makes it kinda long.  

### Expected behavior:

If I open another section, maybe collapse the other one that was open, so that only one section is open at a time.

**Comment by bradtchapman** [comment]
@RPNate1 : meaning my "expected behavior" is how the menu should behave, not leaving all branches open all the time?

**Comment by RPNate1** [comment]
> @RPNate1 : meaning my "expected behavior" is how the menu should behave, not leaving all branches open all the time?

yep!

**Comment by donshefer** [comment]
Unfortunately, the SwiftUI List() element used for this doesn't support programmatic control of the expanded/collapsed states. So supporting this feature would require rebuilding this using different elements, which is doable, but going to take some time. 
I feel like to cost for this feature is far greater than it's benefit. @RPNate1 If you feel strongly about it, let's discuss options.

**Comment by bradtchapman** [comment]
It's still worth filing feedback with Apple to include this.  They like hearing from small app developers with good stories to tell.

feedbackassistant.apple.com
Sign in with the Apple ID tied to Radio Paradise (for signing and publishing the app).

-Brad

—Sent from my iPhone
