### ISSUE TITLE
🌡(b37): UI: Support meter now looks totally empty.  /api/cache_support_meter is returning valid data

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#99]
### Description of issue:

The support meter shows 0% today (March 1) even though it's actually at 42% accodding to the website. 

Are they both using the exact same data source and is it kept up to date in every applicable location? 

Observed at 4:00 AM PST.  See attached screenshots. 

Will check again later today.

For future builds or the next phase of this project, think about having the app poll the support meter value once a day and redraw it, just in case people leave RP running for extended sessions.  Stagger the reload time by a few minutes +/- to avoid a DDOS from every client hitting the server at midnight in their respective time zones.  

![4E7DA947-2E6E-49BC-A36D-8556D1E0172C](https://user-images.githubusercontent.com/32527656/222135867-7457e1a7-ea46-4b4b-9324-b0d2e3413aad.jpeg)

![FE468160-B02F-431C-A691-69C9FCA2A1E0](https://user-images.githubusercontent.com/32527656/222135875-e7ce1a7e-e927-40d2-b0b1-6dfd34f7b2ec.jpeg)

**Comment by bradtchapman** [comment]
@RPNate1 @jarro @donshefer 

Edited the issue title to reflect what is actually happening.

The API conversation goes like this:

https://img.radioparadise.com/api-data/api/cache_support_meter
```
curl  -H "User-Agent: RadioParadiseMk2/37" https://img.radioparadise.com/api-data/api/cache_support_meter
```

And the response:

`{"support_meter_percent":49}`

This indicates that the app is receiving the meter value, but not drawing it.

**Comment by donshefer** [comment]
fixed targeting build 39

**Comment by RPNate1** [comment]
fixed in b39
